Samsung/ONE-vscode

LICENSE
* Apache License Version 2.0
Signed-off-by: Sung-Jae Lee <sj925.lee@samsung.com>
=> Add license document

README.md
- Create gitter.im chat room `Samsung/ONE-vscode` and add badge to link.
Signed-off-by: Sung-Jae Lee <sj925.lee@samsung.com>
=> Open community chat channel in gitter.im

.gitignore
This will introduce initial .gitignore file for working with VSCode.
Signed-off-by: SaeHie Park <saehie.park@samsung.com>
=> Initial .gitignore

.clang-format, infra/format
This will introduce format checker using clang-format
- Copied portion from ONE repo
Signed-off-by: SaeHie Park <saehie.park@samsung.com>
=> Introduce format checker

COPYRIGHT
Signed-off-by: Sung-Jae Lee <sj925.lee@samsung.com>
=> Add COPYRIGHT

.gitignore
This will revise .gitignore to include format.patch and local Makefile.
And remove package-lock.json from ignore file.
=> Revise .gitignore

.vscodeignore, package-lock.json, package.json, src/extension.ts, tsconfig.json
This will introduce initial empty vscode extension created from yo tools.
=> Introduce initial empty vscode extension

.github/workflows/check-pr-format.yml
Add initial PR format checker.
=> Enable PR format checker

src/Project.ts, src/Project/Builder.ts
This will introduce initial empty project builder.
=> Introduce initial project builder

src/Utils.ts, src/Utils/Balloon.ts
This will introduce Utils/Balloon to show notification balloon window.
=> Introduce Utils/Balloon

src/Utils.ts, src/Utils/Logger.ts, src/extension.ts
This will introduce Utils/Logger to show logs in VSCode output window
to show compile outputs and others.
=> Introduce Utils/Logger

src/Project/WorkFlow.ts
This will introduce WorkFlow that will manage compilation jobs.
=> Introduce WorkFlow

src/Project/Job.ts
This will introduce Job interface for compilation jobs.
=> Introduce Job interface

src/Project/JobMixins.ts
This will introduce JobMixins module for mixins with MixinInOutPaths for Job classes.
=> Introduce JobMixins

src/Project/WorkJobs.ts
This will introduce WorkJobs as alias of Array<Job>.
=> Introduce WorkJobs

src/Project/JobBase.ts
This will introduce JobBase class as base class for Jobs implementations.
=> Introduce JobBase

src/Project/Builder.ts
This will fix error handle in Builder with execption error message.
=> Fix error handle in Builder

src/Project/JobRunner.ts, src/Project/WorkFlow.ts
This will introduce JobRunner that will run jobs of WorkJobs.
=> Introduce JobRunner

.github/workflows/check-pr-tsc.yml
This will enable TypeScript compilation for PRs.
=> Enable TypeScript compilation for PRs

src/Project/JobRunner.ts, src/Project/ToolRunner.ts
This will introduce ToolRunner that will invoke the tool of the Job given.
=> Introduce ToolRunner and use it

src/Project/WorkFlow.ts
This will implement start with validation and calling job runner.
=> Implement start of WorkFlow jobs

.eslintignore
This will introduce eslintignore file for eslint.
=> Introduce eslintignore

src/Project/WorkFlow.ts
This will add addJob method to WorkFlow.
=> Add addJob for WorkFlow

package.json
This will sort vscode item in package.json file.
=> Sort package json for vscode

src/Project/BuilderJob.ts
This will introduce BuilderJob interface to buildup builder jobs.
=> Introduce BuilderJob

src/Project/JobOptimize.ts
This will introduce minimum JobOptimize implementation for running
one-optimize command.
=> Introduce JobOptimize

src/Project/JobQuantize.ts
This will introduce minimum JobQuantize implementation for running
one-quantize command.
=> Introduce JobQuantize

src/Project/Builder.ts
This will revise Builder to inherit BuilderJob.
=> Builder inherit BuilderJob

src/Project/Builder.ts, src/Project/WorkFlow.ts
This will add WorkFlow clear and revise Builder to call in init.
=> Builder init to clear WorkFlow

package-lock.json, package.json
This will add ini to package list.
=> Add ini to package

src/Project/Builder.ts
This will remove unused import in Builder.
=> Remove unused import in Builder

package.json, src/extension.ts
This will and command for import cfg file.
=> Add command for import

src/Project/BuilderCfgFile.ts
This will add validate cfg step in import.
=> Validate cfg in import

.gitignore, .vscode/extensions.json, .vscode/launch.json, .vscode/settings.json, .vscode/tasks.json
This will include .vscode folder and files.
=> Include .vscode

src/Project/BuilderCfgFile.ts
This will enable import of one-import-tf from cfg.
=> Enable import of one-import-tf from cfg

src/Project/Builder.ts, src/Project/BuilderJob.ts
This will add two callback methods in BuilderJob and implemnts in
Builder class.
=> [Project] Add two methods in BuilderJob

src/Snippets/tools.json
This will introduce tools.json file for automatic completion function.
ONE-vscode-DCO-1.0-Signed-off-by: ysys <emoney96@naver.com>
=> Introduce tools.json

src/Project/BuilderCfgFile.ts
This will eable cfg import to add optimize and quantize jobs.
=> [Project] Enable cfg import optimize and quantize

package.json
This will add snippets for automatic completion function in cfg file.
ONE-vscode-DCO-1.0-Signed-off-by: Seojeonguk <uk7880@naver.com>
=> Add snippets for Automatic completion

src/Project/BuilderCfgFile.ts
This will notify adding jobs has finished.
=> [Project] Notify finish add

package.json, src/extension.ts
This will and command for visualization by barchart.
ONE-vscode-DCO-1.0-Signed-off-by: wnsdud4197 <wnsdud4197@naver.com>
=> Add command for visualization by barchart

package.json, src/extension.ts
this is initial commit for issue(#58)
configuration settings panel is for serving GUI environment to build ONE .cfg file
=>  Introduce oneConfigurationSettings

.gitignore
It includes the React stuff.
ONE-vscode-DCO-1.0-Signed-off-by: parkjisu6239 parkjisu6239@gmail.com
=> [Visualizer] Add content to .gitignore

package.json, src/Codelens/CodelensProvider.ts, src/extension.ts
This will provide codelens to the ini language.
ONE-vscode-DCO-1.0-Signed-off-by: Seojeonguk <uk7880@naver.com>
=> Introduce codelens

src/Config/GetNonce.ts
for security reason, if you use webview extension, then you have to use nonce function.
so this GetNonce.ts is it
=> [Config] Add GetNonce.ts

res/samples/cfg/inception_v3.cfg
This will revise sample inception_v3.cfg to import properly.
=> [res] Revise inception_v3.cfg

media/Config/reset.css, media/Config/vscode.css
these make webivew looks better and more comfortable
ONE-vscode-DCO-1.0-Signed-off-by: sunjin an asj12896@gmail.com
=> [Config] Add vscode.css and reset.css for configurationSettings webview

src/Config/ConfigPanel.ts
this panel is for configuration settings GUI, basic functions are included like kill, revive, createOrShow, dispose etc...
=> [Config] Add panel for configuration settings webview

media/Config/index.html
this html is base for Config Webview. later this html will be imported
=>  [Config] Add index.html for Config webview

media/Config/index.js
This will introduce index.js for Configuration-Setting GUI
ONE-vscode-DCO-1.0-Signed-off-by: sunjin an asj12896@gmail.com
=> [Config] Add objects of one-import options

package.json
This will add 'which' package to dev dependency.
=> Add 'which' to dev dependency

src/Config/ConfigPanel.ts
import html, css, js to webview
=> [Config] import html, css and js for webview

src/Project/BuilderCfgFile.ts, src/Project/JobPack.ts
This will enable Job for one-pack tool.
=> [Project] Enable Job for one-pack

src/Project/JobRunner.ts, src/Project/ToolRunner.ts
This will fix Job to run tool with correct real path of the tool.
=> [Project] Fix job tool path

package.json, src/extension.ts
Change command for a clear understanding of the visualization tool.
ONE-vscode-DCO-1.0-Signed-off-by: wnsdud4197 wnsdud4197@naver.com
=> [Visualizer] Change command for a clear understanding of the visualization tool.

media/Jsontracer/style.css
Apply the styles of all classes and tags used in Jsontracer.
=> [Jsontracer] Add style.css

media/Jsontracer/index.html
this html is base for Jsontracer webview. later this html will be imported
=> [Jsontracer] Add index.html for Jsontracer webview

media/Jsontracer/index.js
Add index.js, the root file among js for Jsontracer.
=> [Jsontracer] Add index.js

src/extension.ts
This will enable 'onevscode.configuration-settings' invoke 'ConfigPanel' to show configuration GUI.
=> [Config] register ConfigPanel in extension.ts

src/Project/BuilderCfgFile.ts, src/Project/Job.ts, src/Project/JobCodegen.ts
This will enable import and run job for codegen.
=> [Project] Enable job for codegen

package.json
This will provide a user setting variable.
=> [Editor]Add User Setting

src/Project/JobOptimize.ts, src/Project/JobQuantize.ts
This will remove unnecessary init for name which is already done in JobBase.
=> [Project] Remove unnecessary init for name

src/Project/Builder.ts, src/Project/BuilderCfgFile.ts, src/Project/JobBase.ts, src/Project/JobCodegen.ts, src/Project/JobImportTF.ts, src/Project/JobRunner.ts, src/Project/WorkFlow.ts
This will move member initialization to declaration.
=> [Project] Init members at declare

tsconfig.json
This will add attributes for import the json file in typescript.
ONE-vscode-DCO-1.0-Signed-off-by: ysys <emoney96@naver.com>
=> [Editor] Add attributes for import the json file in typescript.

src/extension.ts
This will enable 'onevscode.json-tracer' invoke 'Jsontracer' to show visualization.
=> [Jsontracer] register Jsontracer in extension.ts

media/Jsontracer/index.js, media/Jsontracer/processData.js
This file defines the behavior after the user clicks load button. Open the json file and preprocess it to visualize it.
=> [Jsontracer] Add a processData to open the json file data and process it.

package.json, src/extension.ts
This will toggle the user setting variable.
=> [Editor] Add command for Codelens

src/Editor/HoverProvider.ts, src/extension.ts
This will provide a hover to help explain the tool in ini language.
ONE-vscode-DCO-1.0-Signed-off-by: ysys <emoney96@naver.com>
=> [Editor] Introduce hover

media/Jsontracer/dashboard.js, media/Jsontracer/processData.js
This will render the ruler and the level.
=> [Jsontracer] Add dashboard to render bar-graph

package.json
This will be more effective in distinguishing it from other vcode-extensions commands.
=> Group commands into 'ONE' category

src/Editor/CodelensProvider.ts
This will initialize and return the codelens list.
=> [Editor] Initialize and Return the codelens list

src/Project/BuilderCfgFile.ts, src/Project/JobImportTF.ts
This will revise import-tf to support two remaining options.
=> [Project] Add two remaining options for import-tf

media/Config/vscode.css
This will update webview css width, color items for better presentation.
ONE-vscode-DCO-1.0-Signed-off-by: sunjin an asj12896@gmail.com
=> [Config] Update webview css

media/Jsontracer/category.js, media/Jsontracer/level.js
This will render each category. The category will contain several bars on the bar chart.
=> [Jsontracer] Add category to render bar-graph

src/Project/BuilderCfgFile.ts, src/Project/JobImportTFLite.ts
This will enable to import cfg with tflite model.
=> [Project] Enable import tflite

media/Jsontracer/dynamicGraduation.js, media/Jsontracer/index.js
This will render graduation. Graduation will work dynamically.
=> [Jsontracer] Add dynamic graduation

media/Jsontracer/bar.js, media/Jsontracer/category.js
This will displays json data with a bar and save the data in the DOM.
=> [Jsontracer] Add bar for render each bar

media/Jsontracer/ruler.js
This will render ruler to show timeline of bar-graph
=> [Jsontracer] Add ruler to render timeline of bar-graph

src/Editor/HoverProvider.ts
This will add initializing and returning the MarkdownString in hover.
=> [Editor] Add initializing and returning the MarkdownString in hover.

LICENSE
This commit adds BSD-3 Clause License.
=> Add BSD-3 Clause License

media/Config/sendToPanel.js
This will send data to Webview Panel.
=> [Config] Add sendToPanel.js

media/Jsontracer/bar.js, media/Jsontracer/detail.js
This will show you the details when you click on the bar. Mark detail differently when they are selected single or multiple.
=> [Jsontracer] Add detail to show bar's information.

src/Editor/CodelensProvider.ts
This will analyze the editor of the activated ini language by line if the user variable value is true.
=> [Editor] Parse an active editor

src/Config/Dialog/ImportConfigDialog.ts
This will add import Dialog for webview
ONE-vscode-DCO-1.0-Signed-off-by: sunjin an asj12896@gmail.com
=> [Config] Add import Dialog

media/Config/pathAutoComplete.js
this js add function for path auto complete
naming convention from template.cfg
=> [Config] Add autoComplete function for path

src/Editor/HoverProvider.ts
This will parse the text of the line where the mouse is raised in the editor of the activated ini language.
=> [Editor] Parse the text of the line where the mouse is raised

src/Editor/CodelensProvider.ts
This will find the scope of the tool name in which the codelens will be provided.
=> Find the scope of the tool name

src/Editor/HoverProvider.ts
This will change the name of the MarkdownString variable from mdfile to markdownString.
=> [Editor] Change the MarkdownString variable name.

media/Config/configValidator.js
mainly about input_path, output_path and backend.
this validator checks only for emptiness.
=> [Config] Add validation for required

media/Config/makeTags.js
makeTags.js is mainly for making html tags like input tag, button tag, select tag etc...
these functions will be used in buildDom.js
=> [Config] Add makeTags.js

src/Editor/HoverProvider.ts
This will show the name and description of the tool that matches the name in the json file.
=> [Editor] Add description of tools using Hover.

src/Circlereader/type/types.d.ts
Add semicolon to resolve formatchecker warning
ONE-vscode-DCO-1.0-Signed-off-by: Seunghyun Kang <code.57x53@gmail.com>
=> [Circletracer] Add a semicolon to the types file

package.json, src/Config/ConfigStatusBar.ts, src/extension.ts
This will add statusBar item to open webview easily
ONE-vscode-DCO-1.0-Signed-off-by: Sunjin-An asj12896@gmail.com
=> [Config] Add statusBar item

src/Editor/HoverProvider.ts
This will add a description of the options of the tool using the hover.
=> [Editor] Add a description of the options of the tool using the hover.

src/Config/Dialog/ExportConfigDialog.ts
This will write a '.cfg' file.
=> [Config] Add export dialog

src/Editor/HoverProvider.ts
This will add a description of the value of the option using the hover.
=> [Editor] Add a description of the value of the option using the hover.

src/Config/Dialog/InputFileDialog.ts
This will get input file path and send it to webview content.
=> [Config] Add input file dialog

src/Editor/CodelensProvider.ts
It will calculate the codelens range for the attribute.
=> [Editor]Calculate the range of codelenses for attribute

src/Circlereader/util/initSubgraphNodes.ts
This function takes and returns the name and type of each tensor.
ONE-vscode-DCO-1.0-Signed-off-by: Seunghyun Kang <code.57x53@gmail.com>
=> [Circletracer] Add a file that analyzes the tensor of the subgraph

src/Circlereader/Circlereader.ts
This file converts the information of the circle file required for visualization into JSON.
=> [Circletracer] Add a file that converts information of circle into JSON

src/Editor/CodelensProvider.ts
This will provide a codelens for the attribute.
=> [Editor] Provide a codelens for the attribute

media/Config/pathAutoComplete.js
fix error when there is no input_path in tool.
so i fix it through when it has no input_path, then just get empty string
=> [Config] fix error about input_path

media/Config/buildDom.js, media/Config/index.html, media/Config/vscode.css
buildDom.js is mainly for making DOM on webview extension.
there are funcions related with erasing DOM, building DOM.
and locaForSelect is ambiguous name so change it to SpanTagForSelect
=> [Config] Add buildDom.js

src/Editor/CodelensProvider.ts
This will manage attributes that will not be shown and generate events.
=> [Editor] Manage properties that will not be shown

media/Config/importConfig.js, media/Config/tools.js
This will update webview toggle error
before, if cfg file has tool options but choose to not use, it cause errors
ONE-vscode-DCO-1.0-Signed-off-by: Sunjin-An asj12896@gmail.com
=> [Config] Update importConfig.js

src/Editor/CodelensProvider.ts
This will generate an event to get the codelens again when the configuration is changed.
=> [Editor] Generate an event for codelens

media/Config/receiveFromPanel.js
This will receive data from Webview Panel.
=> [Config] Add receiveFromPanel.js

src/Editor/CodelensProvider.ts
This will change the position of the variable declaration.
`CurrentToolName` will continue to initialize when declaring to `resolveCodeLens`.
=> [Editor] Change the position of the variable declaration

media/Circletracer/style.css
Apply the styles of all classes and tags used in Circletracer.
ONE-vscode-DCO-1.0-Signed-off-by: Donggil Lee <donggillee94@gmail.com>
=> [Circletracer] Add style.css

media/Circletracer/makedata.js
This visualizes the details of the circle file.
=> [Circletracer] Add a js file to visualize details of circle file

res/samples/cfg/inception_v3_tflite.cfg, res/samples/cfg/readme.md, res/samples/cfg/test_onnx_model.cfg
This will introduce sample cfg files for tflite and onnx.
- also update readme file
=> [res] Add sample cfg for tflite and onnx

src/Project/BuilderCfgFile.ts, src/Project/JobImportONNX.ts
This will enable to import ONNX from cfg files.
=> [Project] Enable import ONNX

src/Editor/CodelensProvider.ts
This will filter out all hidden properties of the tool if you press the tool's codelens.
=> [Editor] Filter out hidden attributes

media/Circletracer/circleinfo.js, media/Circletracer/singleton.js
It saves json data initially by singleton pattern.
Also can access and modify json data by singleton pattern.
ONE-vscode-DCO-1.0-Signed-off-by: Donggil Lee <donggillee94@gmail.com>
=> [Circletracer] Add a file that save json by singleton pattern

media/Circletracer/utils.js
It is a common utils for circletracer.
=> [Circletracer] Add commonly used utils js files for circletracer

media/Circletracer/loadfile.js
This file allows you to load two JSON files that you want to compare.
Also, It shows the rate of change based on the duration on the imported JSON files.
ONE-vscode-DCO-1.0-Signed-off-by: Donggil Lee <donggillee94@gmail.com>
=> [Circletracer] Add a file to load two different JSONs

src/Snippets/README.md
This will add README document.
=> [Snippet] Add README document.

src/Editor/README.md
This will add README document.
=> [Editor] Add README document.

src/Config/README.md
This will add README document
ONE-vscode-DCO-1.0-Signed-off-by: Sunjin-An asj12896@gmail.com
=> [Config] Add README document

media/Config/tools.js
This commit adds `fuse_add_with_fully_connected` option to provide support of this optimization option in one-optimizer.
Draft PR: #276 
Signed-off-by: Alexander Moiseev <a.moiseev@samsung.com>
=> [Config] Add fuse_add_with_fully_connected option

infra/license/license-judgment.json, infra/license/package-judgment.json
This commit adds following blocklists
- `package-blocklist.json` : blocklist for packages in ONE-vscode. 1st priority.
- `license-blocklist.json` : blocklist for licenses in ONE-vscode. 2nd priority.
---
Parent Issue : #285 
Draft : #288
=> [infra] Add blocklist for license and package

infra/copyright/copyright-checker.ts
This commit adds copyright checker script.
---
Parent Issue : #298 
Draft : #302
=> [infra] Add Copyright checker script

media/Config/index.html, media/Config/reset.css, media/Config/vscode.css
This commit adds missing copyright statement.
---
Parent Issue : #298 
Draft : #302
=> [media/Config] Add missing copyright statement

infra/license/license-checker.ts
This commit adds license checker sciprt.
---
Parent Issue : #285 
Draft : #288
=> [infra] Add license checker script

.github/workflows/check-copyright.yml
This commit enables copyright checker in Github Action.
---
Parent Issue : #298 
Draft : #302
=> [CI] Enable copyright checker

media/Config/index.js
This commit fixes typo in the comment.
=> [media] Fix comment typo

src/Project/JobOptimize.ts
This commit fixes typo in optimize options.
=> [Project] Fix typo in optimize option

package-lock.json, package.json
To enable license checker in Github Action,
`license-checker` package is needed.
---
Parent Issue : #285 
Draft : #288
=> [infra] Add license-checker package

infra/license/check-result-formatter.ts
This commit adds formatter script for license verification result.
---
Parent Issue : #285
Draft : #288
=> [infra] Add License Verification Result Formatter script

.github/workflows/check-license.yml
This commit enables license checker in Github Action.
---
Parent Issue : #285 
Draft : #288 
**This PR is created in upstream to avoid Github authorization issue.**
=> [infra] Enable license checker

src/Project/JobCodegen.ts
Let's fix wrong JobCodegen type.
=> [Project] Fix wrong JobCodegen type

src/Project/JobImportBCQ.ts
Let's fix wrong toolname of JobImportBCQ.
=> [Project] Fix wrong toolname of JobImportBCQ

.github/workflows/publish-extension.yml, package-lock.json, package.json
This commit adds publish extension workflow.
This workflow builds vsix package and publish to vscode market place.
Signed-off-by: Jiyoung Yun <jy910.yun@samsung.com>
=> [CI] Add publish-extension workflow

package.json, src/extension.ts
This adds welcome content in our view, which asks end-user to do
some initial settings.
parent: #330 
ref: https://code.visualstudio.com/api/references/contribution-points#contributes.viewsWelcome
=> Add Welcome Content in View

.github/workflows/check-commit.yml
This commit enables Signed-off-by checker in Github Action.
---
Parent Issue : #299 
Draft : #308
=> [CI] Enable Signed-off-by checker

package.json, src/Views/FileTreeView.ts, src/Views/FileTreeViewActivator.ts, src/extension.ts
This adds UI to help user to enter model directory.
parent: #330 
=> Help User Enter Model Dir

src/Project/ToolArgs.ts
This reverts commit 33ecc5bf6c63d24f85244e9c91da78abc59d12e9.
=> Revert "[Project] Fix add() of ToolArgs if value is undefined"

.github/workflows/check-commit.yml
This commit enables no-body checker in Github Action.
---
Parent Issue : #123 
Draft : #308
=> [CI] Enable no-body checker in Github Action

.gitignore, .vscode/launch.json, .vscodeignore, package-lock.json, package.json, src/Tests/README.md, src/Tests/hooks.ts, src/Tests/index.ts, src/Tests/runTest.ts
This commit introduces unittest infra for extension test.
=> Introduce unittest infra for extension test

.github/workflows/check-copyright.yml, .github/workflows/check-license.yml, .github/workflows/check-pr-format.yml, .github/workflows/check-pr-tsc.yml
This commit changes github action trigger condition as following.
- license checker : When `package.json` is changed
- others : Remove 'push' event
=> [CI] Change Github Action trigger condition

.github/workflows/check-daily-license.yml
This commit enables license checker daily.
---
Draft : #358
=> [CI] Enable license checker daily

src/Tests/Project/Builder.test.ts
This commit adds unittest for Builder.
=> [Tests] Add unittest for Builder

src/Tests/Project/JobCodegen.test.ts, src/Tests/Project/JobImportBCQ.test.ts, src/Tests/Project/JobImportONNX.test.ts, src/Tests/Project/JobImportTF.test.ts, src/Tests/Project/JobImportTFLite.test.ts, src/Tests/Project/JobOptimize.test.ts, src/Tests/Project/JobPack.test.ts, src/Tests/Project/JobQuantize.test.ts
Let's add unittests for Jobs in Project.
=> [Tests] Add unittests for Jobs in Project

src/Tests/Project/Workflow.test.ts
This commit adds unittest for Workflow.
=> [Tests] Add unittest for Workflow

.github/workflows/check-pr-format.yml, infra/format
Resolves https://github.com/Samsung/ONE-vscode/issues/359
=> [CI] Format json

infra/license/license-checker.ts
This commit removes unused codes in license-checker.
---
Draft : #358
=> [infra] Remove unused codes in license-checker

src/Project/Job.ts, src/Project/JobCodegen.ts, src/Project/JobImport.ts, src/Project/JobImportBCQ.ts, src/Project/JobImportONNX.ts, src/Project/JobImportTF.ts, src/Project/JobImportTFLite.ts, src/Project/JobOptimize.ts, src/Project/JobPack.ts, src/Project/JobQuantize.ts, src/Project/JobRunner.ts, src/Project/ToolRunner.ts, src/Tests/Project/JobCodegen.test.ts, src/Tests/Project/JobImportBCQ.test.ts, src/Tests/Project/JobImportONNX.test.ts, src/Tests/Project/JobImportTF.test.ts, src/Tests/Project/JobImportTFLite.test.ts, src/Tests/Project/JobOptimize.test.ts, src/Tests/Project/JobPack.test.ts, src/Tests/Project/JobQuantize.test.ts
Let's use directly onecc instead of one-cmd to resolve #318.
=> Use directly onecc instead of one-cmd

package.json
Let's add npm run clean to remove output directory.
=> Add `npm run clean`

src/Tests/Project/ToolRunner.test.ts
Let's add unittest for ToolRunner.
=> [Tests] Add unittest for ToolRunner

src/Tests/Project/JobRunner.test.ts
Let's add unittest for JobRunner.
=> [Tests] Add unittest for JobRunner

package-lock.json, package.json
This commit resolves npm vulnerabilities.
Related: #427 
ONE-vscode-DCO-1.0-Signed-off-by: seongwoo <mhs4670go@naver.com>
=> Resolve npm vulnerabilities

src/Tests/indexCI.ts
Let's introduce indexCI for npm test on CI - github action.
=> [Tests] Introduce indexCI for npm test on CI

.github/workflows/check-pr-test.yml
Let's introduce check-pr-test.
=> [CI] Introduce check pr test

media/Compile/compile.css, media/Compile/compile.js, package-lock.json, package.json, src/Compile/CompilePanel.ts
This shows template 'Compile' screen. 'template' means that this screen
would be used as a basic for the future final 'Compile' screen.
For https://github.com/Samsung/ONE-vscode/issues/331
Draft https://github.com/Samsung/ONE-vscode/pull/297
=> Show template [Compile] screen

package.json
This commit adds compiler toolchain view on ONE view
=> [View/Compiler] Add Compiler Toolchain View

media/icon/dark/install.svg, media/icon/light/install.svg, package.json, src/extension.ts
This commit adds install button on Compiler Toolchain view.
It uploads install icon files.
=> [Compiler/View] Add install button

package.json
This commit adds executor view on ONE view container.
=> [Executor/View] Add Executor View

src/Backend/Version.ts, src/Tests/Backend/Version.test.ts
Let's introduce Version class.
=> [Backend] Introduce Version class

src/Backend/Command.ts, src/Tests/Backend/Command.test.ts
Let's introduce Command class.
=> [Backend] Introduce Command class

src/Backend/Backend.ts, src/Tests/Backend/Backend.test.ts, src/extension.ts
Let's move global backends to Backend/.
ONE-DCO-1.0-Signed-off-by: Yongseop Kim <yons.kim@samsung.com>>
=> [Backend] Move global backends to Backend/

package.json
This commit removes detail explorer view.
=> [UI] Remove detail explorer view

src/Backend/Executor.ts
Let's introduce Executor class.
=> [Backend] Introduce Executor class

src/Backend/Compiler.ts
Let's introduce Compiler class.
ONE-DCO-1.0-Signed-off-by: Yongseop Kim <<yons.kim@samsung.com>>
=> [Backend] Introduce Compiler class

src/Backend/API.ts
Let's introduce new API of Backend as commented yet.
ONE-DCO-1.0-Signed-off-by: Yongseop Kim <yons.kim@samsung.com>>
=> [Backend] Introduce new API of Backend

src/Project/Job.ts, src/Project/JobRunner.ts, src/Project/ToolRunner.ts, src/Tests/Project/ToolRunner.test.ts
Let's take Job as param by invoke().
=> [Project] Take Job as param by invoke()

src/Backend/Command.ts, src/Tests/Backend/Command.test.ts
This commit does hot-fix for Command class. The class didn't work
properly when it used `push`.
=> [Backend] Hot-fix for Command class

media/CfgEditor/cfgeditor.css, media/CfgEditor/cfgeditor.js, package-lock.json, package.json, src/CfgEditor/CfgEditorPanel.ts, src/extension.ts
This commit adds initial UI for ONE cfg file editor.
---
Parent Issue : #464 
Draft : #496
=> [cfg editor] Add initial UI for cfg editor

package.json
This commit renames 'Context Explorer' as 'Explorer'.
=> [UI] Rename Explorer View

src/Project/Job.ts, src/Project/JobRunner.ts
Let's Add callback to Invoke() of JobRunner.
=> [Project] Add callback to Invoke() of JobRunner

src/Backend/Toolchain.ts, src/Backend/ToolchainImpl/DebianToolchain.ts, src/Tests/Backend/ToolchainImpl/DebianToolchain.test.ts
Let's introduce Toolchain class.
=> [Backend] Introduce Toolchain class

src/Project/JobCommand.ts, src/Tests/Project/JobCommand.test.ts
Let's introduce JobCommand class.
=> [Project] Introduce JobCommand class

src/Backend/Executor.ts
Let's uncomment Executor and ExecutorBase classes.
=> [Backend] Uncomment Executor and ExecutorBase classes

src/Backend/Compiler.ts, src/Tests/Backend/Compiler.test.ts
Let's uncomment Compiler and CompilerBase classes with a test.
=> [Backend] Uncomment Compiler and CompilerBase

src/OneExplorer.ts, src/extension.ts
This commit implements One Explorer View.
Co-authored-by: Jiyoung Yun <jy910.yun@samsung.com>
----
From #495 #480
For #494
=> [UI] Implement One Explorer View 

src/Execute/ExecutorTfLite.ts
Let's introduce ExecutorTfLite class.
=> [Execute] Introduce ExecutorTfLite class

src/Project/Job.ts, src/Project/JobConfig.ts, src/Project/JobInstall.ts, src/Project/JobInstalled.ts, src/Project/JobUninstall.ts, src/Tests/Project/JobConfig.test.ts, src/Tests/Project/JobInstall.test.ts, src/Tests/Project/JobInstalled.test.ts, src/Tests/Project/JobUninstall.test.ts
This commit adds new Job classes - JobConfig, JobInstall, JobInstalled
and JobUninstall.
=> [Project] Add new Job classes

src/Backend/API.ts, src/Tests/Backend/Backend.test.ts
Let's introduce new API instead of old API.
=> [Backend] Introduce new API

infra/copyright/copyright-checker.ts
This will add netron folder to ingore list.
=> [infra] Ignore copyright checker for external

media/CfgEditor/cfgeditor.js, src/CfgEditor/CfgEditorPanel.ts
This commit renames some of variables for futher features.
---
Parent Issue : #498 
Draft : #496
=> [CfgEditor] Rename variables

media/CfgEditor/cfgeditor.js, src/CfgEditor/CfgEditorPanel.ts
This commit adds intermediate paths for each steps.
---
Parent Issue : #498 
Draft : #496
=> [CfgEditor] Add Intermediate Paths

package.json, src/OneExplorer.ts
This commit enables refresh command of OneExplorer.
---
(I tried to record git but it is not available on remote vscode environment 😭 )
From #530
=> [OneExplorer] Implement refresh command

media/CfgEditor/cfgeditor.js
New functions which can cover old separate functions are introduced.
As they are also better for reducing duplicated codes, this commit will replace them.
---
Parent Issue : #498 
Draft : #496
=> [CfgEditor] Replace separate functions to common functions

package.json, src/extension.ts
This commit will change view name and add some icon on this.
ONE-vscode-DCO-1.0-Signed-off-by: struss rrstrous@nate.com
=> [UI]Change Executor view title contents

src/Compile/CompileEnv.ts, src/Tests/Compile/CompileEnv.test.ts
This commit introduces CompileEnv class.
Original PR: #513
=> [Compile] Introduce CompileEnv class

media/CfgEditor/cfgeditor.js, src/CfgEditor/CfgEditorPanel.ts
Until now, text content is not displayed to GUI editor.
This commit will display text content as GUI.
---
Parent Issue : #498 
Draft : #496
=> [CfgEditor] Display text content to GUI

package.json
This commit will fix some mistypo on package.json
This will show add marker on target device view.
=> [UI] Fix mistypo on package.json

src/Utils/MultiStepInput.ts, src/View/InstallQuickInput.ts, src/extension.ts
This commit shows the install quick input.
It request to install toolchain selected by users.
=> [View] Add install quick input

media/CircleGraph/external/LICENSE, media/CircleGraph/external/ORIGIN, media/CircleGraph/external/base.js, media/CircleGraph/external/circle-metadata.json, media/CircleGraph/external/circle-schema.js, media/CircleGraph/external/circle.js, media/CircleGraph/external/dagre.js, media/CircleGraph/external/flatbuffers.js, media/CircleGraph/external/flexbuffers.js, media/CircleGraph/external/gzip.js, media/CircleGraph/external/index.html, media/CircleGraph/external/index.js, media/CircleGraph/external/json.js, media/CircleGraph/external/protobuf.js, media/CircleGraph/external/python.js, media/CircleGraph/external/tar.js, media/CircleGraph/external/text.js, media/CircleGraph/external/view-grapher.css, media/CircleGraph/external/view-grapher.js, media/CircleGraph/external/view-sidebar.css, media/CircleGraph/external/view-sidebar.js, media/CircleGraph/external/view.js, media/CircleGraph/external/xml.js, media/CircleGraph/external/zip.js
This will add netron source as-is into external.
=> [media/CircleGraph] Add netron source

src/OneExplorer.ts, src/extension.ts
This shows progress in notification when onecc is running by
clicking cfg file in OneExplorer view.
parent issue : https://github.com/Samsung/ONE-vscode/issues/524
=> Introduce OneccRunner class to show progress

package.json, src/CircleGraph/CircleGraph.ts
This will introduce empty CircleGraph to show model graph of circle model.
=> [CircleGraph] Introduce empty CircleGraph

src/extension.ts
This will register command for circle graph view and invoke show method.
=> [CircleGraph] Register command and show

src/CircleGraph/CircleGraph.ts
This will show OpenDialog for model to open if undefined and continue createOrShow.
=> [CircleGraph] Show open dialog and continue

src/CircleGraph/CircleGraph.ts
This will create empry CircleGraph penel.
=> [CircleGraph] Create empty panel

media/CircleGraph/.clang-format, media/CircleGraph/index.js
This will introduce index.js with format applied
- added '// eslint-disable-next-line' for variables don't follow camelCase
- changed '==' to '==='
- use tab size 4 to follow original source
=> [CircleGraph] Introduce formatted index.js

src/Execute/executeQuickInput.ts
This commit shows the log file path to the succesed notification.
=> [Execute] Print log file path to notification

src/CircleGraph/CircleGraph.ts
This will implement to handle dispose and introduce empty update to show
the content of the view.
=> [CircleGraph] dispose and update in ctor

media/CircleGraph/circle-metadata.json
This will introduce circle-metadata.json with format applied.
=> [CircleGraph] Introduce formatted circle-metadata.json

media/CircleGraph/index.html
This will introduce index.html with copyright for customized circle graph.
=> [CircleGraph] Introduce index.html

media/CircleGraph/index.js
This will tidy unnecessary codes in index.js
=> [CircleGraph] Tidy index.js

media/CircleGraph/index.html
This will tidy unneessary index.html icons.
=> [CircleGraph] Tidy index.html icons

src/CircleGraph/CircleGraph.ts
This will enable to load index.html to WebView.
- next changes will fix loading local resources.
=> [CircleGraph] Load index.html

src/CircleGraph/CircleGraph.ts
This will add retainContextWhenHidden option to prevent reloading models.
=> [CircleGraph] Enable retainContextWhenHidden

media/CircleGraph/view.js
This will revise view.js to support only circle format.
=> [CircleGraph] Revise view to support only circle

media/CircleGraph/index.html, src/CircleGraph/CircleGraph.ts
This will enable loading index.html with revised resource URIs.
=> [CircleGraph] Load html with modified resource URI

media/CircleGraph/index.js, src/CircleGraph/CircleGraph.ts
This will revise to show Ballon for alert from WebView.
=> [CircleGraph] Show Balloon for alert

media/CircleGraph/index.html
This will add 'Powered by netron' link at left bottom of the view.
=> [CircleGraph] Add 'Powered by netron'

media/CircleGraph/index.js
This will tidy unused menu items and related codes in index.js.
=> [CircleGraph] Tidy menu and related

media/CircleGraph/circle-metadata.json
This will add items and inputs/outputs attribute from tflite metadata.
=> [CirclrGraph] Add items and inputs/outputs from tflite

media/CircleGraph/index.js
This will revise require for javascript source used to process model files.
- we cannot use dynamic node changes in DOM cause of security
- circle.js and circle-schema.js are added in index.html as static
- this change will make callers to work as expected
=> [CircleGraph] Revise require

src/CircleGraph/CircleGraph.ts
This will use defines for constant string.
=> [CircleGraph] Use defines for string

media/CircleGraph/index.js, src/CircleGraph/CircleGraph.ts
This will enable to support request for local resource in view to ask extension.
- this is to support request of circle-metadata.json file
=> [CircleGraph] Support request for local resource

media/CircleGraph/view.js
This will remove clear selection with keydown to preserve selection state.
=> [CircleGraph] Remove clear selection with keydown

media/CircleGraph/view.js
This will revise to toggle selection with click instead of showing
properties window.
=> [CirclrGraph] Toggle selection with click

media/CircleGraph/index.js
This will tidy unused view methods.
=> [CircleGraph] Tidy unused view methods

src/CircleGraph/CircleGraph.ts
This will handle loadmodel message in extension to send model to WebView.
- this handles model size smaller than 10MB as single message.
=> [CircleGraph] loadmodel message in extension

src/Backend/Command.ts
This root boolean means that this command needs root permission.
=> [Backend] Add root boolean variable to Command class

src/Utils/MultiStepInput.ts
This commit will add password type on InputBox in MultiStepInput.
=> [UI] Add password type on InputBox

media/CircleGraph/index.js
This will enable to request load model from WebView to extension.
=> [CircleGraph] Request load model from WebView

media/CircleGraph/view.js, src/CircleGraph/CircleGraph.ts
This will revise not use var and use const or let.
=> [CircleGraph] Do not use var

media/CircleGraph/view.js
This will revise selection characterstics of find dialog
- will not clear when dialog opens
- scroll to node when clicked in find dialog
=> [CircleGraph] Revise selection for find dialog

src/CircleGraph/CircleGraph.ts
This will implement loadmodel for multi packet and error handling.
=> [CircleGraph] Handle loadmodel for multi packet and error

src/OneExplorer.ts
This commit auto-refresh OneExplorer when
any file with .cfg or modelfile extensions within workspace changes.
(Create/Delete/Change)
=> [OneExplorer] Implement AutoRefresh

media/CircleGraph/view.js
This will revise clearSelection to clear _selectionNodes array.
=> [CircleGraph] Revise clearSelection

media/CircleGraph/index.js
This will add menu item for clear selection.
=> [CircleGraph] Clear selection menu

src/OneExplorer.ts
This commit subscribes commands within OneExplorer
to let commands disposed when the extension is done.
For #643
=> [OneExplorer] Subscribe commands

src/Editor/CodelensProvider.ts, src/extension.ts
This commit Subscribes command inside CodelensProvider for ONE config.
It enables extension to dispose the commands when it is disabled.
=> [Editor] Subscribe commands

src/Project/Job.ts, src/Project/JobBase.ts, src/Project/JobCommand.ts, src/Project/JobRunner.ts, src/Project/ToolRunner.ts
This commit supports to run a job that requires root permission,
such as setting up the toolchain envrionment.
Draft pr: #599
=> Support to run root permission job

src/CircleGraph/CircleGraph.ts
This will tidy console.log for debugging that was not removed.
=> [CircleGraph] Tidy console log

src/View/InstallQuickInput.ts
This commit installs new toolchain
=> [Toolchain] Implement install toolchain

src/Project/ToolRunner.ts
This commit integrates two if-state in root request.
=> Integrate two if-statement in root request

src/OneExplorer.ts
This commit lets user choose a name of new configuration file
on 'create-cfg' command.
=> [OneExplorer] Ask config file name 

src/Toolchain/ToolchainEnv.ts, src/View/PasswordQuickInput.ts
This commit input user machine password using quick input
when there is a root request in command lists.
=> [Toolchain] Input password in case root request

src/Project/JobRunner.ts
This commit adds progress window while job is running.
=> Add progress window while job is running

src/Backend/Version.ts
This commit adds` Version.equals()` method.
This was required while working on a draft for #659.
=> Add Version.equals() method

src/Backend/Backend.ts, src/Tests/Project/Builder.test.ts, src/Tests/Project/JobRunner.test.ts, src/Tests/Project/ToolRunner.test.ts, src/Tests/Project/Workflow.test.ts, src/Tests/Toolchain/ToolchainEnv.test.ts, src/Utils/Logger.ts, src/extension.ts
This makes logger as a singleton.
This removes problem mentioned at https://github.com/Samsung/ONE-vscode/issues/662#issuecomment-1128638648.
For #662
=> Use singleton logger

src/Toolchain/ToolchainProvider.ts, src/extension.ts
This commit adds toolchain tree provider.
=> [Toolchain] Add toolchain tree provider

package.json, src/Toolchain/ToolchainProvider.ts, src/extension.ts
This commit adds uninstall toolchain command.
This icon locates to show actions for the toolchain item.
~Need #658~
=> [Toolchain] Add uninstall command

src/CircleGraph/CircleGraph.ts, src/CircleGraph/CircleGraphCtrl.ts
This will extract part of CircleGraphPanel to as CircleGraphCtrl to
provide common CircleGraph as a UI component.
- this change will extract getHtmlForWebview and related
=> [CircleGraph] Introduce CircleGraphCtrl

src/Utils/external/Nonce.ts
This will introduce Nonce file with getNonce method from external source.
=> [Utils] Introduce Nonce

src/Tests/Toolchain/ToolchainEnv.test.ts, src/Toolchain/ToolchainEnv.ts, src/Toolchain/ToolchainProvider.ts, src/View/InstallQuickInput.ts
This commit uses installed toolchain getter function.
=> [Toolchain] Use installed toolchain functions

src/Toolchain/ToolchainProvider.ts
This commit shows dependency information on tooltip.
=> [Toolchain] Show dependency information on tooltip

src/OneExplorer/ConfigObject.ts, src/Tests/OneExplorer/ConfigObject.test.ts
This commit introduces ConfigObject class which is composed of
parsed dictionary object of given ini file.
=> [OneExplorer] Introduce ConfigObject

src/Utils/Logger.ts
This introduces logger methods: `error()`, `warn()`, `info()`, `debug()` and `append()`.
related comment: https://github.com/Samsung/ONE-vscode/issues/662#issuecomment-1132448696
=> Revisit Logger

src/CircleGraph/CircleGraph.ts, src/CircleGraph/CircleGraphCtrl.ts
This will relocate message handler related codes to CircleGraphCtrl.
=> [CircleGraph] Relocate message handlers

src/Project/Job.ts, src/Project/JobCommand.ts, src/Toolchain/ToolchainEnv.ts
This commit adds success and failure callback to job request.
=> [Toolchain] Add success and failure callback to job request

src/Toolchain/ToolchainProvider.ts, src/View/InstallQuickInput.ts, src/extension.ts
This commit updates the toolchain view automatically when toolchain
is installed.
=> [Toolchain] Auto refresh toolchain view when toolchain is installed

src/OneExplorer/OneExplorer.ts
This commit removes unused functions.
=> [OneExplorer] Remove unused functions

src/OneExplorer/OneExplorer.ts
This commit improve the warning message on rename command.
----
From #723
=> [OneExplorer] Improve rename warning message

.htmlhintrc, media/CfgEditor/cfgeditor.css, media/CfgEditor/cfgeditor.html
This commit adds a new HTML file and css elements for new cfg editor UI.
---
- Parent Issue 
- #698 
- Draft
- #697
---
| UI | Before | After |
| :---: | :---: | :---: |
| Progress bar | ![image](https://user-images.githubusercontent.com/24720192/170421546-49027eb7-8455-40ff-9051-67dbd8e84772.png) | ![image](https://user-images.githubusercontent.com/24720192/170420256-ed0d8da3-c8d8-462a-9624-305abc1dafcd.png) |
| Import Step | ![image](https://user-images.githubusercontent.com/24720192/170493217-d8fe96e3-4d81-46b5-9835-a9d14961f576.png) | ![image](https://user-images.githubusercontent.com/24720192/170951693-92d04c5e-fa71-4b05-b3f3-744f1a111a7e.png) |
| Codegen Step | …
=> [CfgEditor] Introduce new cfg editor UI

package.json, src/OneExplorer/OneExplorer.ts
This commit adds open containing folder command.
=> [OneExplorer] Add OpenContainingFolder Command

media/PartEditor/index.css, media/PartEditor/index.html, media/PartEditor/index.js, package.json, src/PartEditor/PartEditor.ts, src/extension.ts
This will introduce initial PartEditor, to provide partition file editor.
=> [PartEditor] Introduce initial PartEditor

src/Utils/Helpers.ts, src/extension.ts
This commit changes `console.log` in extension.ts and Utils directory
to `Logger`.
for #662
=> Use Logger in extension.ts and Utils dir

src/OneExplorer/OneExplorer.ts, src/Toolchain/ToolchainEnv.ts, src/View/InstallQuickInput.ts
This replaces console.log to Logger among source files for views.
for #662
=> Use Logger for views

src/Circlereader/util/setAttributesByOption.ts, src/Editor/HoverProvider.ts, src/Execute/executeQuickInput.ts, src/Project/Builder.ts, src/Project/BuilderCfgFile.ts, src/Project/JobCodegen.ts, src/Project/JobImportBCQ.ts, src/Project/JobImportONNX.ts, src/Project/JobImportTFLite.ts, src/Project/ToolRunner.ts
This commit uses Logger for files in
src/{Projects,Circlereader,Editor,Execute} directories.
for https://github.com/Samsung/ONE-vscode/issues/662
=> Use Logger for src/{Projects,Circlereader,Editor,Execute}

src/OneExplorer/OneExplorer.ts
This commit
- uses validateInput
- uses value selection
- edit place holder
---
From #738
=> [OneExplorer] Improve Create Cfg UI

src/Project/Job.ts, src/Project/JobPrerequisites.ts, src/Toolchain/ToolchainEnv.ts, src/View/InstallQuickInput.ts
This commit adds refresh button and refresh the toolchain list by
updating apt source list.
=> [Toolchain] Refresh toolchain list

media/CfgEditor/displaycfg.js, media/CfgEditor/index.js, media/CfgEditor/updateContent.js, media/CfgEditor/updateUI.js
This commit adds events to HTML elements.
---
Draft : #697 
---
| Feature | Before | After |
| :---: | :---: | :---: |
| Sync Changes (Editor -> .cfg) | :x: NYI | ![import](https://user-images.githubusercontent.com/24720192/171584030-30757c7b-61bf-4613-812a-e961b0840d5b.gif) |
| Sync Changes (.cfg -> Editor) | :lady_beetle: `onecc` section was not supported<br> | :hammer_and_wrench: `onecc` section is now supported |
=> [CfgEditor] Add events to elements

media/PartEditor/index.html, media/PartEditor/index.js, src/PartEditor/PartEditor.ts
This will revise to fetch backend list items from extension.
=> [PartEditor] Revise backend list from extension

src/Tests/index.ts
This commit add comment to a test target glob
to make it easy to notice.
---
Let's support a test target list or something later.
=> [Unittest] Mark a test target glob

src/CfgEditor/CfgEditorPanel.ts
This commit adds message handlers to process messages from webview.
---
Draft: #697
=> [CfgEditor] Handling messages from webview

src/PartEditor/PartEditor.ts
This will prepare document file path members and set filename in UI.
=> [PartEditor] Prepare document file path members

package.json
This commit changes install button icon.
=> [Toolchain] Change install button icon

src/Toolchain/ToolchainEnv.ts, src/View/InstallQuickInput.ts
Prerequisite request is invoked to perform asynchronously very
frequently, so move it to ToolchainEnv class.
=> [Toolchain] Add prerequisites async function

media/PartEditor/index.js, src/PartEditor/PartEditor.ts
This will fill Operators listbox from operator names with
calling circle-operator tool.
=> [PartEditor] Fill Operators listbox

media/PartEditor/index.js
This will add comment of UI initialize sequence.
=> [PartEditor] Comment of UI init sequence

media/PartEditor/index.js, src/PartEditor/PartEditor.ts
This will apply backend code from the document to Operators listbox.
=> [PartEditor] Set backend code in Operators listbox

media/CfgEditor/cfgeditor.html, media/CfgEditor/displaycfg.js, media/CfgEditor/index.js, media/CfgEditor/one-optimizations.json, media/CfgEditor/updateContent.js
This commit adds HTML and static files for Optimize step.
---
Parent Issue : #751 
Draft : #697 
---
| Type | Item | Before | After |
| :---: | :---: | :---: | :---: |
| UI | Optimize Step | :x: NYI | ![optimize](https://user-images.githubusercontent.com/24720192/172993683-677690f3-49b5-454e-8912-31b89b8cdc2e.gif) |
=> [CfgEditor] Introduce Optimize step

media/PartEditor/index.js, src/PartEditor/PartEditor.ts
This will revise default backend array to give 'CPU' as initial value.
=> [PartEditor] Revise default backend array

media/PartEditor/index.js
This will set backend combobox change to reflect default checkbox.
=> [PartEditor] Handle Backend combobox change

media/PartEditor/index.js, src/PartEditor/PartEditor.ts
This will update GUI editor when document was changed outside like
from text editor.
=> [PartEditor] Update GUI for text edit changes

media/PartEditor/index.js
This will introduce two helpers to generate data for section.
=> [PartEditor] Two make section helpers

src/PartEditor/PartEditor.ts
This will introduce Partition class and makeDefaultPartiton method
for default 'partition' section.
=> [PartEditor] Introduce makeDefaultPartiton method

src/Project/JobRunner.ts, src/Project/ToolRunner.ts, src/Toolchain/ToolchainEnv.ts, src/View/InstallQuickInput.ts
Debian package allows to install only one package in one machine.
This commit removes package if the same package is already installed
through interaction with users.
=> [Toolchain] Uninstall package before installation

media/PartEditor/index.js, src/PartEditor/PartEditor.ts
This will handle default check button to set default backend
and update the document with changed default backend value.
=> [PartEditor] Handle default check with update document

media/CircleGraph/view.js
This will revise clearSelection method with separate _clearSelection
method for selection change notification.
=> [CircleGraphCtrl] Revise clearSelection method

media/CircleGraph/index.js, src/CircleGraph/CircleGraphCtrl.ts
This will add handler for model has finished loading model and graph is ready.
=> [CircleGraphCtrl] Introduce load finish handler

src/CircleGraph/CircleGraphCtrl.ts
This will revise member scope to protected.
=> [CircleGraphCtrl] Revise member scope to protected

src/CircleGraph/CircleGraph.ts, src/CircleGraph/CircleGraphCtrl.ts
This will revise initGraphCtrl to accept model path.
=> [CircleGraphCtrl] Revise initGraphCtrl to accept model path

media/PartEditor/index.js
This will enable 'Set' button to change backend of selection items in
the listbox to current backend of combobox.
=> [PartEditor] Enable Set button action

src/CircleGraph/CircleGraphCtrl.ts
This will introduce state to indentify ready from user.
=> [CircleGraphCtrl] Introduce state

src/CircleGraph/CircleGraph.ts, src/CircleGraph/CircleGraphCtrl.ts
This will revise scope of getWebviewOptions to be private and none static.
=> [CircleGraphCtrl] Revise scope for getWebviewOptions

media/PartEditor/index.js
This will enable 'Clear' button to change backend of selection items in
the listbox to default backend.
=> [PartEditor] Enable Clear button action

media/PartEditor/index.js, src/PartEditor/PartEditor.ts
This will enable to handle 'Set with graph view' button.
Actual switching to graph view is left todo.
=> [PartEditor] Handle Set with graph view button

src/CircleGraph/CircleGraph.ts, src/CircleGraph/CircleGraphCtrl.ts
This will introduce CircleGraphEvent interface so that owner of
CircleGraphCtrl can handle events(loading) of the ctrl.
=> [CircleGraphCtrl] Introduce CircleGraphEvent

media/CircleGraph/index.js, media/CircleGraph/view.js, src/CircleGraph/CircleGraphCtrl.ts, src/PartEditor/PartGraphSelector.ts
This will select nodes on graph view load from .part document file.
=> [PartEditor] Select nodes on graph view load

media/CircleGraph/index.js, media/CircleGraph/view.js, src/CircleGraph/CircleGraphCtrl.ts, src/PartEditor/PartGraphSelector.ts
This will enable notify selection change to owner.
=> [CircleGraphCtrl] Notify selection change

src/PartEditor/PartGraphSelector.ts
This will add more commands as
- close PartGraphSelector by command
- refresh selection state by command
=> [PartEditor] More commands for PartGraphSelector

src/PartEditor/PartEditor.ts, src/PartEditor/PartGraphSelector.ts
This will enable to update document from GraphSelector selection change.
=> [PartEditor] Update document from GraphSelector

src/CircleGraph/CircleGraphCtrl.ts
This will tidy unnecessary semicolon added at the end of function.
=> [CircleGraph] Tidy unnecessary semicolon

media/PartEditor/index.js, src/PartEditor/PartEditor.ts
This will revise to update PartGraphSelector graph view selection state
with Backend combobox item change.
=> [PartEditor] Update PartGraphSelector with Backend change

media/PartEditor/index.js, src/PartEditor/PartEditor.ts
This will tidy console log in PartEditor.
=> [PartEditor] Tidy console log

src/OneExplorer/OneExplorer.ts
Previously 'Cancel' button of progressive notification
while running onecc showed NYI error.
With this commit, 'Cancel' button actually terminates
onecc progress.
For https://github.com/Samsung/ONE-vscode/issues/715
draft #716
GIF images are in #716
=> Enable 'Cancel' button of progressive notification

media/CircleGraph/index.html, src/CircleGraph/CircleGraphCtrl.ts
This will introduce initial view mode global variable, to set
CircleGraph as viewer or node selector, as of now.
=> [CircleGraph] Introduce initial view mode

src/Execute/executeQuickInput.ts, src/Tests/index.ts, src/Tests/indexCI.ts, src/View/InstallQuickInput.ts
This commit fixes inconsistent `return` statements.
=> Fix inconsistent return statements

media/CircleGraph/index.js
This will introduce view mode in host object.
=> [CircleGraph] Introduce host view mode

media/CircleGraph/index.js, media/CircleGraph/view.js
This will apply condition for codes that should work for selector view mode.
=> [CircleGraph] Apply condition for selector view mode

media/CircleGraph/index.js, media/CircleGraph/view.js
This will revive features of viewer mode that was removed for
partition editor.
=> [CircleGraph] Revive features of viewer mode

src/Backend/ToolchainImpl/DebianToolchain.ts, src/Tests/Backend/ToolchainImpl/DebianToolchain.test.ts
This commit uses aptitude tool to remove debian package.
This tool removes all dependency packages at once.
Draft PR: #818
=> [Backend] Use aptitude tool to remove debian package

src/Toolchain/ToolchainEnv.ts, src/Toolchain/ToolchainProvider.ts, src/View/InstallQuickInput.ts
This commit uses Promise object to handle the function execution results.
Draft PR: https://github.com/Samsung/ONE-vscode/pull/818
=> [Toolchain] Modify to receive the function execution results

package.json, src/CircleGraph/CircleViewer.ts, src/extension.ts
This will introduce initial version of circle model viewer.
=> [CircleViewer] Initial version of circle viewer

src/CircleGraph/CircleViewer.ts
This will revise document to own view object.
=> [CircleViewer] Move view owner to document

src/CircleGraph/CircleViewer.ts
This will revise to enable multiple view can exist per document.
=> [CircleViewer] Enable Multiview per document

src/Toolchain/ToolchainProvider.ts, src/View/InstallQuickInput.ts
This commit combines the requests to the toolchain into ToolchainProvider.
=> [Toolchain] Combine the requests to the toolchain into ToolchainProvider

src/Backend/Version.ts
This commit supports cases where there is no minor or patch version.
=> [Backend] Support no minor or no patch version

package.json, src/extension.ts
This will remove old graph viewer with command palette.
=> [CircleGraph] Remove old graph viewer

media/CfgEditor/cfgeditor.css, media/CfgEditor/cfgeditor.html, media/CfgEditor/displaycfg.js, media/CfgEditor/index.js, media/CfgEditor/updateContent.js, media/CfgEditor/updateUI.js, src/CfgEditor/CfgEditorPanel.ts
This commit adds Quantize Step UI.
---
Parent Issue : #563
---
| Type | Item | Before | After |
| :---: | :---: | :---: | :---: |
| UI | Quantize Tab | :x: NYI | ![quantize](https://user-images.githubusercontent.com/24720192/175841643-38cbe42f-2cce-4edf-b4e9-7b75fffa8469.gif) |
=> [CfgEditor] Add Quantize Step UI

media/PartEditor/index.js
This will revise attribute code as becode to be more specific as backend code.
=> [PartEditor] Revise to use becode

src/CircleGraph/CircleGraphCtrl.ts
This will introduce disposed state for safety.
=> [CircleGraphCtrl] Introduce disposed state

media/CircleGraph/view-grapher.css, media/CircleGraph/view-grapher.js, media/CircleGraph/view-sidebar.css, media/CircleGraph/view-sidebar.js
This will add view-grapher and view-sidebar files from external for modification.
- fixed for format
- fixed for lint
=> [CircleGraph] View files for modification

package.json
This commit changes the title of toolchain commands and
hide uninstall command from commandn palette.
Related issue: #839
=> [Toolchain] Update toolchain commands

media/CircleGraph/index.js, src/CircleGraph/CircleGraphCtrl.ts
This will introduce method to handle system theme change.
=> [CirclrGraphCtrl] Enable system theme change

media/CircleGraph/view.js
This will enable to apply 'vscode-dark' type theme style from
vscodes predefined 'data-vscode-theme-kind' value.
=> [CircleGraphCtrl] Apply vscode-dark theme class

media/CircleGraph/index.html, media/CircleGraph/view-grapher.css, media/CircleGraph/view-sidebar.css
This will revise css to follow VSCodes dark theme vscode-dark instead of system dark theme.
=> [CircleGraphCtrl] Revise style to follow vscode

media/CircleGraph/index.js, media/CircleGraph/view.js, src/CircleGraph/CircleGraphCtrl.ts
This will enable to apply config theme dark-light change.
=> [CircleGraphCtrl] Apply config theme change

media/CircleGraph/view-grapher.css
This will change graph selection color to blue, from red, and
a little thicker as to follow default Windows selection color.
=> [CircleGraph] Change selection line style

src/OneExplorer/OneExplorer.ts
This log changes an info log to debug.
=> [OneExplorer] Change an info log to debug

src/OneExplorer/OneExplorer.ts, src/OneExplorer/OneccRunner.ts
This commit separates OneccRunner.ts from OneExplorer.ts.
=> [OneExplorer] Separate OneccRunner

src/PartEditor/PartEditor.ts
This will introduce PartEditor class to hold an instance for each document.
=> [PartEditor] Introduce PartEditor class

src/PartEditor/PartEditor.ts
This will revise PartEditorProvider to use PartEditor to hold for each document.
=> [PartEditor] Revise PartEditorProvider to use PartEditor

src/PartEditor/PartEditor.ts
This will tidy unused codes that moved to PartEditor class.
=> [PartEditor] Tidy unused codes

package-lock.json, package.json
This commit will update release version to 0.2.0.
=> Update Release version to 0.2.0

src/PartEditor/PartEditor.ts, src/PartEditor/PartGraphSelector.ts
This will revise to hold multiple PartGraphSelPanel with ID from
multiple PartEditor owners.
=> [PartEditor] Revise to hold multiple PartGraphSelPanel with ID

media/CircleGraph/view.js
This will add keyCtrl and keyShift members in view.View to utilize key
state of control and shift.
=> [CircleGraph] Add keyCtrl and keyShift

src/PartEditor/PartEditor.ts
This will add event handler for PartEditor to dispose request of itself.
=> [PartEditor] Event handler for dispose

media/CircleGraph/view.js
This will revise to use let instead of var.
=> [CircleGraph] Use let

media/PartEditor/index.html
This will revise position and button text of show graph view button.
=> [PartEditor] Revise show graph view button

src/PartEditor/PartEditor.ts
This will add some comments for message from web view.
=> [PartEditor] Comments for message from web view

media/CircleGraph/view.js
This will fix to remove double declare of host const.
=> [CircleGraph] Remove double host

media/PartEditor/index.js, src/PartEditor/PartEditor.ts
This will revise backend selection combobox change not to update backend.
=> [PartEditor] Revise backend combobox change

media/PartEditor/index.js, src/CircleGraph/CircleGraphCtrl.ts, src/PartEditor/PartEditor.ts, src/PartEditor/PartGraphSelector.ts
This will revise to show PartGraphSelector with same selection items
from Operators listbox when created.
=> [PartEditor] Revise PartGraphSelector with seleciton

media/PartEditor/index.js
This will revise backend combobox value string generation.
=> [PartEditor] Revise backend combobox

src/PartEditor/PartGraphSelector.ts
This will rename new graph selection panel to 'graphSelPanel' to be more
specific to its purpose.
=> [PartEditor] Rename object

src/PartEditor/PartGraphSelector.ts
This will revise panel title to show filename instead.
=> [PartEditor] Show filename as panel title

media/PartEditor/index.js, src/PartEditor/PartEditor.ts, src/PartEditor/PartGraphSelector.ts
This will enable to foward selection from PartEditor listbox to
PartGraphSelector graph nodes.
=> [PartEditor] Forward selection

media/CircleGraph/index.js
This will add graph node style for backend assignmments with
element generation as color is decided from backend extensions.
=> [CircleGraph] Add graph node style for backend assignments

media/PartEditor/index.js, src/PartEditor/PartEditor.ts
This will revise graph node selection to change operators listbox selection.
=> [PartEditor] Revise graph node selection

src/PartEditor/PartEditor.ts
This will tidy unused member _backEndForGraph.
=> [PartEditor] Tidy unused member

src/CircleGraph/CircleGraphCtrl.ts, src/PartEditor/PartGraphSelector.ts
This will enable document change to update graph view partition state.
=> [PartEditor] Send partition to Graph

media/CircleGraph/index.js, media/CircleGraph/view.js
This will apply partition of backend assignments for graph nodes.
=> [CircleGraph] Apply partition for graph nodes

package.json, src/OneExplorer/OneExplorer.ts
This commit adds delete command on every directory and files.
Its UI basically looks after vscode's default explorer.
It asks the user once more whether to delete.
---
For #906
=> [OneExplorer] Add delete command

src/PartEditor/PartGraphSelector.ts
This will set node backend assignment after load is finished.
=> [PartGraphSelector] Set node backend assignment after load

media/CircleGraph/view.js
This will exit forEach loop after item is found.
=> [CircleGraph] Exit forEach after found

media/CircleGraph/view.js
This will introduce '_scrollToSelected' flag member as scroll to selected
nodes when selection has changed.
=> [CircleGraph] Scroll to selected nodes with flag

media/CircleGraph/view.js
This will add view.Node ctor comment for input arguments.
=> [CircleGraph] Comment for view.Node ctor

src/CircleGraph/BackendColor.ts, src/PartEditor/PartEditor.ts, src/PartEditor/PartGraphSelector.ts
This will revise to send backend color information when open PartGraphSelector.
=> [PartEditor] Backend colors when open PartGraphSelector

media/CircleGraph/index.js, src/CircleGraph/CircleGraphCtrl.ts, src/PartEditor/PartGraphSelector.ts
This will introduce 'pageloaded' eventh when page is loaded.
=> [CircleGraphCtrl] Introduce pageloaded event

media/PartEditor/index.js, src/PartEditor/PartEditor.ts
This will revise resultBackends to send backend name and color in one object.
=> [PartEditor] Send backends with color as object

media/CircleGraph/index.js, src/CircleGraph/CircleGraphCtrl.ts, src/PartEditor/PartGraphSelector.ts
This will revise extension to send backend colors to web view.
=> [CircleGraph] Backend colors from extension

media/CircleGraph/index.js, media/CircleGraph/view.js
This will revise setNodeBackend method to use names from extension.
=> [CircleGraph] setNodeBackend with names from extension

media/PartEditor/index.css, media/PartEditor/index.html
This will add input element for find operators by name and code.
=> [PartEditor] input for find operators

media/CircleGraph/index.js
This will tidy unused _addStyleForBackend method.
=> [CirclrGraph] Tidy unused _addStyleForBackend

media/PartEditor/index.js
This will enable find operator with input text for name and opcode.
=> [PartEditor] Find operator with input

src/PartEditor/PartEditor.ts
This will tidy check of _document object as it's always valid object.
=> [PartEditor] Tidy check _document

src/PartEditor/PartEditor.ts, src/PartEditor/PartGraphSelector.ts
This will introduce types for commands to make command and function call simple.
=> [PartEditor] Introduce types for commands

src/PartEditor/PartEditor.ts, src/PartEditor/PartGraphSelector.ts
This will revise cmdOpen using PartGraphCmdOpenArgs type.
=> [PartEditor] Revise cmdOpen with PartGraphCmdOpenArgs

src/PartEditor/PartEditor.ts, src/PartEditor/PartGraphSelector.ts
This will revuse cmdUpdate and cmdFwdSelection with
PartGraphCmdUpdateArgs and PartGraphCmdFwdSelArgs types.
=> [PartEditor] Revise cmdUpdate and cmdFwdSelection

media/CircleGraph/index.js, media/PartEditor/index.js
This will disable to show web view default context menu with
cut/copy/paste.
=> [PartEditor/CircleGraph] Disable context menu

media/CircleGraph/index.js, media/CircleGraph/view.js
This will enable reload message to reload the model after it may have
changed.
=> [CircleGraph] Enable reload message

src/CircleGraph/CircleGraphCtrl.ts
This will introduce reloadModel method to invoke view to reload the model.
=> [CircleGraphCtrl] Introduce reloadModel

src/PartEditor/PartGraphSelector.ts
This will introduce cmdReload to reload the model.
=> [PartGraphSel] Introduce cmdReload

src/PartEditor/PartEditor.ts
This will enable to reload the model when changed from outside.
=> [PartEditor] Reload model when changed

media/CircleGraph/index.html
This will adjust menu position to show on bottom of button so that
button is not blocked.
=> [CircleGraphCtrl] Adjust menu position

src/Tests/View/PasswordQuickInput.test.ts, src/View/PasswordQuickInput.ts
This commit revisits PasswordQuickInput file.
=> [View] Revisit PasswordQuickInput file

src/OneExplorer/ConfigObject.ts
This commit refactors ConfigObj class by introducing Artifact and ArtifactLocator
=> [OneExplorer] Introduce ArtifactLocator

package.json, src/Execute/InferenceQuickInput.ts, src/Execute/InferenceRunner.ts, src/Execute/InferenceShowBox.ts, src/Execute/executeQuickInput.ts, src/Tests/Backend/Backend.test.ts, src/Tests/Execute/InferenceQuickInput.test.ts, src/Tests/Execute/InferenceRunner.test.ts
Let's revisit executeQuickInput file.
=> [Execute] Revisit executeQuickInput file

docs/Glossary.md, docs/HowToBuildFromSource.md, docs/HowToInstall.md, docs/HowToUse.md
Let's introduce HowTo and Glossary documents.
=> [docs] Introduce HowTo and Glossary documents

package.json, src/Toolchain/ToolchainProvider.ts, src/extension.ts
This commit adds set default toolchain command and icon.
Draft PR: #854
=> [Toolchain] Add set default toolchain command

src/Project/Builder.ts, src/Project/Job.ts, src/Project/JobBase.ts, src/Project/JobCommand.ts, src/Project/JobRunner.ts, src/Project/ToolRunner.ts, src/Project/WorkFlow.ts, src/Tests/Project/JobRunner.test.ts, src/Toolchain/ToolchainEnv.ts
This commit modifies the execution location of JobRunner to see the home
directory of os instead of seeing workspaceRoot.
Draft PR: #854 
**NOTE**
This modification helps each job run in a different location(cwd).
=> [Project] Introduce workDir in Job interface

src/OneExplorer/OneExplorer.ts
This commit cleans by removing unused lines
and elaborates comments about NodeType.
-----
From #1001
=> [OneExplorer] Clean and elaborate

src/OneExplorer/ConfigObject.ts
This commit refactors ConfigObject.parseBaseModel/DerivedModels
by adding register function and rewriting constructor.
---
From #1001
=> [OneExplorer] Refactor ConfigObject

src/Toolchain/ToolchainProvider.ts
This commit changes toolchain icon.
Draft PR: #854
=> [Toolchain] Change toolchain icon

src/Tests/View/InstallQuickInput.test.ts, src/Utils/MultiStepInput.ts, src/View/InstallQuickInput.ts
Let's revisit InstallQuickInput file.
=> [View] Revisit InstallQuickInput file

src/OneExplorer/ConfigObject.ts, src/Tests/OneExplorer/ConfigObject.test.ts
This commit shows .circle.log file under the cfg file.
=> [OneExplorer] Show .circle.log file

src/Tests/Utils/Helpers.test.ts, src/Utils/Helpers.ts
This commit rewrites RealPath's equal commands.
---
From #1011
=> [Utils] Revisit RealPath

src/CfgEditor/CfgData.ts, src/CfgEditor/CfgEditorPanel.ts, src/CfgEditor/CfgHtmlBuilder.ts, src/Tests/CfgEditor/CfgData.test.ts, src/Tests/CfgEditor/CfgHtmlBuilder.test.ts
Let's revisit CfgEditorPanel class.
=> [CfgEditor] Revisit CfgEditorPanel class

media/CfgEditor/one-optimizations.json, src/Project/BuilderCfgFile.ts, src/Project/JobOptimize.ts, src/Tests/Project/JobOptimize.test.ts
This will remove using --O1 option to follow ONE.
=> Deprecate --O1 option

media/CircleGraph/view.js
This commit removes no-effect return statement.
=> [CircleGraph] Remove no-effect return statement

docs/HowToUse.md, src/OneExplorer/OneExplorer.ts, src/Toolchain/DefaultToolchain.ts, src/Toolchain/ToolchainEnv.ts, src/Toolchain/ToolchainProvider.ts
This commit introduces DefaultToolchain class.
Draft PR: #854
=> [Toolchain] Introduce DefaultToolchain class

src/OneExplorer/ConfigObject.ts, src/OneExplorer/OneExplorer.ts
This commit refactors OneExplorer by using abstract class.
It redefines Node as an abstract class
and extends into each NodeType.
---
From #1039
=> [OneExplorer] Refactor with abstract class

src/Project/JobRunner.ts
This commit supports canceling JobConfig.
Depends on #854
=> [Toolchain] Support JobConfig cancellation

src/OneExplorer/OneExplorer.ts
This commit integrates same if-else statetment into one.
=> [OneExplorer] Integrate same if-else statement

.gitignore
This will update .gitignore to add generated files from coverage tools.
=> Update .gitignore for coverage test

src/OneExplorer/ConfigObject.ts
This commit fixes ConfigObj to check if ini field exists.
This commit also includes some trivial touches apon comments
----
From #1055
=> [OneExplorer] Fix parsing ConfigObj

.gitignore
This will update .gitignore to ignore test result file.
=> Update .gitignore for test result

src/CircleGraph/CircleGraphCtrl.ts
This will extract method handleChangeConfiguration for unit testing.
=> [CircleGraph] Extract handleChangeConfiguration

src/CircleGraph/CircleGraph.ts
This will revise createOrShow to return panel object for unit testing.
=> [CircleGraph] Revise createOrShow to return panel object

src/OneExplorer/ConfigObject.ts
This commit shows chrome trace files on OneExplorer.
---
From #1055
Waiting for #1058
=> [OneExplorer] Show chrome trace files 

src/OneExplorer/OneExplorer.ts
This commit fixes the bug making a duplicated root.
---
Resolves #1070
=> [OneExplorer] Fix bug of duplicated root

src/Backend/API.ts, src/Backend/Backend.ts, src/Execute/InferenceQuickInput.ts, src/Execute/InferenceRunner.ts, src/Tests/Backend/Backend.test.ts, src/Tests/Execute/InferenceQuickInput.test.ts, src/Tests/Execute/InferenceRunner.test.ts, src/extension.ts
This commit exchagnes the file names of
Backend/API.ts and Backend/Backend.ts
----
From #1049
=> [Backend] Exchange the file names: API, Backend

src/Tests/CircleGraph/CircleGraph.test.ts
This will introduce initial unit test for CircleGraphPanel class.
=> [CircleGraph/test] Initial test for CircleGraphPanel

src/OneExplorer/ArtifactLocator.ts
This commit adds assertions on ArtifactLocator class.
---
For #1064
=> [OneExplorer] Add assertions on ArtifactLocator

src/CfgEditor/CfgEditorPanel.ts
=> [CfgEditor] Exclude UI related codes from coverage analysis

src/Execute/InferenceShowBox.ts
=> [Execute] Exclude UI related codes from coverage analysis

src/Tests/Toolchain/JobConfig.test.ts, src/Tests/Toolchain/JobInstall.test.ts, src/Tests/Toolchain/JobUninstall.test.ts, src/Toolchain/JobConfig.ts, src/Toolchain/JobInstall.ts, src/Toolchain/JobPrerequisites.ts, src/Toolchain/JobUninstall.ts, src/Toolchain/ToolchainEnv.ts, src/Toolchain/ToolchainProvider.ts
Toolchain job files:
- JobInstall
- JobUninstall
- JobPrerequisites
- JobConfig
Related issue: #1080
=> [Toolchain] Move toolchain job files into Toolchain directory

src/CfgEditor/CfgHtmlBuilder.ts, src/Tests/CfgEditor/CfgData.test.ts, src/Tests/CfgEditor/CfgHtmlBuilder.test.ts
This commit refactors `CfgEditor` with following updates.
- Integrate trivial functions into one
- Integrate trivial positive testcases into one
- Add more testcases including negative tc.
=> [CfgEditor] Refactoriong for better tests

src/OneExplorer/ConfigObject.ts
This commit shows .tv2m, .tv2o, .tv2w files on ONE Explorer.
=> [OneExplorer] Show .tv2* files

src/Tests/OneExplorer/ConfigObject.test.ts
This commit adds more ConfigObject unit tests
---
From #1096
For #1051
=> [OneExplorer] Add ConfigObject unit tests

media/CfgEditor/cfgeditor.css, media/CfgEditor/cfgeditor.html, media/CfgEditor/index.js, src/CfgEditor/CfgEditorPanel.ts
This commit adds following events for codicon
- `codicon-search` : Open file dialog to select file or directory.
- `codicon-question` : Show help message when mouseover.
And this commit also removes some unnecessary codicons.
---
Draft : #1098 
---
=> [CfgEditor] Add codicon events

media/Jsontracer/bar.js, media/Jsontracer/calculateGraduation.js, media/Jsontracer/dashboard.js, media/Jsontracer/detail.js, media/Jsontracer/level.js
This commit fixes static analysus warnings in `media/Jsontracer`.
=> [Jsontracer] Fix static analysis warnings

package.json
This comit reorders context menus
---
For #1120
=> [OneExplorer] Reorder context menus

src/OneExplorer/ConfigObject.ts, src/Tests/OneExplorer/ConfigObject.test.ts
Let's show tracealloc.json files in OneExplorer.
----
/cc @hyunsik-yoon @ai-moiseev
=> [OneExplorer] Show tracealloc.json files

src/OneExplorer/ConfigObject.ts
This commit replaces some warning logs with debug logs
=> [OneExplorer] Change some warning logs

src/Toolchain/DefaultToolchain.ts
This commit shows default toolchain message once.
=> [Toolchain] Show default toolchain message once

src/Job/Job.ts, src/Job/JobCommand.ts, src/Job/JobRunner.ts, src/Toolchain/DefaultToolchain.ts, src/Toolchain/JobConfig.ts, src/Toolchain/JobInstall.ts, src/Toolchain/JobUninstall.ts, src/Toolchain/ToolchainProvider.ts
This commit changes the message contents.
=> [Toolchain] Update several information messages

src/OneExplorer/ConfigObject.ts
This commit opens *.circle files with circleViewer.
------
Moved from #937
=> [OneExplorer] Open *.circle files with circleViewer

src/Execute/DeviceViewProvider.ts
This commit will remove bug on DeviceView.
if some backend removed, associated executor is not displayed on DeviceView.
=> [DeviceView] Fix Device Executor display bug

.ahub/tcchecker-tca/config.yaml, src/Tests/Backend/Compiler.test.ts, src/Tests/Backend/Executor.test.ts, src/Tests/Backend/Toolchain.test.ts, src/Tests/Backend/ToolchainImpl/DebianToolchain.test.ts, src/Tests/CfgEditor/CfgData.test.ts, src/Tests/Execute/DeviceViewProvider.test.ts, src/Tests/OneExplorer/ConfigObject.test.ts, src/Tests/Toolchain/ToolchainProvider.test.ts, src/Tests/Utils/Helpers.test.ts
This commit initialize Test Case Administrator with fixing following things.
- Remove duplicated TC names even they are in the same suite
- Add missing assert
=> Initialize Test Case Administrator with fixing some TCs

src/extension.ts
=> Exclude UI related codes from coverage analysis

src/Execute/Device.ts, src/Tests/Execute/Device.test.ts
This commit will add NEG case for `Device` API.
=> [TEST] add NEG test case for Device

src/Tests/Job/Workflow.test.ts
this commit will add test `start()` on Workflow.
=> [TEST] Add Test on `Workflow.test.ts`

src/Tests/View/InstallQuickInput.test.ts, src/Tests/View/PasswordQuickInput.test.ts, src/View/InstallQuickInput.ts, src/View/PasswordQuickInput.ts
This commit revises unit tests in View with following things.
- Exclude UI related codes
- Rename negative testcases
- Integrate similar positive testcases
=> [View] Revise unit tests

src/Tests/index.ts
This commit adds `mocha-xunit-reporter` to generate xml file of coverage result.
=> [Tests] Add mocha reporter to generate xml file

src/CfgEditor/CfgEditorPanel.ts, src/extension.ts
This commit tidies registration of CfgEditorPanel.
---
- For #1167
=> [CfgEditor] Tidy registration

src/Execute/DeviceViewProvider.ts, src/Tests/Execute/DeviceViewProvider.test.ts
This commit will update getChildren test to cover more case.
=> [TEST] revisit DeviceViewProvider test

src/Tests/Utils/Helpers.test.ts, src/Utils/Helpers.ts
This commit improves line and function coverage by following things
- Remove unused function
- Add more testcases
=> [Utils] Improve line and function coverage

src/Tests/View/InstallQuickInput.test.ts, src/Tests/View/PasswordQuickInput.test.ts
This commit adds negative tests in `View` and break down a test
to multiple tests.
=> [View] Add negative tests and break down test

src/Toolchain/ToolchainProvider.ts, src/extension.ts
This commit tidies registration of toolchainProvider.
---
- For #1167
=> [Toolchain] Tidy registration

src/Execute/DeviceViewProvider.ts, src/extension.ts
This commit tidies registration of DeviewViewProvider.
----
- For #1167
=> [Device] Tidy registration

src/CircleGraph/CircleViewer.ts, src/extension.ts
This commit tidies registration of CircleViewerProvider.
=> [CircleViewer] Tidy registration

src/OneExplorer/OneExplorer.ts, src/extension.ts
This commit replaces initOneExplorer function with register function.
---
For #1167
=> [OneExplorer] Tidy registration

src/PartEditor/PartEditor.ts, src/PartEditor/PartGraphSelector.ts, src/extension.ts
This commit tidies registration of PartEditorProvider.
----
- For #1167
=> [PartEditor] Tidy registration

src/Tests/View/InstallQuickInput.test.ts, src/View/InstallQuickInput.ts
This commit adds InstallQuickInput test cases.
=> [View] Add InstallQuickInput test cases

src/Tests/Toolchain/DefaultToolchain.test.ts, src/Toolchain/DefaultToolchain.ts
This commit introduces new DefaultToolchain.test.ts file.
This file covers the DefaultToolchain test cases.
Draft PR: #1148
=> [Toolchain] Add DefaultToolchain test cases

src/Tests/Utils/Helpers.test.ts
This commit changes a test to negative test.
=> [Utils] Change test to negative test

src/Tests/MockCompiler.ts, src/Tests/Toolchain/ToolchainProvider.test.ts, src/Toolchain/ToolchainProvider.ts
This commit adds ToolchainProvider test cases.
- Add MockCompilerWithMultipleInstalledToolchains compiler
- Add MockCompilerWithNoInstalledToolchain compiler
Draft PR: #1148
=> [Toolchain] Add ToolchainProvider test cases

src/OneExplorer/ConfigObject.ts
This commit shows chrome trace files on ONE Explorer.
----
Need rebase after #1172
=> [OneExplorer] Show chrome trace files

src/Tests/Toolchain/ToolchainEnv.test.ts, src/Tests/View/InstallQuickInput.test.ts
This commit fixes following trivials.
- typos
- duplicated suite
=> [Tests] Fix trivial errors

src/OneExplorer/OneExplorer.ts, src/Tests/OneExplorer/OneExplorer.test.ts
This commit adds OneNode unit tests.
----
- For #1051
=> [OneExplorer] Add OneNode unit tests

script/sdbSpecList.sh, src/Execute/DeviceViewProvider.ts
This commit will add handling code for 'command not found' in DeviceList script.
=> [DeviceView] Fix `DeviceView` Error case for `command not found`

src/Tests/Utils/PipedSpawn.test.ts
This commit adds a negative test case.
=> [Tests/Utils] Add a negative TC

src/Toolchain/ToolchainProvider.ts
This commit updates the button title in default toolchain message.
=> [Toolchain] Update default toolchain message

src/Tests/View/InstallQuickInput.test.ts
This commit adds more test cases, especially for negative test cases.
=> [Tests/View] Add more test cases

src/Tests/Utils/Helpers.test.ts
This commit adds more test cases, especially for negative test cases.
=> [Tests/Utils] Add more test cases

infra/release/release_note.md
This commit adds release note for ONE-vscode v0.3.0
=> [Infra] Add Release Note for ONE-vscode v0.3.0

src/CfgEditor/CfgEditorPanel.ts
When multiple cfg editor are created, file content was not modified correctly.
It was because `CfgEditorPanel` is only created once,
while multiple panels try to modify cfg file content.
This commit will fix it by introducing `map` structure by using document URI as key.
=> [CfgEditor] Bugfix for multiple cfg editor panels are created

res/samples/traces/sample.timeline.json
This commit adds sample file for Jsontracer.
=> [res] Add sample file for Jsontracer

package-lock.json, package.json
This commit updates version to 0.3.0
=> Update Version to 0.3.0

src/OneExplorer/OneExplorer.ts
This commit uses extensionKind instead of remoteName
to know if the extension is remote or not.
----
For #1209
/cc @jyoungyun @hyunsik-yoon
=> [OneExplorer] Use extensionKind to know whether extensions' remote

src/OneExplorer/OneStorage.ts, src/Tests/OneExplorer/OneStorage.test.ts
This commit adds OneStorage unit tests.
-----
Waiting for the merge of #1227
=> [OneExplorer] Add OneStorage unit tests

src/OneExplorer/OneExplorer.ts
This commit subscribes filewatcher events to be disposed properly
=> [OneExplorer] Subscribe filewatcher events

.eslintrc.json, media/PartEditor/index.js, src/Backend/Command.ts, src/Backend/Compiler.ts, src/Backend/Executor.ts, src/Backend/Toolchain.ts, src/Backend/ToolchainImpl/DebianToolchain.ts, src/Backend/Version.ts, src/CfgEditor/CfgEditorPanel.ts, src/CircleGraph/CircleGraphCtrl.ts, src/CircleGraph/CircleViewer.ts, src/Jsontracer/JsonTracerViewerPanel.ts, src/OneExplorer/ArtifactLocator.ts, src/OneExplorer/ConfigObject.ts, src/OneExplorer/OneExplorer.ts, src/PartEditor/PartEditor.ts, src/PartEditor/PartGraphSelector.ts, src/Tests/OneExplorer/ConfigObject.test.ts, src/Tests/OneExplorer/OneExplorer.test.ts, src/Tests/OneExplorer/OneStorage.test.ts
This commit removes unnecessary semicolons.
---
For #1253
=> [lint] Remove unnecessary semicolons

package.json, src/CfgEditor/CfgEditorPanel.ts, src/OneExplorer/OneExplorer.ts
This commit reveals focused cfg file on CfgEditor in OneExplorer.
----
From #1246
=> [OneExplorer] Reveal focused cfg file in OneExplorer

src/Backend/Toolchain.ts, src/Toolchain/DefaultToolchain.ts, src/Toolchain/ToolchainEnv.ts
This commit removes unused variables and parameters from Toochain.
----
From #1261 
For #1253
=> [lint] Remove unused variables from Toolchain

src/CfgEditor/CfgEditorPanel.ts, src/Execute/DeviceViewProvider.ts, src/Job/ToolRunner.ts, src/Jsontracer/JsonTracerViewerPanel.ts, src/View/InstallQuickInput.ts
This commit removes unused variables or add underscores to those in need.
----
From #1261 
For #1253
=> [lint] Remove some unused variables

src/Backend/API.ts, src/Backend/ONE/ONEToolchain.ts, src/Tests/Backend/Backend.test.ts, src/Tests/Backend/ONE/ONEToolchain.test.ts, src/Tests/Toolchain/ToolchainProvider.test.ts, src/Tests/View/InstallQuickInput.test.ts
This commit introduces ONEToolchain when the extension is activated. 
This also includes test codes for ONEToolchain.
related issue : #1271, #1272 
related draft : #1283 
ONE-vscode-DCO-1.0-Signed-off-by: Yeonjeong Lee <yeonjeong.lee00@gmail.com>
=> [ONEToolchain] Introduce ONEToolchain

src/Tests/OneExplorer/OneExplorer.test.ts, src/Tests/TestBuilder.ts
This commit introduces 'TestBuilder', which is a helper class
to build a test file and directories during mocha test.
=> [Test] Introduce TestBuilder

script/prerequisitesForGetToolchains.sh, src/Backend/One/OneToolchain.ts, src/Tests/Backend/One/OneToolchain.test.ts
This commit implements compiler of ONEToolchain.
related issue: #1272  #1285
ONE-vscode-DCO-1.0-Signed-off-by: Nakhyun Kim <dss02094@gmail.com>
Co-authored-by: Yeonjeong Lee <yeonjeong.lee00@gmail.com>
Co-authored-by: Hyeryeong Jeong <jhr3681@naver.com>
=> [ONEToolchain] Implement compiler of ONEToolchain

media/CircleEditor/index.js, media/CircleEditor/view.js
This PR introduces preprocessing for editing circle file. It enables saving the data from open window view, adding data necessary for data modification, and adding vscode cmds and types of custom operator attributes.
ONE-vscode-DCO-1.0-Signed-off-by: Seonhyuk Ahn <gomduridkstjsgur@gmail.com>
---
Related issue : #1269
Draft : #1298
=> [CircleEditor] Preprocessing for Editing Circle Files

media/MetadataViewer/index.html, media/MetadataViewer/index.js, media/MetadataViewer/style.css, package.json, src/MetadataViewer/MetadataViewer.ts, src/MetadataViewer/MetadataViewerProvider.ts, src/MetadataViewer/example/MetadataExample.ts, src/OneExplorer/OneExplorer.ts, src/extension.ts
this commit adds Metadata Viewer
ONE-vscode-DCO-1.0-Signed-off-by: jihong-yu <jimdac@naver.com>
=> [MetadataViewer] Introduce Metadata Viewer

media/CircleEditor/type.js, media/CircleEditor/view-sidebar.css
This commit fix files for implementing GUI
type.js and view-sidebar.css, the main files of this pull request.
ONE-vscode-DCO-1.0-Signed-off-by: Gyeongmin Kwon <rudalsd@naver.com>
---
Related issue : #1269
Draft : #1298
=> [CircleEditor] Fix files for implementing GUI

media/CircleEditor/index.html
=> [CircleEditor] Add codicon

src/Tests/Utils/PipedSpawnSync.test.ts, src/Utils/PipedSpawnSync.ts
This commit adds PipedSpawnSync and PipedSpawnSyncStdout functions and test cases.
draft pr: #1329
=> [Utils] Add PipedSpawnSync and PipedSpawnSyncStdout functions

media/CircleEditor/view-sidebar.js
This PR adds class sidebar.EditAttributesView.
=> [CircleEditor] Add class sidebar.EditAttributesView

src/CircleEditor/CircleEditorDocument.ts, src/CircleEditor/CircleEditorProvider.ts
This commit adds Json editor feature.
- loadJson
- editJsonModel
- toJson function of BigInt type
ONE-vscode-DCO-1.0-Signed-off-by: Taeyoon Jeong <tanficial9574@gmail.com>
---
Related issue : #1269
=> [CircleEditor] Add Json editor feature

src/Tests/Utils/Hash.test.ts
This commit adds unit test for Hash.ts
---
Waiting for #1323, #1321
=> [Test] Add unit test for Hash.ts 

media/CircleEditor/view-sidebar.js
This PR adds CustomOp name edit function.
=> [CircleEditor] Add CustomOp name edit function

media/CircleEditor/view-sidebar.js
This PR adds input and output edit function.
It is possible to change tensor name, type and shape.
=> [CircleEditor] Add Input and Output Edit Function

src/CircleGraph/CircleGraphCtrl.ts
This will remove unused message command.
=> [CircleGraphCtrl] Remove unused message command

media/CircleGraph/index.html
This will introduce region for legend to show legend of quantization error (visquv).
=> [media/CircleGraph] Introduce region for legend

src/VisqProvider/VisqViewer.ts, src/extension.ts
This will intrododuce initial VisqProvider to show visq quantization error in graph view.
=> [visq] Introduce initial VisqProvider

src/CircleGraph/CircleGraphCtrl.ts, src/PartEditor/PartGraphSelector.ts
This will introduce CircleGraphEvent.onViewMessage method and revise to use this.
=> [CircleGraphCtrl] Introduce onViewMessage and revise

src/CircleGraph/CircleGraphCtrl.ts, src/PartEditor/PartGraphSelector.ts
This will tidy unused CircleGraphEvent handlers with CircleGraphCtrl and inhirt class PartGraphSelPanel.
=> [CircleGraphCtrl] Tidy unused with CircleGraphEvent

src/CircleGraph/CircleGraph.ts, src/CircleGraph/CircleGraphCtrl.ts, src/CircleGraph/CircleViewer.ts, src/PartEditor/PartGraphSelector.ts
This will relocate common loadContent method to CircleGraphCtrl class.
=> [CircleGraphCtrl] Relocate loadContent

media/CircleGraph/index.js, media/CircleGraph/view.js
This will introduce visq mode for CircleGraph to follow basic feature as default circle viewer.
=> [media/CircleGraph] Introduce visq mode

src/CircleGraph/CircleGraphCtrl.ts
This will add notes for received messages that was removed while refactoring.
=> [CircleGraphCtrl] Add notes for received messages

media/CircleGraph/index.js
This will comments explaining items of viewMode.
=> [media/CircleGraph] Comment for viewMode

src/VisqProvider/VisqViewer.ts
This will enable to load visq.json file to visualize quantization error.
=> [VisqProvider] Load visq.json

src/VisqProvider/VisqViewer.ts
This will revise to use path.join method.
=> [visq] Use path.join

media/CircleGraph/index.js
This will revise to start with visq command for visq viewMode.
=> [media/CirGr] Start with visq command

src/CircleGraph/CircleGraphCtrl.ts, src/VisqProvider/VisqViewer.ts
This will revise VisqViewer to implement CircleGraphEvent and handle visq message to load visq quantization error and model file.
=> [visq] Revise VisqViewer to handle visq message

media/CircleEditor/view-sidebar.js, media/CircleEditor/view.js
This PR adds buffer edit function.
- Compare modified data
- Update changed parts
- When type is changed, change whole data
=> [CircleEditor] Add Buffer Edit Function

media/CircleGraph/index.js
This will enable to handle visq message with empty detail methods.
=> [media/CircleGraph] Handle visq message

media/CircleEditor/view-sidebar.js
This PR classifies 'Edit Inputs and Outputs View'.
=> [CircleEditor] Classify EditInputsOutputsView

package.json
This will register *.visq.json to visq viewer.
=> Register visq viewer

media/CircleGraph/index.js
This will implement visq settings method to
- prepare style elements
- fill legend table
- store error nodes
=> [media/CircleGraph] Implement visq settings method

media/CircleGraph/index.js, media/CircleGraph/view.js
This will apply visq quantization error value in node and color value according to the error value.
=> [media/CircleGraph] Apply visq value and color

src/OneExplorer/OneExplorer.ts
This commit cleans up rename command.
It extracts 'askNewName' and 'validateNewPath' functions from rename command so that they can be used by other functions.
---
For #1359
=> [OneExplorer] Revisit rename command

media/MetadataViewer/index.js
This commit enables filtering properties in for-in loop by if statement.
---
This is to resolve static analysis warning, which is https://rules.sonarsource.com/javascript/RSPEC-1535.
Although diff is little bit complicated, only if statements are added.
=> [MetadataViewer] Filter properties in for-in loop

media/CircleGraph/index.js
This will introduce visqMetric to store metric of quantization error.
=> [media/CircleGraph] Introduce visqMetric

src/CircleGraph/CircleViewer.ts
This will enable to reload when view model has changed in filesystem.
=> [CircleViewer] Enable reload when changed

src/CircleGraph/CircleViewer.ts
This will add some comments about reload comment of delay.
=> [CircleViewer] Comment for reload delay

media/CircleGraph/view.js
This will revise to set visq attributes into node properties.
=> [media/CircleGraph] Set visq attributes into node

media/CircleGraph/view.js
This will tidy comment of old code.
=> [media/CircleGraph] Tidy comment

media/CircleGraph/view-sidebar.js, src/CircleGraph/CircleGraphCtrl.ts
This will copy view-sidebar.js from external for modification.
- changes applied are copyright comment and to follow format
=> [CircleGraph] Prepare view-sidebar.js

media/CircleGraph/index.js
This will revise dynamic visq style generation to follow existing partitioning style generation patterns.
=> [media/CircleGraph] Revise visq style

src/CircleGraph/CircleGraphCtrl.ts
This will add setModel method to set/update model path.
=> [CircleGraph] Add setModel

media/CircleGraph/index.js
This will add title for visquv styles to fast query.
=> [media/CircleGraph] Style title for visquv

media/CircleGraph/view-sidebar.js
This will add side bar property field for visq metric if available.
=> [media/CircleGraph] Add property field for visq metric

media/CircleGraph/view.js
This will apply Visquv styles in export.
=> [media/CircleGraph] Visquv export style

media/CircleGraph/index.js
This will revise blob export method to post message to vscode extension.
=> [media/CircleGraph] Revise blob export

src/OneExplorer/OneExplorer.ts
This commit makes `refactorCfgs` to return consistent type.
=> [OneExplorer] Return consistent return type

media/CircleGraph/index.js
This will add export to png/svg menu for visquv.
=> [media/CircleGraph] Add export menu for visquv

src/CircleGraph/CircleGraphCtrl.ts, src/Visquv/VisqViewer.ts
This will introduce export file method from webView request.
=> [Visquv] Introduce export file

src/OneExplorer/OneStorage.ts
This commit renames some functions and removes redundant member variable.
---
From #1402
=> [OneExplorer] Revisit OneStorage

src/Visquv/VisqViewer.ts
This will extract common method makeModelPath.
=> [visquv] Extract common method makeModelPath

src/OneExplorer/OneExplorer.ts, src/OneExplorer/OneStorage.ts
This commit supports multi-root workspaces.
---
For #1417
Waiting for #1424 to be merged
=> [OneExplorer] Support multi-root workspaces

src/OneExplorer/OneExplorer.ts
This commit optimizes hide&show command.
Previously, it reset all the internal data, the node tree and node map, and built them from scratch.
Now, it keeps all the internal data and only changes the getChildren() function's behavior.
Note that TreeView does build the tree by:
(1) getting children nodes from getChildren() and
(2) mapping the nodes to OneNode(Tree Item) using getTreeItem() Therefore, to decide whether to display node or not, getChildren() should make decision.
ONE-vscode-DCO-1.0-Signed-off-by: Dayoung.lee <dayoung.lee@samsung.com>
=> [OneExplorer] Optimize Hide&Show

src/OneExplorer/OneExplorer.ts
This commit uses vscode.WorkspaceEdit instead of vscode.workspace.fs.
WHY?
VSCODE's WorkspaceEdit supports ordered multiple workspace changes. It is listened by vscode.worskpace.onDid* event listeners, which are more usable then filesystem watcher.
---
For #1436
=> [OneExplorer] Use vscode.WorkspaceEdit

src/Tests/OneExplorer/ConfigObject.test.ts, src/Tests/OneExplorer/OneStorage.test.ts
Let's use TestBuilder utility in ConfigObject.test.ts and OneStorage.test.ts.
=> [Test] Use TestBuilder

src/Tests/OneExplorer/OneStorage.test.ts
This commit rearrange test suites of OneStorage.
before introducing more classes and its tests to OneStorage class.
=> [OneStorage/test] Rearrange suites

src/OneExplorer/OneStorage.ts
Instead of using undefined, let's use default value.
=> [One Explorer] Set default value for delete function

src/Toolchain/DefaultToolchain.ts, src/Toolchain/ToolchainProvider.ts
This commit removes default toolchain info message. This feature is not stable, showing toolchain message confuses user even more.
=> [Toolchain] Remove default toolchain info message.

infra/release/release_note.md, package-lock.json, package.json
This commit prepares for ONE-vscode to v0.4.0.
- Update release note for v0.4.0
- Update package version number
=> Prepare for updating ONE-vscode to v0.4.0

src/Tests/OneExplorer/OneExplorer.test.ts, src/Tests/OneExplorer/OneStorage.test.ts
This commit fixes a unit test which is wrongly defined.
=> [OneExplorer] Fix a unit test

media/CircleGraph/view.js
This will let prettier ignore previous code of view.js without formatting for better readability.
=> [CircleGraph] Use prettier ignore view.js

media/CircleGraph/index.html, media/CircleGraph/view-sidebar.css, media/CircleGraph/view-sidebar.js
This commit adds tensor visualization property for sidebar.
ONE-vscode-DCO-1.0-Signed-off-by: Stanislav Ponkrashov <s.ponkrashov@samsung.com>
=> [CircleGraph] Add Visual Tensor View

src/CircleGraph/CircleGraphCtrl.ts, src/CircleGraph/CircleViewer.ts
This commit enables visual tensor view in Circle Graph.
ONE-vscode-DCO-1.0-Signed-off-by: Stanislav Ponkrashov <s.ponkrashov@samsung.com>
=> [CircleGraph] Enable Visual Tensor View

src/MPQEditor/MPQData.ts, src/Tests/MPQEditor/MPQData.test.ts
This commit adds MPQData to MPQEditor.
Draft: https://github.com/Samsung/ONE-vscode/pull/1505
=> [MPQEditor] Add MPQData to MPQEditor 

src/OneExplorer/OneExplorer.ts
This commit tidies delete function.
=> [OneExplorer] Tidy delete

src/OneExplorer/OneExplorer.ts
This commit tidies getTreeItem function with switch-case statement.
=> [OneExplorer] Tidy getTreeItem

media/MPQEditor/index.js
This commit introduces 'requestDisplayMPQ' message.
Fresh draft: #1511
=> [MPQEditor] Introduce 'requestDisplayMPQ' message

src/MPQEditor/MPQEditor.ts
This commit introduces MPQEditor for manual mixed precision quantization task.
=> [MPQEditor] Introduce MPQEditor

src/MPQEditor/MPQEditor.ts
This commit implements webviewPanel initialization and update.
Its correctness is tested in #1511.
=> [MPQEditor] Implement webviewPanel init.

src/extension.ts
This commit registers MPQEditor for manual mixed precision quantization task.
Its correctness is tested in https://github.com/Samsung/ONE-vscode/pull/1511.
=> [MPQEditor] Register MPQEditor

src/MPQEditor/MPQData.ts, src/Tests/MPQEditor/MPQData.test.ts
This commit revisits 'MPQData' for the ability to update specific layers.
=> [MPQEditor] Revisit 'MPQData'

src/extension.ts
This commit registers MPQSelectionPanel for manual mixed precision quantization task.
=> [MPQEditor] Register MPQSelectionPanel

src/Backend/Compiler.ts, src/Backend/Executor.ts, src/Backend/One/OneToolchain.ts, src/Backend/Toolchain.ts, src/Backend/ToolchainImpl/DebianToolchain.ts, src/Tests/Backend/Compiler.test.ts, src/Tests/Backend/Executor.test.ts, src/Tests/Backend/Toolchain.test.ts, src/Tests/Backend/ToolchainImpl/DebianToolchain.test.ts, src/Toolchain/ToolchainEnv.ts, src/Toolchain/ToolchainProvider.ts
This commit updates Backend codes for support model related functions.
=> Update Backend codes for supporting model related functions

.ahub/sam/exclude.txt
This will revise sam exclude list to exclude CircleGraph and CircleEditor.
=> [ahub/sam] Revise exclude list

src/Toolchain/ToolchainProvider.ts
This commit uses checkAvailableToolchain in _run() function.
Related draft: #1570
=> [Toolchain] Use checkAvailableToolchian in _run() function

src/Job/JobCommand.ts
This commit adds result optional variable to JobCommand.
Related PR: #1568
=> Add result variable to JobCommand

src/Tests/Toolchain/ToolchainEnv.test.ts, src/Toolchain/ToolchainEnv.ts
This commit implements inference function in ToolchainEnv.
=> [Toolchain] Implement inference function in ToolchainEnv

src/Tests/Toolchain/ToolchainEnv.test.ts, src/Toolchain/ToolchainEnv.ts
This commit implements profile function in ToolchainEnv.
=> [Toolchain] Implement profile in ToolchainEnv

package.json, src/Tests/Toolchain/ToolchainProvider.test.ts, src/Toolchain/ToolchainProvider.ts
This commit implements profile function in ToolchainProvider. This function calls the profile function of ToolchainEnv. It also adds vscode command for profile.
=> [Toolchain] Implement profile in ToolchianProvider

src/View/InstallQuickInput.ts
This commit shows error messages that occurs during requesting prerequisite().
=> [Toolchain] Show prerequisites error messages

src/OneExplorer/OneStorage.ts
This commit fixes typo in comment.
=> [OneExplorer] Fix typo in comment

package.json, src/OneExplorer/OneExplorer.ts
This commit adds delete shortcut.
=> [OneExplorer] Add delete shortcut

src/Toolchain/ToolchainProvider.ts
This commit uses option in ProfileModel command.
Draft PR: #1584
=> [Toolchain] Use option in ProfileModel command

package.json, src/OneExplorer/OneExplorer.ts
This commit introduces infer function to product file.
Draft PR: #1584
=> [OneExplorer] Introduce infer function to product file

package.json, src/OneExplorer/OneExplorer.ts
This commit introduces profile function to product file.
Draft PR: #1584
=> [OneExplorer] Introduce profile functon to product file

src/Tests/Backend/Compiler.test.ts, src/Tests/Backend/Executor.test.ts, src/Tests/Backend/Toolchain.test.ts
This commit fixes 4 major defects in modules in Backend directory. It fixes by refering unused objects.
---
For #1580
=> Fix CQM Major defects in Backend

package.json
This commit formats package.json
=> Align package.json

README.md
Co-authored-by: Dayoung Lee <dayoung.lee@samsung.com>
ONE-vscode-DCO-1.0-Signed-off-by: taorye <taorye@outlook.com>
=> docs: correct compile and model typo, etc

src/Backend/API.ts
This commit sets vscode context of enabled backend.
=> [API] Set context of backend enabled

.ahub/sam/exclude.txt
This commit excludes test code from SAM analysis.
=> [ahub/sam] Exclude test code

package.json
This commit updates toolchain referesh/install/uninstall commands title to "Verb + Object", like other commands.
ONE-vscode-DCO-1.0-Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>
=> [Toolchain] Update command title

src/Tests/OneExplorer/ConfigObject.test.ts
This commit is to relieve function complextiy in test.
=> [OneExplorer] Relieve function complexity

src/OneExplorer/ConfigObject.ts
This commit opens product files with default editor in One Explorer
=> [OneExplorer] Open files with default editor

package.json, src/MPQEditor/MPQEditor.ts
This commit adds the 'create mpq configuration menu' from OneExplorer.
=> [MPQEditor] Add create menu from OneExplorer

media/CircleGraph/external/circle-schema.js
This PR will update circle-schema to version 0.6.
The `circle-schema.js` file is originally come from [netron](https://github.com/lutzroeder/netron/blob/89104391b1f2dfea9738d064339069ad1db3bd34/source/circle-schema.js).
ONE-vscode-DCO-1.0-Signed-off-by: Seungho Henry Park <shs.park@samsung.com>
---
Related: #1651
=> [CircleGraph] Update Circle Schema

media/CircleGraph/external/circle-schema.js, media/CircleGraph/external/tflite-metadata.json, media/CircleGraph/external/tflite-schema.js, media/CircleGraph/external/tflite.js, media/CircleGraph/index.html, media/CircleGraph/index.js, media/CircleGraph/view.js, package.json, src/CircleGraph/CircleGraphCtrl.ts
Now, CircleGraph can show tflite.
It also updates circle-schema. It shows more operators like `GELU`.
ONE-vscode-DCO-1.0-Signed-off-by: Sanggyu Lee <sg5.lee@samsung.com>
=> [CircleGraph] Support tflite

src/Toolchain/ToolchainEnv.ts, src/View/PasswordQuickInput.ts
This commit adds password requirement description by using InputBoxOptions' placeHolder field.
ONE-vscode-DCO-1.0-Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>
=> [Toolchain] Add description for password requirement

src/Toolchain/ToolchainProvider.ts
This commit updates toolchain icon.
When the toolchain is a default toolchain, it changes the icon color to green.
=> [Toolchain] Update toolchain icon

src/Toolchain/DefaultToolchain.ts, src/Toolchain/ToolchainProvider.ts
This commit refreshes device view whenever default toolchain is changed.
=> [Toolchain] Refresh device view when default toolchain is changed

src/Execute/Device.ts, src/Tests/Execute/Device.test.ts
This commit introduces SimulatorDevice and TargetDevice.
=> [Execute] Introduce SimulatorDevice and TargetDevice

src/Execute/DeviceViewProvider.ts, src/Tests/Execute/DeviceViewProvider.test.ts
This commit introduces DeviceViewNode by device type.
=> [Execute] Introduce DeviceViewNode by device type

src/Execute/DeviceViewProvider.ts
This commit updates default executor icon.
~~waiting for #1661~~
=> [Execute] Update default executor icon 

src/Tests/Backend/One/OneToolchain.test.ts
This commit adds OneToolchain test cases.
=> [OneToolchain] Add one toolchain test cases

src/OneExplorer/OneExplorer.ts, src/OneExplorer/OneStorage.ts, src/Tests/OneExplorer/OneExplorer.test.ts, src/Tests/OneExplorer/OneStorage.test.ts
This commit Implements Explorer for EdgeTpu Backend
- Implements Explorer for EdgeTpu Backend
- Add Explorer Test code for EdgeTPU Backend
Co-author: Seongwon Im <imsw0529@gmail.com>
ONE-vscode-DCO-1.0-Signed-off-by: SeungHyunH <vkflek1232@naver.com>
=> [EdgeTpu] Implements Explorer for EdgeTpu Backend

infra/release/release_note.md, package-lock.json, package.json
This commit updates ONE-vscode version to v0.5.0.
It also updates release note for v0.5.0.
=> [Infra] Update ONE-vscode version to v0.5.0

src/OneExplorer/OneStorage.ts
This commit separates init() from constructors.
---
From #1702
=> [OneStorage] Revisit constructors

src/Backend/CompilerImpl/DebianCompiler.ts, src/Backend/EdgeTPU/EdgeTPUToolchain.ts, src/Backend/One/OneToolchain.ts, src/Tests/Backend/EdgeTPU/EdgeTPUToolchain.test.ts
Implemented the EdgeTPUCompiler for EdgeTPUToolchain
Implemented code to test the EdgeTPUCompiler
- constructor
- getToolchainTypes
- parseVersion
- getToolchains
- getInstalledToolchains
- prerequisitesForGetToolchains
=> [EdgeTPU] Add EdgeTPUCompiler

src/OneExplorer/OneExplorer.ts, src/OneExplorer/OneStorage.ts
This commit enhances node map to have multiple nodes.
---
For #1703
=> [OneExplorer] Enhance node map

src/Tests/MPQEditor/MPQEditor.test.ts, src/Tests/Utils/Hash.test.ts, src/Utils/Hash.ts
This commit fixes async tests and adds a related exception throwing.
---
For #1706
=> [Test] Fix async test

src/MPQEditor/MPQEditor.ts
This commit completes async condition of createDefaultMPQ by waiting for document.save().
---
Expecting to resolve #1706
=> [MPQEditor] Fix createDefaultMPQ

src/Backend/API.ts, src/Tests/Backend/Backend.test.ts, src/Tests/Toolchain/ToolchainProvider.test.ts, src/Tests/View/InstallQuickInput.test.ts, src/extension.ts
This commit adds EdgeTPUToolchain in extension.ts using API.registerBackend() and updates the testing codes.
ONE-vscode-DCO-1.0-Signed-off-by: Bumsoo Ko <rhqjatn2398@naver.com>
=> [EdgeTPU] Add EdgeTPU backend registration codes

.github/workflows/check-pr-test.yml
This commit allows check PR test on all branches.
=> [workflows] Allow to check pr test on all branches

src/Backend/API.ts, src/OneExplorer/OneExplorer.ts, src/extension.ts
This commit binds edgetpu creation feature to EdgeTPU Backend functionally.
=> [EdgeTPU] Bind CFG creation to backend

src/OneExplorer/OneExplorer.ts, src/OneExplorer/OneStorage.ts
This commit shows edgetpucfg node only if EdgeTPU Backend is registered.
=> [EdgeTPU] Bind EdgeTPUCfg Node to the backend's registration

src/CfgEditor/CfgData.ts, src/CfgEditor/EdgeTPUCfgData.ts, src/CfgEditor/ICfgData.ts, src/CfgEditor/Sections.ts, src/Tests/CfgEditor/EdgeTPUCfgData.test.ts
This commit is about implementing EdgeTPUCfgData using the ICfgData interface.
ONE-vscode-DCO-1.0-Signed-off-by: Hyeon-Uk <rlagusdnr120@gmail.com>
---
Original PR #1673
=> [EdgeTPU] Implement EdgeTPUCfgData using the ICfgData interface

src/OneExplorer/ConfigSettings/EdgeTpuConfigSetting.ts
Let's open edgetpu file with circle viewer.
=> [EdgeTPU] Open edgetpu file with circle viewer

src/Backend/EdgeTPU/EdgeTPUToolchain.ts, src/Tests/Backend/EdgeTPU/EdgeTPUToolchain.test.ts
This commit adds EdgeTPUToolchain.
ONE-vscode-DCO-1.0-Signed-off-by: Bumsoo Ko <rhqjatn2398@naver.com>
=> [EdgeTPU] Add EdgeTPUToolchain 
