.eslintrc.json

This will introduce initial .eslintrc.json file that is used for eslint.

Introduce initial eslintrc.json file

---

.github/workflows/check-pr-format.yml

This will enable TypeScript format checker with clang.

Enable ts format checker with clang

---

.github/workflows/check-pr-format.yml

This will enable to upload format.patch to Artifacts for failed checks.

Enable upload format.patch if failed

---

src/Project/Builder.ts
src/Utils/Helpers.ts

This will initialize Builder current workspace folder with
introducing obtainWorkspaceRoot method in Helpers in Utils.

Initialize Builder current workspace

---

src/Project/ToolArgs.ts

This will introduce ToolArgs alias of Array<string> used as arguments
when executing commands.

Introduce ToolArgs

---

src/Project/Builder.ts
src/Project/JobImport.ts
src/Project/JobImportTF.ts

This will introduce JobImportTF and JobImprt for base class of import jobs.
NE-vscode-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

Introduce JobImportTF

---

src/Utils/Helpers.ts

This will introduce getImportCfgFilepath in utils to get import cfg file
path from the user.

Introduce utils.getImportCfgFilepath method

---

src/Project/Builder.ts
src/Project/BuilderCfgFile.ts

This will introduce BuilderCfgFile to import cfg files to WorkFlow.

Introduce BuilerCfgFile to import cfg files

---

src/Utils/Helpers.ts

This will introduce loadCfgFile method in helpers that will load
onecc cfg file.

Introduce helpers loadCfgFile

---

src/Project/BuilderCfgFile.ts

This will fix typo 'selection' in BuilderCfgFile.

Fix typo in BuilderCfgFile

---

src/Utils/Logger.ts

This will revise log to show shorter date-time prefix in message.

Log with shorter date-time prefix

---

src/extension.ts

This will rename as 'OneBuild' to reflect it's a build command variable.

[extension] Rename OneBuild command

---

.github/workflows/check-pr-format.yml
package.json

This will enable lint for html, css and js files in src and/or media folder.

[CI] Enable lint for html, css and js

---

media/Jsontracer/index.html
src/Jsontracer.ts

this will fix RegExp in Jsontracer/index.html, which was applied incorrectly

[Jsontracer] Fix RegExp in index.html

---

media/Jsontracer/index.js

this will fix setTimeout to arrow function in Jsontracer/index.js

[Jsontracer] Fix setTimeout to arrow function in index.js

---

media/Jsontracer/dashboard.js
media/Jsontracer/level.js

This will render level-container. The level container will contain several bars on the bar chart.

[Jsontracer] Add level to render bar-graph

---

package.json

This will call the activate function immediately after the vscode is executed.
Without this, you can only look codelens and hover after another event occurs.
ONE-DCO-1.0-Signed-off-by: YongSoo Kang emoney96@naver.com

[Editor] add onStartupFinished event

---

media/Config/pathAutoComplete.js

in pathAutoComplete, getOutputPath is used but not defined
so add getOutputPath to pathAutoComplete.js

[Config] fix bug that getOutputPath is not defined

---

media/Config/buildImportCom.js

buildImportDom.js is made of functions that will be used to make DOM related to one-import

[Config] Add buildImportDom.js

---

.eslintignore

This commit disables `eslint` for `FlatBuffers` compilation results.
---
To resolve #206

Disable eslint for FlatBuffers compilation results

---

src/Circlereader/util/getNodeOutputs.ts

Returns the outputsArray of each operator separated by location, name and type. This function is used to represent the outputs data during visualization.

[Circletracer] Add a file that parses node outputs

---

src/Editor/CodelensProvider.ts

This will manage the name of the tool that will show the description of the attribute.

[Editor] Manage the name of the tool to show the attribute description

---

src/Circlereader/util/initBuiltinOptions.ts

Returns the builtInCodes of model.
The value returning from this function will help recognize the model type during visualization.
ONE-vscode-DCO-1.0-Signed-off-by: Donggil Lee donggillee94@gmail.com

[Circletracer] Add a file that init builtin options

---

src/Editor/CodelensProvider.ts

This will occur and detect an event that the codelens to be supplied has changed.

[Editor] Add a codelens event

---

.eslintignore
src/Circlereader/util/optionsAttribute.ts

This is to make the attributes of each node in the circle file suitable for the operator of the node for visualization of the node graph and return it.

[Circletracer] Add a file that creates attributes according to the node operator

---

media/Config/exportConfig.js

This will set default name of `.cfg` file.

[Config] Add exportConfig.js

---

src/Circlereader/util/caseOptions.ts
src/Circlereader/util/setAttributesByOption.ts

This is to call a function that extracts appropriate attributes according to the operator's name for visualization of the node graph.
ONE-vscode-DCO-1.0-Signed-off-by: Donggil Lee <donggillee94@gmail.com>

[Circletracer] Add a function that fetches attributes by option name

---

src/Editor/HoverProvider.ts

This will show Option List as a MarkdownString only for tools with sub-attributes.

[Editor] Fix the conditions that show the Option List.

---

src/Editor/json/tools_attr.json

This commit adds `fuse_add_with_fully_connected` tool attribute to provide missing option for one-optimize.
Draft PR: #276 
Signed-off-by: Alexander Moiseev <a.moiseev@samsung.com>

[Editor] Add fuse_add_with_fully_connected tool attribute

---

src/Project/BuilderCfgFile.ts
src/Project/JobOptimize.ts

This commit adds three missing options to one-optimize project config:
* fuse_add_with_fully_connected
* fuse_instnorm
* remove_fakequant
Draft PR: #276 
Signed-off-by: Alexander Moiseev <a.moiseev@samsung.com>

[Project] Add options to one-optimize config

---

src/Circletracer.ts

Previously, `import *` was used and this PR refactors this import statement so that 
only the method used in this file is imported.
Signed-off-by: Hyun Sik Yoon <hyunsik.yoon.1024@gmail.com>

Import a method rather than 'import *'

---

.github/workflows/check-pr-format.yml
.github/workflows/check-pr-tsc.yml
package-lock.json

This commit upgrades `node` version of Github Action from 12 to 16,
and apply changes for `package-lock.json`.
---
Parent Issue : #286

Upgrade node version of Github Action

---

package.json

This commit adds repository and publisher fields to package json file.
These fields are required to generate vsix package file.
Signed-off-by: Jiyoung Yun <jy910.yun@samsung.com>
related issue: #293

Add repository and publisher fields

---

package.json

This shows "ONE" in setting. Previously it was "one-vscode".
For #311

Show "ONE" instead of "one-vscode" in setting

---

media/Jsontracer/colorList.js

This commit adds missing copyright statement to `colorList.js`.
---
Originated from : #298

[media/Jsontracer] Add missing copyright statement

---

tsconfig.json

`.ts` files in `infra/` directory is not related with building ONE-vscode.
Therefore excluding `infra/` directory in `tsconfig.json` would be better.

[infra] Add infra directory to exclude list in tsconfig.json

---

infra/commit/signed-off-by-checker.ts

This file adds Signed-off-by checker script,
which checks whether Signed-off-by is inserted in commit meesage or not.
---
Parent Issue : #299 
Draft : #308

[infra] Add Signed-off-by checker script

---

infra/commit/no-body-checker.ts

This commit adds a script for checking commit message body.
---
Parent Issue : #123
Draft : #308

[infra] Add Commit Message Body Checker script

---

media/Circletracer/index.html

This commit adds missing copyright statement.
---
Parent Issue : #298 
Draft : #302

[media/Circletracer] Add missing copyright statement

---

package-lock.json
package.json

This commit updates following packages
- Add `ts-node` : this will be used in Github Action to run infra/**/*.ts
- Upgrade `mocha` : from major version 8 to 9
- Remove `vscode-test` : never used

[infra] Update package.json

---

package.json

This adds an input box into Setting under [ONE] section,
where end-user can enter directory path for model files.
for #330
reference: https://code.visualstudio.com/api/references/contribution-points#contributes.configuration

Add Setting For Model Directory Path

---

.github/workflows/check-license.yml

`report_verification_result` cannot be run on `push` event.
But current codes did not care about this.
This commit will fix it.

[CI] Fix license checker on push event

---

.github/workflows/check-license.yml

Until now, `pull_request` is used for triggering github action.
But it causes authrization error.
This commit replaces `pull_request` to `pull_request_target`.

[CI] Fix trigger condition for pull request

---

package.json

This changes package description form "ONE Compiler for VSCode"
to "ONE for VSCode"
to synchronize comment at https://github.com/Samsung/ONE-vscode/pull/332#discussion_r824399840.

Change Package Descripion

---

src/Project/ToolArgs.ts

Let's fix add() of ToolArgs if value is undefined.

[Project] Fix add() of ToolArgs if value is undefined

---

infra/license/package-judgment.json

This adds expand-template and rc into permitted license.
By reading their README.md in their github repo, they don't modify
original licenses or don't add additional condition.
From https://github.com/Samsung/ONE-vscode/pull/348#issuecomment-1067522109

Add expand-template and rc into permitted license

---

.github/workflows/check-license.yml

Until now, license checker checked out with latest main ref.
As a result, PR is not correctly checked.
This commit will fix it.

[CI] Fix checkout ref in license checker

---

.github/workflows/check-commit.yml

Until now, we used `refs/pull/PR_NUMBER/merge` or `github.event.after` to fetch PR's commit.
But it causes unintened errors.
This commit will fix it with `github.event.pull_request.head.sha`.

[CI] Fix fetch ref in Github Action

---

src/Views/FileTreeView.ts

This code uses code of `FileSystemProvider` from
https://github.com/microsoft/vscode-extension-samples/blob/9a2eb8ba5f781edb847e8c3eb563af96334fa534/tree-view-sample/src/fileExplorer.ts
The code inside comment was copied from original code and then run with `bash infra/format`.
In next PR, I will uncomment and modify this code.
**What is this code for?**
This code implements `FileSystemProvider`, which reads directory and lists files and sub-dirs. This list will be used to show file and list inside our `"Files"` View.
`FileSystemProvider` implements `vscode.TreeDataProvider<Entry>` and , `vscode.FileSystemProvider`, which has lots of abstract methods. Writing all code needs time and I decided to reuse existing code in `vscode-extension-samples/tree-view-sample`.
parent issue: #330
draft: …

Use FileSystemProvider

---

src/Tests/MockJob.ts
src/Tests/MockupJob.ts

Let's add MockupJob for preparing unittests of Jobs such as JobCodegen.

[Tests] Add MockupJob for unittests of Jobs

---

infra/license/README.md
infra/license/check-result-formatter.ts
infra/license/license-checker.ts
infra/license/package-judgment.json

This commit renames following things for consistancy.
- Remove `ONE_` prefix
- Rename `deny` to `fail`.
---
- `flowchart.png` will be modified in another PR because of size limit
Draft : #358 
Originated from https://github.com/Samsung/ONE-vscode/pull/295#discussion_r819540232

[infra] Rename keywords for license-checker

---

infra/license/check-result-formatter.ts

When daily license check result is not passed, new issue should be created.
However, generating failure mark is not added.
This commit will fix it.
---
Draft : #358

[infra] Generate failure logfile for license check result

---

.github/workflows/check-daily-license.yml

This commit fixes wrong format of `ref`.
It should be used with `with`.

[CI] Fix wrong format of ref

---

package.json

This adds a menu, `set model directory`, to `Files view.
After setting an initial directory, user can set it to
another directory using this menu.
parent issue: https://github.com/Samsung/ONE-vscode/issues/330
draft: https://github.com/Samsung/ONE-vscode/pull/297
after #375

Add menu to `Files` view

---

infra/license/README.md
infra/license/license-checker.ts
infra/license/license-judgment.json

This commit changes the format of `license-judgment.json` with following reason.
- To keep consistency with `package-judgment.json`
- To make understanding why `permitted` of license is not `yes`
---
Draft : #358

[infra] Change license-judgment.json format

---

src/Project/BuilderCfgFile.ts

Let's do clearJobs when cfg is imported to fix #319.

[Project] Do clearJobs when cfg is imported

---

src/Tests/Utils/Helpers.test.ts

Let's add unittests for Helpers in Utils.

[Tests] Add unittests for Helpers in Utils

---

infra/license/license-checker.ts

This commit refactors following things
- Reduce if-else statements
- Make verification logic clear
- Make comment creation logic clear
- Inline comments to dictionary values
---
Draft : #358

[infra] Refactoring license-checker

---

infra/license/check-result-formatter.ts

Current format has a header but we can know if there's
license issue or not without the header by looking at
body of the license verification comment.
Plus, header with big bold font distracts attention about PR.
So I guess removing the header is better to concentrate
reviewing PR.

Remove header of license verification comment

---

package.json

Make ONE-vscode run on the machine where workspace is.
With this PR, when in a local workspace, ONE-vscode runs on the local machine.
When in a remote workspace, ONE-vscode runs on the remote machine.
https://code.visualstudio.com/api/advanced-topics/remote-extensions#architecture-and-extension-kinds
https://code.visualstudio.com/api/advanced-topics/extension-host#preferred-extension-location

Make ONE-vscode run on the machine where workspace is

---

src/Tests/runTest.ts

This commit fix runTest.ts to drive indexCI or index for CI.

[Tests] Fix runTest.ts for CI

---

media/Compile/compile.js
src/Compile/CompilePanel.ts
src/Utils/Uri.ts
src/extension.ts

This enables an empty 'Compile' webview page, which is loaded by
[Compile] menu in File Explorer view.
For #331
Draft #297

Enable empty 'Compile' webview page

---

src/Tests/Project/JobRunner.test.ts
src/Tests/Project/ToolRunner.test.ts
src/Tests/README.md

This commit adds `@Use-onecc` suite name. Current github action doesn't
install the latest ONE so filter the tests which use onecc.

[Tests] Add `@Use-onecc` suite name

---

.github/workflows/check-copyright.yml

To create comment, authorization is needed but `pull_request` does not have it.
This commit fixes `pull_request` to `pull_request_target`.

[CI] Fix trigger condition and ref

---

media/Compile/compile.js
src/Compile/CompilePanel.ts

This adds basic event handlers for HTML element in [Compile] webview.
The purpose of this PR is to provide basic way to handle events in
JS and vs extension.
Later, "Compile" modeum needs to enable compilation by ONE by adding
more code into this JS code or `_setWebviewMessageListener` in
`CompilePanel.ts` file.
For https://github.com/Samsung/ONE-vscode/issues/331
Draft https://github.com/Samsung/ONE-vscode/pull/297

Add basic event handlers for HTML element in [Compile] webview

---

infra/license/package-judgment.json
package-lock.json
package.json

This moves some packages from `devDependencies` to `dependencies`
in pckage.json.
Parent issue: https://github.com/Samsung/ONE-vscode/issues/447 for background and solutions.

Move some packages into `dependencies` in package.json

---

src/Backend/API.ts
src/extension.ts

This adds API that backend extensions must implement
and a function (registerBackend) through which backend extensions
registers backend implementation.
Related issue #441
Related draft: #444 #445

Add basic support for multiple backend

---

package.json

This contextual title is not required if CompilerToolchainView is
included in ONE-Views container.

[Compiler/View] Remove contextual title in compiler toolchain view

---

package.json

This adds `test-no-screen` script in package.json, which is used
when dev environment cannot run vscode GUI. (e.g., Windows connecting
Linux machine via SSH extension).
This is originated from [ .github/workflows/check-pr-format.yml.](https://github.com/Samsung/ONE-vscode/blob/e6e52be227ae83e1622a303646b3aad14047dbdd/.github/workflows/check-pr-test.yml#L18)

Add 'test-no-screen' script

---

media/icon/dark/install.svg
media/icon/dark/refresh.svg
media/icon/light/install.svg
media/icon/light/refresh.svg
package.json

Icon images in `media/` is VSCode built-in icons.
This commit will replace them with built-in icons.

Use codicon instead of raw image files

---

package.json

This commit adds context and detail explorers on ONE view container.
The detail explorer is collapsed at the first installed.
Once the user has changed the view state by moving, hiding the view,
the initial state will not be used again.
Signed-off-by: Jiyoung Yun <jy910.yun@samsung.com>
related issue: #476 
/cc @Samsung/one-vscode

[View] Add context and detail explorers

---

infra/format

This will skip format checker for json files if .FORMATDENY exist in folder.

[infra] Apply format deny for json files

---

src/OneExplorer.ts

This commit removes openfile command which currently generates
many warnings.
Let's remove this now and implement properly later.

[OneExplorer] Remove openfile command

---

src/OneExplorer.ts

This commit expands the tree until model files.
It improves UI to save user clicks.

[OneExplorer] Expand tree until model file

---

src/OneExplorer.ts

Let's remove 'oneTree' member.
**This change is necessary for a bug fix for refresh command.**
NOTE that OneNodes are generated on the first expansion of tree view.
'oneTree' is not used as getChildren method should returns
freshly generated trees.

[OneExplorer] Remove 'oneTree' member

---

.eslintignore

This will include to ignore external netron codes to come.

Ignore eslint for CircleGraph/external

---

src/OneExplorer.ts

This commit refactors Node interface.
It converts Node interface to class
as it requires more functionality thus it needs OOP.

[OneExplorer] Refactor Node as class

---

src/Backend/ToolchainImpl/DebianToolchain.ts
src/Tests/Backend/ToolchainImpl/DebianToolchain.test.ts

This commit changes the debian command to check the installation
of packages. If the given package is not installed, it returns
not zero value.

Change the debian command to check the installation of packages

---

src/Backend/Executor.ts

This commit introduces `getExecutableExt` method which returns executable
extension list to Executor class.
---
draft: #522

[Backend] Introduce `getExecutableExt` method to executor

---

src/Backend/Executor.ts

This commit changes inference API of executor to `runInference`.
Each executor takes the model path to infer and specific option list.
draft: #522

[Backend] Change executor inference API

---

src/Backend/Backend.ts
src/Compile/CompileEnv.ts

This commit adds compilerEnvMap for managing compiler environment
with backend name.

Add compilerEnvMap for managing compiler env

---

package.json

This will add csslint tool to exclude media/CircleGraph/external folder
as files are from external source.

Add csslint to exclude CircleGraph/external

---

src/OneExplorer.ts

This commit enables users to open ConfigEditPanel by clicking
the .cfg file on OneExplorer view.

[OneExplorer] Open ConfigEditPanel by clicking 

---

package.json
src/Backend/Backend.ts
src/Tests/Toolchain/ToolchainEnv.test.ts
src/Toolchain/ToolchainEnv.ts
src/View/InstallQuickInput.ts
src/extension.ts

This commit changes the compiler toolchain view name and
related codes. It uses toolchain word instead of compiler toolchain.

Change Compiler Toolchain name to Toolchain

---

package.json
src/Execute/executeQuickInput.ts
src/extension.ts

This commit adds execute quickInput which select the backend, model to run,
and input-spec as option. This will be deprecated when one-infer has been landed.
---
draft: #522

[Execute] Add execute quickInput

---

media/Mondrian/mondrianViewer.js
media/Mondrian/style.css
package.json
res/samples/traces/sample.tracealloc.json
src/Mondrian/MondrianEditor.ts
src/Mondrian/README.md
src/extension.ts

This commit implements custom editor which provides graphical view of Mondrian JSON allocation traces (`.tracealloc.json`).
Issue: #395 
Draft: #452 
ONE-vscode-DCO-1.0-Signed-off-by: Alexander Moiseev <a.moiseev@samsung.com>
Currently implemented features: 
* JSON input data parsing
* round-robin colorized memory blocks output
* ability to scale horizontally/vertically
* switching between memory segments.
More features such as model trim, mouse hover info, rulers, more coloring modes etc. will be added in new PRs, #395 description contains feature roadmap.
Example data: 
[example.tracealloc.json.txt](https://github.com/Samsung/ONE-vscode/files/8531449/example.tracealloc.json.txt) (remove .txt extension for plugin to properly detect .json)
Scaled up memory zone view:
Model "bird's eye" …

[Mondrian] Implement viewer for Mondrian files

---

package.json

There are two `customEditors` in `package.json`.
These should be integrated as one.

Fix duplicated item in package.json

---

src/Backend/Compiler.ts

This revised Compiler backend API to have `getToolchainTypes()` and
`getToolchains()` methods, which are deprecating previous `toolchains()`
method.
For #573

Revise Compiler backend API

---

package-lock.json
package.json

This will upgrade engines.vscode in package file to 1.57+.
- postMessage with Uint8Array works correctly and faster with this.

Upgrade package engines vscode

---

.github/workflows/build-release.yml
release_notes.md

This commit adds release GitHub Actions workflow.
It checks license, copyright issues and
runs build test and unit tests. There is no issue for
release, it creates vsce package and release it.
Related issue: #571 
Draft workflow: https://github.com/jyoungyun/ONE-vscode/actions/runs/2298576642
This workflow made an issue for release. ([example](https://github.com/jyoungyun/ONE-vscode/issues/7))
It runs several release tests and if everything is successful, it releases new version. ([example](https://github.com/jyoungyun/ONE-vscode/releases/tag/0.0.1))

[CI] Add release workflow

---

package.json
src/OneExplorer.ts

This commit implements create-cfg command and it's UI of 'add' icon
as inline command of baseModel(tflite,onnx) on OneExplorer view.

[OneExplorer] Implement create-cfg

---

media/CircleGraph/circle-metadata.json

This will add missing category field in circle-metadata.json
- category is used to colorlize nodes in the graph.

[CircleGraph] Add category in circle-metadata

---

infra/license/license-checker.ts
infra/license/package-judgment.json

Until now, `one-vscode` is added in `package-judgment.json`.
Let's exclude `one-vscode` from the logic itself.

[infra] Exclude one-vscode from license checker

---

infra/license/license-checker.ts

`pkgName` is like `one-vscode@0.0.1`.
To filter all versions of `one-vscode`, logic should be fixed.
This commit will fix it.

[infra] Fix one-vscode checking logic

---

media/CircleGraph/view.js

This will disable showing node properties window when clicked.
- click is changed to toggle selection of the node

[CircleGraph] Disable show node properties window

---

src/OneExplorer.ts

This commit removes collapse arrow from the nodes with no child.

[OneExplorer] Enhance collapsible state

---

src/OneExplorer.ts

This commit adds [one-import-*][output_path] entries of configuration
as the child nodes.

[OneExplorer] Add more child nodes

---

src/Backend/Command.ts

This revises `Command.str()` in a way that when `root === true`, `str()` starts with `"sudo"`.

Revise Command.str() considering root

---

src/Backend/Command.ts

This introduces piped command, which represents
`$ cmd1 | cmd2` format.

Introduce PipedCommand

---

src/Backend/Command.ts

Previously we wanted to send a list of commands as `CommandList`
and command with pipe as `PipedCommand`.
After more discussion, we will create one shell script that contains
list of command and return the path of shell script.
Due to this decision, let's remove `PipedCommand` and `CommandList`.

Remove PipedCommand and CommandList

---

src/Backend/Compiler.ts

This add a method which returns a command that must be called
before calling `getToolchains()` method.
For #627

Add prerequite method into Backend API

---

src/Utils/Balloon.ts

This adds `Balloon.warning()` method.

Add Balloon.warning()

---

src/Backend/Compiler.ts

This introduces `getInstalledToolchains()` method in backend API.
For #659

Introduce getInstalledToolchains() method

---

src/OneExplorer.ts
src/Utils/Helpers.ts

This commit gets workspace root from helper.
The helper takes charge of handling related exceptions
on workspace root.

[OneExplorer] Get workspace root from helper

---

src/Tests/Utils/Helpers.test.ts
src/Utils/Helpers.ts

Let's introduce RealPath class.
It represents a normalized absolute path
which actually exists on the filesystem.
For #669

[Utils] Introduce RealPath class

---

src/OneExplorer/OneExplorer.ts
src/extension.ts

This commit creates OneExplorer directory and moves the file into it
to expand the module.

[OneExplorer] Move OneExplorer inside directory

---

infra/copyright/copyright-checker.ts
src/Utils/external/MultiStepInput.ts
src/Utils/external/Nonce.ts
src/Utils/external/Uri.ts

This commit removes Samsung Copyright which was in external source codes.

Remove Samsung Copyright in external source codes

---

src/Tests/Toolchain/ToolchainEnv.test.ts
src/Toolchain/ToolchainEnv.ts

This commit removes installed toolchain variable.
The installed toolchain can be multiple toolchains and
it does not have to be stored and managed.

[Toolchain] Remove unused installed toolchain variable

---

src/Backend/ToolchainImpl/DebianToolchain.ts
src/Tests/Backend/ToolchainImpl/DebianToolchain.test.ts

This uses aptitude for installation of debian toolchain.
This was copied from backend repo.

Use aptitude for backend API

---

src/Backend/Backend.ts
src/OneExplorer/OneExplorer.ts
src/Project/Builder.ts
src/Project/BuilderCfgFile.ts
src/Project/JobRunner.ts
src/Project/ToolRunner.ts
src/Project/WorkFlow.ts
src/Tests/Project/Builder.test.ts
src/Tests/Project/JobRunner.test.ts
src/Tests/Project/ToolRunner.test.ts
src/Tests/Project/Workflow.test.ts
src/Tests/Toolchain/ToolchainEnv.test.ts
src/Toolchain/ToolchainEnv.ts
src/Utils/Logger.ts
src/extension.ts

This applies static logger.
1. Make all class var and method as static.
2. Remove `logger` param being passed around and `import` 
3. Remove deprecated methods
4. Classes now have logging tag
While doing the above, one method `appendLine` was added into Logger
because ToolRunner needs both `append` and `appendLine`.
For #662 

Apply static logger

---

src/Toolchain/ToolchainProvider.ts
src/extension.ts

This commit uninstalls the installed toolchain.
After uninstalled the toolchain, the toolchain view will be updated
automatically.

[Toolchain] Uninstall toolchain

---

src/OneExplorer/OneExplorer.ts

This commit improves OneExplorer to find all the config files
and the derived files in the workspace.

[OneExplorer] Find nodes beyond directory bound

---

src/OneExplorer/OneExplorer.ts

Previously, when there's error during running onecc,
progress notification does not disappear.
This commit makes progress notification.
for https://github.com/Samsung/ONE-vscode/issues/635

Hide progress when compilation error occurs

---

src/OneExplorer/OneExplorer.ts

Previous, `warning` was shown when running onecc failed.
Let's fix this to `error`.
From https://github.com/Samsung/ONE-vscode/pull/711#discussion_r882279587

Show error message when running onecc failed

---

src/Backend/Backend.ts
src/Project/BuilderCfgFile.ts
src/Project/JobRunner.ts
src/Utils/Logger.ts

While converting existing console.log to Logger's methods,
two changes were made.
1. Logging object type in Json format
2. Accept variadic params
This PR also has some usage cases of 1 and 2.
For https://github.com/Samsung/ONE-vscode/issues/662

Make Logger to log object and accept variadic params

---

package.json
src/OneExplorer/OneExplorer.ts

This commit adds rename command by right-clicking on the nodes of all
types (model files and config).
It doesn't change path, only the filename.

[OneExplorer] Add rename command

---

src/CfgEditor/CfgEditorPanel.ts

Until now, content of cfg file is not saved but parsed every time.
To apply changes at cfg editor and save resources,
this commit introduces member variable `_oneConfig` to hold it.
---
Draft : #697

[CfgEditor] Add member variable for CfgEditorPanel

---

src/OneExplorer/OneExplorer.ts

This commit validates an input for renaming.
It checks (1) ext, (2) file already exists.

[OneExplorer] Validate input for rename

---

src/Execute/executeQuickInput.ts
src/Utils/MultiStepInput.ts
src/View/InstallQuickInput.ts

This commit moves MultiStepInput class out of external dir.
This commit contains the code chage about MultiStepInput.
Draft PR: #699 (Big draft PR...)

[Utils] Move MultiStepInput out of external dir

---

package.json

This commit revises activation events.
NOTE: onStartupFinished will activate our extension
some time after VS Code starts up.
The other events are redundant.
---
FYI,
https://code.visualstudio.com/api/references/activation-events#onStartupFinished
We want to provide our users with our extension always. 
There are two options: '\*' and 'onStartupFinished' as activation events 'always'.
'onStartupFinished' will activate our extension some time aftser VS Code starts up, 
so that it doesn't slow down the vscode's start-up, unlike "*" will do.

Revise activation events

---

package.json
src/OneExplorer/OneExplorer.ts

This commit adds 'open with text editor' command for cfg files.
----
From #730

[OneExplorer] Add 'Open with Text Editor' command

---

package.json
src/OneExplorer/OneExplorer.ts

This commit adds Collapse All command to OneExplorer
context menu.

[OneExplorer] Add collapseAll command

---

src/OneExplorer/OneExplorer.ts

This commit expand the node in the OneExplorer when it is created
and also opens an editor.
---
This commit conflicts with #745, so it is queued by including the one.

[OneExplorer] Show and open config on create 

---

src/CfgEditor/CfgEditorPanel.ts

Until now, `_getHtmlForWebview` function was returning literal HTML source.
In addition, old css and js have been used.
This commit replaces static files to new ones.
---
Parent issue : #698 
Draft : #697

[CfgEditor] Replace static files as new

---

package.json
src/extension.ts

This commit renames command names from
onevscode.* to one.toolchain.*

[Toolchain] Rename command names

---

package.json
src/Config/ConfigStatusBar.ts
src/extension.ts

This commit renames command names from
onevscode.* to one.editor.* and so on.

[CfgEditor] Rename command names

---

package.json
src/extension.ts

This commit renames commands onevscode.* to one.backend.*.

[Backend] Rename commands

---

package.json
src/extension.ts

This commit rename commands from onevscode.* to one.project.*.

[Project] Rename commands

---

package.json
src/extension.ts

This commit renames command onevscode.* to one.device.*.

[Device] Rename commands

---

src/CfgEditor/CfgEditorPanel.ts

Because of VSCode design, `onDidChangeTextDocument` can be called even when there are no changes.
It is not intended behavior that `updateWebview` is called even if document is not changed.
This commit will fix it by checking whether there are actual document changes.
---
Draft : #697

[CfgEditor] Add more condition for onDidChangeTextDocument

---

package.json
src/extension.ts

This commit renames commands onevscode.* to one.viewer.*

[Viewer] Rename commands

---

src/PartEditor/PartEditor.ts

This will relocate initialization of _backEndNames to
resolveCustomTextEditor method as current position is called multiple
times while editing.

[PartEditor] Relocate inital BackendNames

---

src/PartEditor/PartEditor.ts

This will revise to use normal string instead of using template literal types.

[PartEditor] Use normal string for template literal types

---

media/CfgEditor/cfgeditor.html
media/CfgEditor/index.js

This commit fixes bugs relates with `one-import`, which is not updating cfg file content correctly.
---
Draft : #697 
---
| Type | Item | Before | After |
| :---: | :---: | :---: | :---: |
| Bugfix | Import Model Type | ![input_modelT_before](https://user-images.githubusercontent.com/24720192/172770998-e566d7a7-3856-4080-97e4-81a297d95a84.gif) | ![input_modelT_after](https://user-images.githubusercontent.com/24720192/172771014-1d394db0-31cc-4ca6-8b56-6972b1e49031.gif)
| Bugfix | Import Step | ![Import_step_before](https://user-images.githubusercontent.com/24720192/172771558-50d98018-eee6-4800-b30d-3d465b04f539.gif) | ![import_step_after](https://user-images.githubusercontent.com/24720192/172771574-143 …

[CfgEditor] one-import UI Bugfix

---

src/Backend/ToolchainImpl/DebianToolchain.ts
src/Tests/Backend/ToolchainImpl/DebianToolchain.test.ts

This commit adds -y and -q option to uninstall command.
This options fix the stop procedure to wait for user input and reduce
log messages.
This commit is copied from backend project.

[Backend] Add automatic yes and quiet option to uninstall command

---

src/View/InstallQuickInput.ts

This commit shows canceled installation message when user rejects
prerequisites() call.

[Toolchain] Show canceled installation message

---

src/PartEditor/PartEditor.ts

This will close PartGraphSelector when PartEditor is closed.

[PartEditor] Close PartGraphSelector

---

src/Backend/Compiler.ts
src/Tests/Toolchain/ToolchainEnv.test.ts

This removes deprecated `toolchains()` method in Compiler.ts.

Remove deprecated `toolchains()` method

---

src/Backend/ToolchainImpl/DebianToolchain.ts
src/Tests/Backend/ToolchainImpl/DebianToolchain.test.ts

This commit uses ProblemResolver to install older packages.

[Backend] Use ProblemResolver to install older packages

---

src/Project/ToolRunner.ts
src/Tests/Project/ToolRunner.test.ts

Currently exit code and signal handling is kinda complex.
This commit tries to sumplify this by introducing two
interfaces.
from https://github.com/Samsung/ONE-vscode/pull/749#issuecomment-1149432151

Refactor exit code and signal of ToolRunner

---

src/OneExplorer/OneExplorer.ts

This commit uses treeview api to exploit vscode's latest support.
This commit includes UI change that enables multi-selection.

[OneExplorer] Use TreeView API

---

media/Mondrian/mondrianViewer.js
media/Mondrian/style.css
src/Mondrian/MondrianEditor.ts
src/Mondrian/README.md

This commit adds viewport limiter bar which provides ability to set min/max cycle values to avoid hang-ups for a very large models.
Areas outside of active 'viewport' are marked with shadow borders.
Issue: #395 
Screenshot (shadow on left and right marks viewport limit):
Signed-off-by: Alexander Moiseev <a.moiseev@samsung.com>

[Mondrian] Add viewport dynamic limiter bar

---

src/Project/JobRunner.ts
src/Utils/Logger.ts

This commit shows output log during running job runner.

[Logger] Show output log during running job runner

---

media/PartEditor/index.html
src/PartEditor/PartEditor.ts

This will use TRIX to replace NPU in backend names.

[PartEditor] USe TRIX

---

src/PartEditor/PartGraphSelector.ts

This will revise to set CircleGraphCtrl view mode to selector for
PartEditorSelector.

[PartEditor] Set view mode to selector

---

package.json
src/Toolchain/ToolchainProvider.ts
src/extension.ts

This commit adds runCfg command in toolchain provider.
And it hides this command from command palette because it can't
work without cfg file.
Draft PR: #818

[Toolchain] Add runCfg command in toolchain provider

---

src/CircleGraph/CircleViewer.ts

This will disable support for MultipleEditorsPerDocument.

[CircleViewer] Disable MultipleEditorsPerDocument

---

src/Toolchain/ToolchainProvider.ts

This commit changes teh filter code of installed toolchain items.
The `DebianToolchain` of the backend and the `DebianToolchain` of this project
are not recognized as the same object by `instanceof`.
So, it is classified by classname.

[Toolchain] Change filter of installed toolchain items

---

package.json

This commit hides unnecessary commands in command palette
Related issue #839

[OneExplorer] Hide from command palette

---

media/CircleGraph/index.html

This will tidy 'about' styles which are not used anymore.

[CircleGraph] Tidy 'about' style

---

media/PartEditor/index.js
src/PartEditor/PartEditor.ts

This will revise partition editor view to show backend and nodes in
color by backend.

[PartEditor] Use color by backend

---

src/Project/JobRunner.ts

This remvoed `title` with progerss notification since
`title` is concatenated with `message` and this sometimes makes
message with awkward wording.

Remove `title` with progress notification

---

package.json

This commit hides unnecessary commands from command palette.
The hidden commands may not need to exposed to end user since it
could make the user confused.
---
for: #839 
With this PR, the following commands will be remained.

Hide unnecessary commands from command palette

---

src/OneExplorer/OneExplorer.ts
src/Utils/Balloon.ts

This adds 'OK' and 'See log' button in methods in Balloon.
When 'See log' button is pressed, log window will be opened.
This also changes some methods in OneExplorer.ts
to show this new Balloon. (as a demonstration)
for #823

Show `See log` button in Balloon

---

.vscode/launch.json
src/Utils/Logger.ts

This shows debug log only when it runs in vscode debug mode.
When ONE-vscode is packaged into vsix, debug log won't be shown.
For https://github.com/Samsung/ONE-vscode/issues/870#issuecomment-1168453781

Show debug log only when it runs in vscode debug mode

---

src/OneExplorer/OneccRunner.ts

Balloon was used previously in #860
but it was removed accidentally in #878.
Let me revoke the change.

Use Balloon in OneccRunner

---

.github/workflows/build-release.yml

This commit will change release note file position to `infra/release/release_note.md`.

[workflow] Update Release note file position

---

media/PartEditor/index.js

This will revise partition editor to show operator code for each items
in operators list.

[PartEditor] Show operator code in operators list

---

media/CircleGraph/view.js

This will revise CircleGraphCtrl to set category style of the node only for
viewer mode.

[CirclrGraph] set category style only for viewer mode

---

media/CircleGraph/view.js

This will disable clang format for class method getter.

[CircleGraph] clang format off of get class

---

media/CircleGraph/view.js

This will revise toggleSelect method handle with ctrl key pressed.
- without ctrl: select only the node
- with ctrl: toggle node selection

[CircleGraph] toggleSelect with ctrl key

---

package.json

This commit hides `build` command from command palette option.
---
For #839 
After this PR, following commands are left in command palette.

Hide `build` from command palette option

---

src/PartEditor/PartEditor.ts
src/PartEditor/PartGraphSelector.ts

This will revise update from PartEditor to PartGraphSelector to remove
backend as it is not used anymore.

[PartEditor] Revise update without backend

---

package.json

This commit adds run icon for each `cfg` inline.

[OneExplorer] Add run icon inline

---

src/PartEditor/PartEditor.ts

_document is now always valid object so there is no need to check.

[PartEditor] Do not check _document

---

src/OneExplorer/OneExplorer.ts

This commit saves tree root.
When it needs to rebuild a part of the tree by 'refresh',
build the sub-tree under the given node.
----
From #738
COMMENT: This feature is required to implement `reveal` command and `open in vscode-explorer view` command. Currently, we cannot search through the root node as it doesn't keep it.

[OneExplorer] Save tree root

---

media/PartEditor/index.js

This will revise select element usage.
- use `add()` not `options.add()`
- use `selectedOptions`

[PartEditor] Revise select element usage

---

media/CircleGraph/view.js

This will revise setSelection method graph traverse to use nodes.keys()
for using forEach as this method is used in existing codes.

[CircleGraph] Revise setSelection graph traverse

---

src/Tests/Backend/Backend.test.ts

Let's add teardown to Backend test to avoid remaining test mockup
backend.

[Tests] Add teardown to Backend test

---

src/Project/ToolRunner.ts

If `boolean` parameter is `undefined`, it can be interpreted as `false`.
Let's use default value instead of `undefined`.

[ToolRunner] Use default value instead of undefined

---

src/PartEditor/PartEditor.ts
src/PartEditor/PartGraphSelector.ts

This will revise viewColumn of PartGraphSelector to be
right side of PartEditor pane.

[PartEditor] Show PartGraphSelector to right of PartEditor

---

src/Toolchain/ToolchainEnv.ts
src/Toolchain/ToolchainProvider.ts

This commit fixes the problem pointed out in SonarLint.

[Toolchain] Fix SonarLint related issues

---

media/PartEditor/index.js

This will reset Operators listbox before filling.

[PartEditor] Reset Operators listbox before fill

---

src/Tests/MockCompiler.ts
src/Tests/Toolchain/ToolchainEnv.test.ts

Let's separate MockCompiler from ToolchainEnv.test and introduce it.

[Tests] Separate and introduce MockCompiler

---

src/Tests/Toolchain/ToolchainProvider.test.ts
src/Toolchain/ToolchainProvider.ts

This commit revisits ToolchainProver class in src/Toolchain.

[Toolchain] Revisit ToolchainProvider class

---

.github/workflows/check-commit.yml
.github/workflows/check-copyright.yml
.github/workflows/check-license.yml
.github/workflows/check-pr-format.yml
.github/workflows/check-pr-test.yml
.github/workflows/check-pr-tsc.yml

This commit introduces a new feature to disable pr test if `PR/No test` label is set.
---
for: #958 
You can find how theses actions work through #963 (the pr will be closed and the `no_test` branch will be removed after this pr has been merged).

[CI] Disable PR test for `PR/No Test` label

---

media/CfgEditor/index.js
media/CfgEditor/updateContent.js
media/CfgEditor/vscodeapi.js

Currently, acquireVsCodeApi was called in `index.js` and it cannot be referenced from other js files.
However, calling `acquireVsCodeApi` more than one time causes an error.
("An instance of the VS Code API has already been acquired")
To resolve these issues, this commit introduces our own API to use VsCodeApi.

[CfgEditor] Fix to use acquireVsCodeApi only once

---

src/Backend/Executor.ts
src/Tests/Execute/InferenceQuickInput.test.ts
src/Tests/Execute/InferenceRunner.test.ts

This commit will revisit `Executor` for some reason
about `name()`: if we add None Backend Executor, we need to add Executor name on this.
otherwise, follow Backend Name.
about `require()`: to use on `satisfied()` on Device API.

[DeviceAPI] revisit Executor to make this use on Device API

---

src/Execute/InferenceQuickInput.ts

`selectInputModel` and `pickBackend` function return two types,
one is `void` and the other is `undefined`.
This commit fixes to return `void` consistently.

[Execute] Use consistent return statement

---

src/Tests/Execute/InferenceQuickInput.test.ts

`map(...)` function returns new array but it is not used.
This commit will fix to use `forEach` instead of `map`.

[Tests] Use forEach instead of map

---

src/Tests/Toolchain/ToolchainProvider.test.ts

`map(...)` function returns new array but it is not used.
This commit will fix to use `forEach` instead of `map`.

[Toolchain] Use forEach instead of map

---

src/OneExplorer/OneExplorer.ts
src/extension.ts

As `OneExplorer` class is used for anywhere except constructor,
extracting constructor of `OneExplorer` separate function seems better.
Meanwhile, this commit removes unused codes in `OneExplorer`.

[OneExplorer] Refactor OneExplorer

---

src/Backend/Backend.ts
src/Tests/Backend/Backend.test.ts

This commit will add `registerExcutor` API on `backendRegistrationApi`.
`registerExecutor` API will use to register executor and use this on Device API.

[Backend] Add registerExecutor API on backend register

---

src/OneExplorer/ConfigObject.ts
src/OneExplorer/OneExplorer.ts
src/Tests/OneExplorer/ConfigObject.test.ts

This commit rewrite ConfigObject to..
(1) Return a list of Artifact instead of Uri
(2) Introduce getBase(Drived)ModelsExists function to filter existing artifacts
(3) Introduce isChildOf method and use it
(4) Remove redundant wrapper `parse` method and use `createObject`
(5) Pass string filepath instead of Uri as parameter of functions (parseDerivedModels, parseBaseModels)
(6) Replace map with forEach to remove unused variable
---
#1012 must be merged first.
From #1011

[OneExplorer] Rewrite ConfigObject 

---

src/OneExplorer/ConfigObject.ts
src/OneExplorer/OneExplorer.ts

This commit rewrites OneExplorer to
(1) Introduce getCfgList() helper function
(2) Introduce createDirectory/BaseModel/ConfigNode() helpers for readibility
(3) Rename searchPairConfig to searchConfig
(4) Remove unused function comparePath()
(5) Import 'Artifact' interface
(6) Use ConfigObject::getDerivedModelsExists()
(7) Replace nodeTypeToStr with node.typeAsString getter
---
From #1011 
Wait until #1016 is merged

[OneExplorer] Rewrite OneExplorer 

---

src/CircleGraph/CircleViewer.ts

`openView` function was returning two types,
one is `true` and the other is `void`.
This commit fixes this to use consistent return statement.

[CircleGraph] Use consistent return statement

---

src/PartEditor/PartEditor.ts
src/PartEditor/PartGraphSelector.ts

Some functions were returning two types,
one is `true` and the other is `void`.
This commit fixes this to use consistent return statement.

[PartEditor] Use consistent return statement

---

src/OneExplorer/ConfigObject.ts
src/OneExplorer/OneExplorer.ts
src/Tests/OneExplorer/ConfigObject.test.ts

This commit renames derivedModel to product,
to use more inclusive term as it now include not only output models
but also logs.
---
For #1011

[OneExplorer] Rename DerivedModel to Product

---

media/PartEditor/index.js

This commit excludes properties from the prototype of `partition.OPNAME`.

[PartEditor] Exclude properties from the prototype

---

media/Mondrian/mondrianViewer.js

`alloc` variable is declared without any qualifier.
This commit adds it with `const`.

[Mondrian] Declare variable with const

---

src/OneExplorer/OneExplorer.ts

`vscode.workspace.fs.delete` returns `Thenable<void>`, so `return` is useless.
This commit removes this.

[OneExplorer] Do not use useless return

---

src/OneExplorer/OneExplorer.ts

This commit modifies OneExplorer to handle no workspace opened cases.
To introduce welcome view, showing pop-up message to user should be deprecated.
---
draft: #953

[OneExplorer] Handle no workspace opened case

---

src/OneExplorer/ConfigObject.ts
src/OneExplorer/OneExplorer.ts

This commit changes model file icon from File to 'symbol-variable'
To make it different from log or other product files.
----
From #1039 
Wait for #1041

[OneExplorer] Change model file icon 

---

package-lock.json
package.json

`flatbuffers` are no more used anywhere.
This commit removes `flatbuffers` from `package.json`.

Remove flatbuffers from package.json

---

src/OneExplorer/ArtifactLocator.ts

Let's check if the directory path given to LocatorRunner.run()
is absolute path or not.
---
From #1064 
By adding some unit test, it's found out that the logic only allows absolute path.
Let's specify this restriction in the code.

[OneExplorer] Throw non-absolute path from LocatorRunner

---

media/Mondrian/mondrianViewer.js

This commit modifies status line output format with the following upgrades:
* Trim very long origin names to the maximum of 32 characters
* Display block lifetime using `alive_from -> alive_till (total size)` format.
ONE-vscode-DCO-1.0-Signed-off-by: Alexander Moiseev <a.moiseev@samsung.com>

[Mondrian] Update status line info format

---

src/CircleGraph/CircleGraph.ts
src/CircleGraph/CircleGraphCtrl.ts
src/CircleGraph/CircleViewer.ts

[CircleGraph] Exclude UI related codes from coverage analysis

---

src/Tests/OneExplorer/ArtifactLocator.test.ts

This commit adds ArtifactLocator unit tests.
----
Waiting for https://github.com/Samsung/ONE-vscode/pull/1062
Waiting for https://github.com/Samsung/ONE-vscode/pull/1074
Waiting for #1079

[OneExplorer] Add ArtifactLocator unit tests

---

src/OneExplorer/OneExplorer.ts

`canHide` is `boolean` and thus `false` has same effect with `canHide?`.
Let's use default value for function parameter to be more evident.

[OneExplorer] Use default value for function parameter

---

src/OneExplorer/OneExplorer.ts
src/OneExplorer/OneccRunner.ts

[OneExplorer] Exclude UI related codes from coverage analysis

---

package.json

External open source codes are hard to be managed about to code quality.

Exclude external open source from coverage analysis

---

src/Project/Job.ts
src/Project/JobBase.ts
src/Project/JobCommand.ts
src/Project/JobConfig.ts
src/Project/JobRunner.ts

This commit adds `isCancelable` option to Job interface
to remove the dependency with JobConfig class in Job codes.
Related issue: #1080

[Project] Add isCancelable option to Job interface

---

src/Backend/Backend.ts
src/Tests/Backend/Backend.test.ts
src/Tests/Execute/InferenceQuickInput.test.ts
src/Tests/Execute/InferenceRunner.test.ts

For [#1094 ](https://github.com/Samsung/ONE-vscode/pull/1094#discussion_r928561673)
This commit will add `executors()` on `Backend`.

[Backend] Add `executors()` API on `Backend`.

---

src/Mondrian/MondrianEditor.ts

[Mondrian] Exclude UI related codes from coverage analysis

---

res/script/sdbSpecList.sh
script/sdbSpecList.sh
src/Backend/Spec.ts
src/Tests/Backend/Spec.test.ts

This commit revisit `sdbSpec` to use script file.
As `spawnsync()` with `shell: false` could not execute piped command, using `&&` or `|`.

[Spec] revisit sdbSpec

---

package.json

This commit provides welcome guide via ONE view container.
OneExplorerView shows the brief description about one-explorer-view,
and guide to open a workspace which includes model files and `cfg`s.
If no backend toolchain is registered, toolchainView's welcome page
leads the user to register or install toolchain.
---
1. The link to our document will be updated after introducing better README. (since json doesn't support comment, I couldn't add todo)
2. Toolchain timing issue (https://github.com/Samsung/ONE-vscode/issues/932#issuecomment-1181320311) will be resolved in near future.

Provide welcome guide via ONE view container

---

src/View/InstallQuickInput.ts

This commit adds `No available toolchain version` message when there is
no available toolchain to install.
Related PR: #1088

[Toolchain] Add no available version message to install quick input

---

src/Backend/API.ts

This commit refreshes toolchainView after backend registraion to prevent
showing empty toolchainView tree.
---
This will resolve `ONE-vscode` extension and backend extension timing issue. (from https://github.com/Samsung/ONE-vscode/issues/932#issuecomment-1182658014)

Refresh toolchain View after backend registraion

---

package.json

There was a button for switching editor for cfg file.
But as the button is hard to be implemented now,
this commit removes the button not to cause unnecessary confusionfor users.

[CfgEditor] Remove NYI button

---

package.json
src/OneExplorer/OneExplorer.ts

This commit introduce hide command and button.
The nodes with canHide set as true are going to be hiden and unhiden by the toggle button
-----
For #1061

[OneExplorer] Introduce hide command and button

---

media/CfgEditor/index.js

Until now, text field was added by `change` event type.
As a result, the value of the text field was applied after focused out.
This commit fixes to be applied right away with `input` event type.

[CfgEditor] Change event type for text field

---

src/OneExplorer/OneExplorer.ts
src/Utils/Helpers.ts

Currently `obtainWorkspaceRoot` log is `info` log and we see this log too much.
Let's change this log to debug log.
Also, let's log workspace info once when One Explorer View is initialized.

Change `obtainWorkspaceRoot` log to debug log

---

src/PartEditor/PartEditor.ts
src/PartEditor/PartGraphSelector.ts

[PartEditor] Exclude UI related codes from coverage analysis

---

src/CfgEditor/CfgData.ts
src/Tests/CfgEditor/CfgData.test.ts

Behavior of `resolveDeprecated` function was different for `one-build` and `input_dtype`.
This commit fixes the error with negative TCs.

[CfgEditor] Fix resolveDeprecated function with negative TC

---

src/Tests/Backend/Toolchain.test.ts

This commit adds dummy toolchain unit tests.

[Backend] Add dummy toolchain unit tests

---

src/Tests/Backend/Compiler.test.ts

This cocmmit adds dummy CompilerBase unit tests.

[Backend] Add dummy CompilerBase unit tests

---

src/Tests/Backend/Executor.test.ts

This commit adds dummy ExecutorBase unit tests.

[Backend] Add dummy ExecutorBase unit tests

---

media/Mondrian/mondrianViewer.js
media/Mondrian/style.css
src/Mondrian/MondrianEditor.ts

This commit introduces on-click side panel UI, which can show longer origin names using resizable text area and provide means to select and copy allocation info. Side panels hides automatically when user clicks on empty area in memory viewer.
ONE-vscode-DCO-1.0-Signed-off-by: Alexander Moiseev <a.moiseev@samsung.com>

[Mondrian] Add on-click side panel with allocation info

---

package.json
src/Job/JobRunner.ts

This commit add `when clause context` related to job running status.
This context shows and hides toolchain related buttons and command.

[Job] Add context related to job running status

---

src/Job/JobRunner.ts

This commit uses logger instead of Balloon.
The information messages depend on the requested job.
So it is better to handle the message where it is requested.

[Job] Use logger instead of Balloon

---

src/Jsontracer.ts
src/Jsontracer/GetWebviewOptions.ts

[Jsontracer] Exclude UI related codes from coverage analysis

---

src/Job/ToolRunner.ts
src/Tests/Utils/PipedSpawn.test.ts
src/Utils/PipedSpawn.ts

This removes `spawn(.., shell:true)` by introducing
a new function `pipedSpawn(..)`.
For #988

Remove `spawn(.., shell:true)`

---

src/Tests/Utils/Logger.test.ts
src/Utils/Balloon.ts
src/Utils/Logger.ts
src/Utils/MultiStepInput.ts

This adds unit tests for 'Utils' and put `/* istanbul ignore next */` for GUI related code.
While adding unit tests, I found two more things and fixed them:
1. Logger needs to be enhanced for handing `Error` input and `object` input.
2. Extract `_logStr()` function for unit test.

Revise Utils with more unittest cases

---

src/Tests/Utils/PipedSpawn.test.ts

This removes one pipedSpawn unit test which sometimes make CI fail.
Failed CI: https://github.com/Samsung/ONE-vscode/runs/7671212387?check_suite_focus=true

Remove one pipedSpawn unit test

---

src/Tests/Toolchain/JobConfig.test.ts
src/Tests/Toolchain/JobInstall.test.ts
src/Tests/Toolchain/JobUninstall.test.ts

This commit uses Toolchain test suite name in JobConfig, JobInstall, and
JobUninstall tests.
- Add isCancelable related assertion in JobConfig tests
Draft PR: #1148

[Toolchain] Use Toolchain suite name

---

src/Tests/Backend/Version.test.ts

This commit adds more testcases for `Version`.

[Backend] Add more testcases for Version

---

src/Tests/Utils/PipedSpawn.test.ts

This renames wrong name of two negative tests.

Rename wrong name of two negative tests

---

src/Tests/Toolchain/JobPrerequisites.test.ts

This commit adds JobPrerequisites test cases.
Draft pr: #1148

[Toolchain] Add JobPrerequisites test cases

---

src/Job/ToolRunner.ts
src/Tests/MockCompiler.ts
src/Tests/MockJob.ts
src/Tests/Toolchain/ToolchainEnv.test.ts
src/Toolchain/ToolchainEnv.ts

This commit adds ToolchainEnv test cases.
- Add Error handler on ToolRunner
- Support multiple toolchain types in MockCompiler
- Add MockJob and MockFailedJob
Draft PR: #1148

[Toolchain] Add ToolchainEnv test cases

---

src/Job/ToolRunner.ts

This commit removes unset userpassword code in child process's exit
function. This password can be used again even after one job is
finished. For example, uninstall and install are executed in one
workflow. So it should not delete the user password just because
one job is finished.

[Toolchain] Remove unset userpassword in child process's exit function

---

README.md
docs/Tutorial.md
package.json
src/Toolchain/DefaultToolchain.ts

This adds link to installation and tutorial document into README.md.
I renamed HowToUse.md to Tutorial.md.
Note: Installation and tutorial document will be revised later.

Modify README.md and HowToUse.md

---

src/Tests/Backend/Command.test.ts
src/Tests/Backend/Compiler.test.ts
src/Tests/Backend/Executor.test.ts
src/Tests/Backend/Spec.test.ts
src/Tests/Backend/Toolchain.test.ts
src/Tests/Backend/ToolchainImpl/DebianToolchain.test.ts
src/Tests/Backend/Version.test.ts
src/Tests/Execute/Device.test.ts
src/Tests/Job/Workflow.test.ts
src/Tests/Toolchain/JobConfig.test.ts
src/Tests/Toolchain/JobInstall.test.ts
src/Tests/Toolchain/JobPrerequisites.test.ts
src/Tests/Toolchain/JobUninstall.test.ts

This commit fixes following trivial mistakes.
- Fix `contructor` to `constructor`
- Add `test` to `suite` only test cases

[Tests] Fix trivial mistakes

---

src/Tests/View/InstallQuickInput.test.ts

This commit adds more negative TCs for `InstallQuickInput`.

[View] Add more negative TCs for InstallQuickInput

---

src/Mondrian/MondrianEditor.ts
src/extension.ts

This commit tidies registration of MondrianEditorProvider.
----
- For #1167

[Mondrian] Tidy registration

---

package.json
src/CfgEditor/CfgEditorPanel.ts
src/CircleGraph/CircleViewer.ts
src/Jsontracer.ts
src/Mondrian/MondrianEditor.ts
src/OneExplorer/ConfigObject.ts
src/OneExplorer/OneExplorer.ts
src/PartEditor/PartEditor.ts
src/extension.ts

This commit formats custom editor view types with prefixes:
one.editor.* (for editors)
one.viewer.* (for viewers, without editing functionality)
---
For #1165
> 
> ## Targets
> 
> current name | suggestion | type
> ---|---|---
> onevscode.mondrianViewer | one.viewer.mondrian | viewType
> onevscode.part-editor | one.editor.part | viewType
> onevscode.circleViewer | one.viewer.circle | viewType
> cfg.editor | one.editor.cfg | viewType
> JsonTracer | one.viewer.jsontrace | viewType
> one.viewer.jsonTracer | one.viewer.jsontrace.open | comnmand (not a viewtype, open command for the panel)

Format custom editor view types

---

package.json

This hides the following from command palette (`ctrl-shift-p`) just like vwe already did for `one.toolchain.uninstall`.
- `one.toolchain.install`
- `one.toolchain.refresh`

Hide one.toolchain.{install,refresh} from cmd palette

---

media/Jsontracer/index.js
src/Jsontracer/JsonTracerViewerPanel.ts

Until now, json content is not loaded initially, especially in remote-ssh environment.
It was because displaying json request is done even before all the elements are not ready.
This commit will fix it to request displaying json content after all the elements are ready.

[Jsontracer] Fix to display json content initially

---

src/Backend/ToolchainImpl/DebianToolchain.ts
src/Tests/Backend/ToolchainImpl/DebianToolchain.test.ts

This fixes the args of aptitude.
(This fixes an erroneous situation where some toolchain cannot be installed.)
1. Split `"-o Aptitude::..."` into `"-o"`, `"Aptutude::..."`
2. Since we don't use `shell:true`, remove shell metachars
`SolutionCost='100*cancel-..removals'` to
`SolutionCost=100*cancel-..removals` (without `'`)

Fix args of aptitude

---

src/Toolchain/ToolchainProvider.ts

This commit adds return statement if a toolchain is not installed.

[Toolchain] Add return statement in installation process

---

src/Tests/Utils/Helpers.test.ts
src/Utils/Helpers.ts

This commit revises following things.
- Remove unused function
- Add more negative test cases

[Tests/Utils] Revise test cases

---

src/Toolchain/ToolchainProvider.ts

This commit refreshes the device view when toolchain is installed or
uninstalled.

[Toolchain] Refresh device view when toolchain is updated

---

README.md

This removes a wrong link in README.md and
add more description about Tutorial.md.

Remove wrong link in README.md

---

src/OneExplorer/ConfigObject.ts
src/OneExplorer/OneExplorer.ts

This commit fixes the bug of not showing the trace result automatically,
but only after refreshing the view, if the profiling took long.
---
Thanks for the report @jyoungyun 😄

[OneExplorer] Fix the bug of not showing trace result immediately

---

src/OneExplorer/OneExplorer.ts

This commit fixes the bug of deleting file not working in ssh-remote env.
It fixes:
- remove undefined operator '? :', it's only for cpp
- do not use 'useTrash' option if it's ssh-remote env. With the option, the entire deletion command fails.

[OneExplorer] Fix the bug of delete command in ssh-remote env

---

src/OneExplorer/OneExplorer.ts

`refresh()` was sometimes called after `rename(...)` is not yet finished.
This commit fixes it by using then phrase.

[OneExplorer] Fix to use then phrase

---

src/OneExplorer/OneExplorer.ts

This commit changes ONE Explorer's file watcher to watch all files
to watch directories too.
-----
For #1217 
/cc @hyunsik-yoon @llFreetimell

[OneExplorer] Refresh on directory deletion/move

---

package.json
src/OneExplorer/OneExplorer.ts
src/extension.ts

This commit disables and hides openContainingDirectory command based on extensionKind.
---
Waiting for #1220 
The feature is required because openContainingDirectory doesn't work in remote env.

[OneExplorer] Disable openContainingDirectory based on extensionKind

---

media/Jsontracer/index.js
media/Jsontracer/processData.js
src/Jsontracer/JsonTracerViewerPanel.ts

This commit adds `displayTimeUnit` value to DOM to fix bugs.
---
Now `ts` and `dur` values are available in `JsonTracer`!
for: #1218

[JsonTracer] Add `displayTimeUnit` to DOM

---

src/OneExplorer/OneExplorer.ts
src/OneExplorer/OneStorage.ts

This commit introduces OneStorage module which caches the storage context.
It improves ONE Explorer's latency EFFECTIVELY.
----
For #1223
Also, when we first open the ONE Explorer, it applies the same.

[OneExplorer] Introduce OneStorage to improve latency

---

package.json
src/OneExplorer/OneExplorer.ts

This commit add 'Reveal in Explorer View' command in menu.
Note that directory cannot be a target.
----
For #1234

[OneExplorer] Add 'Reveal in explorer view' command

---

package.json
src/OneExplorer/OneExplorer.ts

This commit deprecates rename command.
---
- For #1233

[OneExplorer] Deprecate rename command

---

src/OneExplorer/OneExplorer.ts
src/Tests/OneExplorer/OneExplorer.test.ts

This commit is not to build hidden nodes.
This is required to change the OneTreeDataProvider's element type from OneNode to Node.
The provider will expect every nodes to be correspond to OneNodes, which is a visible tree item.
----
From #1247

[OneExplorer] Do not build hidden nodes

---

src/OneExplorer/OneExplorer.ts
src/Tests/OneExplorer/OneExplorer.test.ts

This commit makes OneExplorer to build children on demand.
It means, OneExplorer do not know if the node has any children until users click the node to expand.
When users click nodes, then it builds the children nodes.
The latency improvement is expected.
NOTE
As baseModel nodes and config nodes need to know its children count,
they build their children one-level earlier.
But they don't build the tree until the leaf nodes,
so the 'on-demand' concept still works on them.
----
Waiting for #1248 to be merged
From #1247

[OneExplorer] Build children on demand 

---

src/OneExplorer/OneExplorer.ts

This commit builds child nodes on demand.
It includes
- Change OneTreeDataProvider into type of TreeDataProvider<Node> instead of <OneNode>
- OneNode is a TreeItem, which is a representation node
- Node is an 'element', which is a core data structure
- TreeDataProvider is designed to have 'element' to be 'unseen materials' and 'TreeItem' to be 'shown nodes, which is collapsible'.
To make our OneExplorer to build children only when expanding the 'TreeItem', we need to make it as a proper TreeDataProvider<Node>.
- Introduce getChildren() function which builds children on demand.
- Do not create 'hidden' extra nodes
- Change didHideExtra as static, accordingly
- Change getTree() not to build the whole tree but to obtain the root
- Move workspaceRoot-checking code inside this
- Change …

[OneExplorer] Change element type to Node from OneNode

---

src/Tests/Toolchain/ToolchainProvider.test.ts
src/Toolchain/ToolchainProvider.ts
src/Utils/Helpers.ts

This commit is to ask user to save dirty target document
before running the document as onecc config.
---
For #1236

[ToolchainProvider] Ask user to save documents before run

---

.eslintrc.json

This commit adds envs and globals to configurations to remove wrong errors.
NOTE
"node" in "env"  <-- Removes 'process' is undefined error
"mocha" in "env" <-- Removes 'test'/'suites' is undefined error
"Thenable" in "globals" <-- Removes 'Thenables' is undefined error. Thenable is defined in node_modules/@types/vscode
"NodeJS" in "gloabls" <-- Removes 'NodeJS' is undefined error. Ref https://github.com/Chatie/eslint-config/issues/45
For #1253 #587

[lint] Add envs and globals

---

.eslintrc.json
src/CfgEditor/CfgEditorPanel.ts

This commit adds "no-case-declarations" rule to our lint configuration and
fixes the errors.
----
For #1253
> 
> ### Remove no-case-declarations
> 
> https://eslint.org/docs/latest/rules/no-case-declarations
> 
> #### Why is this a problem?
> >  The reason is that the lexical declaration is visible in the entire switch block but it only gets initialized when it is assigned, which will only happen if the case where it is defined is reached.
> 
> #### Sol
> > To ensure that the lexical declaration only applies to the current case clause wrap your clauses in blocks.
> 
> 
> ### 2 Errors
> ```
> /home/dayo/git/ONE-vscode/src/CfgEditor/CfgEditorPanel.ts
>   146:11  warning  Unexpected lexical declaration in case block …
```

[lint] Remove no-case-declarations

---

.eslintrc.json
src/CircleGraph/CircleGraphCtrl.ts
src/PartEditor/PartEditor.ts

This commit adds "no-useless-escape" rule and
fixes errors accordingly.
---
From #1253
> 
> ### Remove no-useless-escape
> 
> https://eslint.org/docs/latest/rules/no-useless-escape
> 
> > Escaping non-special characters in strings, template literals, and regular expressions doesn’t have any effect
> 
> ```
> /home/dayo/git/ONE-vscode/src/CircleGraph/CircleGraphCtrl.ts
>   366:26  warning  Unnecessary escape character: \%  no-useless-escape
> 
> /home/dayo/git/ONE-vscode/src/PartEditor/PartEditor.ts
>   414:26  warning  Unnecessary escape character: \%  no-useless-escape
> 
> ✖ 2 problems (0 errors, 2 warnings)
> ```
>

[lint] Remove no-useless-escape

---

.eslintrc.json
media/CircleGraph/view.js
media/PartEditor/index.js
src/PartEditor/PartEditor.ts

This commit adds "no-prototype-builtins" rule and
fixes errors accordingly.
---
For #1253 
> 
> ### Remove no-prototype-builtins
> #### Reference
> 
> > https://eslint.org/docs/latest/rules/no-prototype-builtins
> 
> > In ECMAScript 5.1, Object.create was added, which enables the creation of objects with a specified [[Prototype]]. Object.create(null) is a common pattern used to create objects that will be used as a Map. This can lead to errors when it is assumed that objects will have properties from Object.prototype. This rule prevents calling some Object.prototype methods directly from an object.
> > 
> > Additionally, objects can have properties that shadow the builtins on Object.prototype, potentially causing …

[lint] Remove no-prototype-builtins

---

.eslintrc.json
src/View/PasswordQuickInput.ts

This commit enables 'no-control-regex' rule
and removes the errors accordingly.
---
For #1253
> 
> ### Remove no-control-regex
> 
> #### Reference
> > https://stackoverflow.com/questions/14313183/javascript-regex-how-do-i-check-if-the-string-is-ascii-only
> 
> #### Problematic lines
> 
> ```typescript
> // NOTE ASCII characters have codes ranging from u+0000 to u+007f
> function containsNonAscii(str: string): boolean {
>   return !/^[\u0000-\u007f]*$/.test(str);
> }
> ```
> 
> The line is required to check if it's an ascii, but how about checking 'printable ascii' aside from those problematic non-printables?

[lint] Remove no-control-regex

---

src/OneExplorer/OneExplorer.ts
src/Tests/OneExplorer/OneExplorer.test.ts

This commit adds parent member to Node.
This is required to implement 'reveal' in ONEExplorer. Because, ONE Explorer need to reveal it's all parent node to reveal the node consequently.
---
From #1246

[OneExplorer] Add parent to Node

---

src/Backend/Compiler.ts
src/Backend/Toolchain.ts

This commit adds underscores to unused parameters in Backend.
----
From #1261 
For #1253

[lint] Add underscores to unused parameters in Backend

---

src/CircleGraph/CircleGraph.ts
src/CircleGraph/CircleGraphCtrl.ts
src/CircleGraph/CircleViewer.ts
src/PartEditor/PartEditor.ts
src/PartEditor/PartGraphSelector.ts

This commit removes unused variables and parameters from CircleGraph and PartEditor.
----
From #1261 
For #1253

[lint] Remove unused variables from CircleGraph and PartEditor

---

src/Utils/MultiStepInput.ts

This commit removes unused generics from MultiStepInput.
----
From #1261 
For #1253

[lint] Remove unused generics from MultiStepInput

---

media/CircleGraph/index.js
media/CircleGraph/view.js
media/Mondrian/mondrianViewer.js
media/PartEditor/index.js

This commit removes unused variables from .js files.
---
For #1299 
From #1253

[lint] Remove unused variables from .js files

---

src/Tests/OneExplorer/OneStorage.test.ts

This commit revisits OneExplorer Unit Tests.
It renames the duplicated test suite and relocate the tests

[OneExplorer] Revisit OneExplorer Unit Tests

---

.eslintrc.json

This commit adds no-unused-vars rule to linter.
---
Waiting for #1274
Waiting for #1300

[lint] Add no-unused-vars rule

---

src/Backend/API.ts
src/Backend/One/OneToolchain.ts
src/Tests/Backend/Backend.test.ts
src/Tests/Backend/One/OneToolchain.test.ts

Because OneExplorer used `One` prefix, modify the file and directory name in the same format.

[OneToolchain] Change ONEToolchain and ONECompiler name

---

src/Job/Job.ts
src/Job/JobCommand.ts
src/Tests/MockJob.ts
src/Tests/Toolchain/JobConfig.test.ts
src/Tests/Toolchain/JobInstall.test.ts
src/Tests/Toolchain/JobPrerequisites.test.ts
src/Tests/Toolchain/JobUninstall.test.ts
src/Toolchain/JobConfig.ts
src/Toolchain/JobInstall.ts
src/Toolchain/JobPrerequisites.ts
src/Toolchain/JobUninstall.ts

This commit removes re-declararation of 'Job'.
To remove 're-declare' error from eslint.
---
For #1253

[lint] Remove re-declare

---

.eslintrc.json

Let's finally use eslint:recommended
NOTE 'no-undef' rule is off because the most vscode-webview's client-side codes 'document' and 'window'
---
For #1253

[lint] Use eslint:recommended

---

src/Utils/Hash.ts

This PR introduces generateHash, a function used in the process of converting a product file into a hash value. This funciton receives the model or product file's Uri and converts it to a hash value.
ONE-vscode-DCO-1.0-Signed-off-by: HyeonMyeong Jung <gandi0330@naver.com>

[Utils] Introduce Hash.ts

---

src/CircleGraph/CircleViewer.ts

Currently, `uri.path` is used for finding path.
However, it causes an error at Windows native environment. This commit fixes the error.

[CircleGraph] Fix to find file system path

---

script/prerequisitesForGetToolchains.sh

This commit returns the output value as it is.
This allows the log to be displayed and the output to be handled.
~~fix this bug: https://github.com/Samsung/ONE-vscode/pull/1333#issuecomment-1268162214, #1335~~

[OneToolchain] Returns the output value as it is

---

src/Tests/Utils/Helpers.test.ts

This commit adds unit test for isOneExplorerTargetFile() in Helpers.ts
ONE-vscode-DCO-1.0-Signed-off-by: HyeonMyeong Jung <gandi0330@naver.com>

[Test] Add unit test for isTargetFile

---

src/CircleEditor/CircleEditorDocument.ts
src/CircleEditor/CircleEditorProvider.ts
src/CircleEditor/CircleType.ts

this commit adds
- edit tensor's data logic.
- edit attribute's data logic about built-in and custom operator.
- send value's type of custom operator.
- send encoding data about key and value of custom operator.
ONE-vscode-DCO-1.0-Signed-off-by: Hyeonwoo Yu <dbgusdn98@naver.com>
---
Related issue : #1269

[CircleEditor] Add edit & send logic.

---

src/Tests/Utils/Hash.test.ts

This commit adds missing assert in test case for `Utils/Hash`.

[Tests/Utils] Add missing assert

---

src/CircleGraph/CircleGraphCtrl.ts

This will relocate onDidReceiveMessage handlers.

[CircleGraphCtrl] Relocate handlers

---

package.json
src/OneExplorer/OneExplorer.ts

This commit revives rename command which is deprecated by #1243.
---
FOR REVIEWERS,
This is a baseline for 'Cfg Refactoring' feature, which replaces input_file names with the new one when the mode file name is changed.
For #1359
NOTE That the behavior is the same as before, it's just a revival of the same old 'rename' command.

[OneExplorer] Revive rename command

---

src/MetadataManager/Metadata.ts

`getObj` function in `Metadata` was not returning consistent type. This commit will fix it.

[MetadataManager] Return consistent type

---

src/Utils/Helpers.ts

`filter` function for array type should return boolean values. This commit will fix it.

[Utils] Fix wrong return type for filter function

---

.vscode/extensions.json

This commit adds xaver.clang-format as a recommended extension for a workspace.
ONE-vscode-DCO-1.0-Signed-off-by: Changho Shin <chshin59@gmail.com>

[vscode] Add a recommended extension for a workspace

---

package.json
src/OneExplorer/OneExplorer.ts

This commit allows rename command only for config files. By this, base model and products renaming is restricted
and it will be replaced with 'Refactoring' command.
This commit also include some code cleanings.
----
FOR REVIEWERS,
This commit is from discussion https://github.com/Samsung/ONE-vscode/pull/1361
It's decided to enable rename command only for config files,
and support refactoring command for other files.

[OneExplorer] Allow rename command only for config files

---

src/Backend/One/OneToolchain.ts
src/Tests/Backend/One/OneToolchain.test.ts

The execSync has a security issue.
This PR modifies execSync to spawnSync and PipedSpawnSync.
draftpr: #1329

[OneToolchain] Use spawnsync instead of execSync

---

.ahub/sam/exclude.txt

This commit adds `media/CircleEditor/external` directory to excluding list.

[CircleEditor] Add external directory to excluding list

---

src/MetadataManager/PathToHash.ts

`forEach` function requires a function who returns `void`. This commit will fix it.

[MetadataManager] Fix incorrect return type for callback function

---

media/CircleGraph/index.js

This commit enables filtering properties in for-in loop by if statement, using `Object.prototype.hasOwnProperty.call`.
---
This is to resolve static analysis warning, which is https://rules.sonarsource.com/javascript/RSPEC-1535.
Only `if` statements are added, and logic itself is not changed.

[CircleGraph] Filter properties in for-in loop

---

package.json
src/OneExplorer/OneExplorer.ts

This commit enables refactoring by renaming,
so that the model file renaming can be automatically applied to related
config files.
It renames all the changed model file names in children config files.
----
Waiting for #1388 to be merged
For #768
NOTE: Command name is changed from `Refactor` to `Rename Model` after taking this video.

[OneExplorer] Support refactoring by renaming

---

src/OneExplorer/OneExplorer.ts

This commit removes the stage of pre-building a node map on the beginning. _nodeMap will collect the path-to-node relation when getTreeItem() is called, which is a function called when the node is shown on the view.
---
From #1402

[OneExplorer] Build a node map on demand

---

src/OneExplorer/OneExplorer.ts
src/OneExplorer/OneStorage.ts
src/Tests/OneExplorer/OneExplorer.test.ts

This commit removes unused function getCfgList().
It's been replaced with OneStorage class's other functions and it's not used anywhere now.

[OneExplorer] Remove unused getCfgList()

---

src/OneExplorer/OneExplorer.ts
src/OneExplorer/OneStorage.ts

This commit revises refresh command and make it more efficient
to re-build only the changed node.
---
From #1402

[OneExplorer] Revise Refresh to re-build only the changed node

---

src/Toolchain/ToolchainProvider.ts

This commit does not return undefined type in Toolchain Provider file.

[Toolchain] Do not return undefined type in ToolchainProvider

---

src/Utils/Helpers.ts

This commit rewrites obtainWorkspaceRoot.
It fixes the bug of throwing unknown error by accessing workspaceFolders[0].uri.path when worksapceFolder is an empty array but not undefined.
---
For #1419

[Helpers] Fix obtainWorkspaceRoot

---

src/OneExplorer/OneExplorer.ts
src/Utils/Helpers.ts

This commit simplifies the error handling logic
when ONE Explorer sets workspace root.
---
For #1419

[OneExplorer] Simplify getting workspaceRoot 

---

src/Utils/Helpers.ts

This commit introduces obtainsWorkspaceRoots() function which returns a list of workspace roots.
It's a helper to support multiple workspaces to be shown in ONE Explorer.
---
For #1419

[Utils] Introduce obtainWorkspaceRoots

---

src/OneExplorer/OneExplorer.ts
src/Tests/OneExplorer/OneExplorer.test.ts

This commit shows parent directory path as description,
to let user notice the file's real path at once.
---
--- 
Waiting for #1419 to be merged

[OneExplorer] Show full path in description

---

src/OneExplorer/OneExplorer.ts

This commit removes redundant refresh.
When any file system changes occurs, the change will be handled by event listeners.

[OneExplorer] Remove redundant refresh

---

.github/workflows/check-commit.yml
.github/workflows/check-copyright.yml
.github/workflows/check-license.yml

This commit substitute `pull_request_target` with `pull_request`.

[CI] Use pull_request instead of pull_request_target

---

.github/workflows/check-license.yml

Until now, CI did not fail even when license verification is failed. It was because maintainers can judge the result by comment. However, as result of license verification is not created anymore, it is better for CI to fail when the verification is failed.

[CI] Make CI fail when license verification is failed

---

src/OneExplorer/OneExplorer.ts

This commit fixes the disposable registrations in OneTreeDataProvider.
ONE-vscode-DCO-1.0-Signed-off-by: Dayoung.lee <dayoung.lee@samsung.com>

[OneExplorer] Subscribe omitted disposables

---

src/OneExplorer/OneExplorer.ts

This commit is to use chai instead of assert.

[OneExplorer] Use chai instead of assert

---

src/OneExplorer/OneExplorer.ts

This commit adds id to Node class.
`id` is a member variable kept by TreeItem,
which makes it possible to keep existing node when its name is changed.
---
For #1422

[OneExplorer] Add id to Node

---

src/OneExplorer/OneExplorer.ts

This commit revisits NodeFactory.create
- BUG FIX: It fixes a possible bug of hide & show.
If onecc was run in hide mode, the extra files would have never shown.
Let's fix it by removing this redundant legacy codes.
- CLEANING: It uses switch-case instead of if statement
---
Related to #1435 (This should have been applied with the PR)

[OneExplorer] Revisit NodeFactory.create

---

src/OneExplorer/OneExplorer.ts
src/OneExplorer/OneStorage.ts

This commit refactors OneExplorer by relocating _nodeMap into OneStorage.

[OneExplorer] Move _nodeMap to OneStorage

---

src/OneExplorer/OneStorage.ts

This commit removes null type from ConfigObjMap's value. Let's return undefined when the key is not found,
as the same as the other maps do.
---
From #1446

[OneStorage] Clarify ConfigObjMaps value

---

src/OneExplorer/OneStorage.ts

This commit renames _initCfgList to _getCfgList.
because it doesn't keep the cfglist and just use and dispose it.
---
From #1446

[OneStorage] Rename function

---

src/OneExplorer/ArtifactLocator.ts

This commit fixes typo in comments.
- input_file->input_path
- output_file->output_path.

[OneExplorer] Fix comment

---

src/Tests/OneExplorer/ConfigObject.test.ts
src/Tests/OneExplorer/OneExplorer.test.ts
src/Tests/OneExplorer/OneStorage.test.ts

This commit clarifies the OneExplorer unit tests by
(1) elaborate `create a base model` test.
(2) Add isDefined checker to easily notice undefined objects
(3) Replace `?` with `!` to assert unexpected undefined objects

[OneExplorer/Test] Clarify tests

---

src/OneExplorer/OneStorage.ts
src/Tests/OneExplorer/OneStorage.test.ts

This commit refactors OneStorage class
to divide its functionalities into CfgToCfgObjMap and BaseModelToCfgMap.
It includes unit tests.
----
Related to #1442
From #1446
Waiting for #1452

[OneExplorer] Introduce BaseModelToCfgMap/CfgToCfgObjMap

---

src/OneExplorer/ArtifactLocator.ts
src/OneExplorer/ConfigObject.ts
src/OneExplorer/OneExplorer.ts
src/OneExplorer/OneStorage.ts

This commit fixes trivial typos in src/OneExplorer directory.

[OneExplorer] Fix trivial typos

---

src/OneExplorer/OneExplorer.ts
src/OneExplorer/OneStorage.ts
src/Tests/MockCompiler.ts

This commit reverts "[OneExplorer] Use chai instead of assert (#1441)" and similar changes. 'chai' doesn't turn off at release mode, so it MUST NOT BE USED IN PRODUCT CODE.
---
For #1463

Remove chai from product code

---

src/OneExplorer/OneExplorer.ts

This change includes a TreeView into TreeDataProvider. This enables ONE Tree to use 'reveal node' command provided by TreeView instance.
---
For #1465

[OneExplorer] Add reveal function

---

src/OneExplorer/ArtifactLocator.ts
src/Tests/OneExplorer/ConfigObject.test.ts
src/Tests/OneExplorer/OneStorage.test.ts

This commit fixes ArtifactLocator not to parse wrongly formatted ini file.
For example,
>
>  [one-import-tflite]
>  input_path="model.tflite"
This is parsed by python 'ini' module as
[one-import-tflite]=true
...

[OneExplorer] Fix ArtifactLocator

---

src/Backend/One/OneToolchain.ts

This commit removes the package name from the apt-cache result.
Installation fails indefinitely due to an unexpected package name.

[Toolchain] Fix the problem of one toolchain installation failure

---

src/Tests/OneExplorer/OneStorage.test.ts

This commit inserts OneStorage.reset() if a test case includes any file system change.
OneStorage's singleton instance reflects the filesystem context at the time it is first referred.
Therefore, to update OneStorage instance, OneStorage.reset() must be called after the writeFileSync in test.
Then, how come those tests passed so far? One possible guess is that Github Action's runner somehow keeps previous test's filesystem,
so that those tests have been randomly succeeded.
Let's fix the test.

[OneStorage] Fix unit tests

---

.github/workflows/build-release.yml
.github/workflows/check-commit.yml
.github/workflows/check-copyright.yml
.github/workflows/check-daily-license.yml
.github/workflows/check-license.yml
.github/workflows/check-pr-format.yml
.github/workflows/check-pr-test.yml
.github/workflows/check-pr-tsc.yml
.github/workflows/publish-extension.yml

This commit uses checkout v3 and setup-node v3 by default in GitHub Actions workflows. The Node.js 12 actions are deprecated. The checkout v3 and setup-node v3 use Node.js 16.

[ci] Use node16 by default in GitHub Actions

---

.github/workflows/build-release.yml
.github/workflows/nightly-release.yml
.github/workflows/publish-extension.yml

This commit change publish-extension to reusable workflow. And it introduces nightly-release for nightly build on behalf of publish-extension.

[ci] Apply reusable workflow in release workflows

---

.github/workflows/build-release.yml
.github/workflows/publish-extension.yml

This commit publishes vsix extension file to marketplace with Samsung Publisher in Official release workflow.
This job requires VSCE_PAT secret environment variable.
Related issue: #1473 
Draft workflow: https://github.com/jyoungyun/vscode-test/actions/runs/3938041397/jobs/6736269110

[ci] Publish extension to marketplace in official release workflow

---

.github/workflows/official-release.yml

This commit changes the build-release workflow name to official-release workflow.

[ci] Change the build-release workflow name

---

package-lock.json
package.json

VSCode supports pre-release versions of extensions since v1.63.0. So this commit changes the version of vscode engine to v1.63.0.

[ci] Version up the vscode engine to v1.63.0

---

package.json
src/OneExplorer/OneExplorer.ts

This commit implements configuration run by  'Ctrl+F7' shortcut.
Issue: #1488
ONE-DCO-1.0-Signed-off-by: s.malakhov <s.malakhov@partner.samsung.com>

[OneExplorer] Implement configuration run by Ctrl+F7

---

infra/format

This will tidy unused clang-format related in format tool.

Tidy using clang-format

---

media/CircleGraph/view-sidebar.js

This will let prettier ignore previous code of view-sidebar.js without formatting for better readability.

[CircleGraph] Use prettier ignore view-sidebar.js

---

media/CfgEditor/index.js
package.json
src/CfgEditor/CfgEditorPanel.ts

This commit fills .cfg paramters by default values using keyboard shortcut.
This commit fills default values in .cfg file (input and output paths for import/optimization/quantization).
Currently its optimal usage would be:
1) create new configuration
2) check needful steps 
3) press 'ctrl+shift +/' for filling .cfg parameters to default values. ('ctrl+d' is busy)
Issue: #1487

[CfgEditor] Fill .cfg parameters  by default values

---

media/MPQEditor/index.html
media/MPQEditor/index.js
media/MPQEditor/style.css

This commit introduces 'media'  for MPQEditor.
Draft: #1505
Related: #1491

[MPQEditor] Introduce 'media' for MPQEditor

---

src/Tests/MPQEditor/MPQData.test.ts

This commit fixes suite naming to make it consistent with tests for another  modules (see https://github.com/Samsung/ONE-vscode/pull/1516#discussion_r1155779204).

[MPQEditor] Fix suite naming

---

src/MPQEditor/MPQEditor.ts
src/Tests/MPQEditor/MPQEditor.test.ts

This commit implements 'validateMPQName' and adds tests for it.

[MPQEditor] Implement 'validateMPQName'

---

src/MPQEditor/MPQEditor.ts
src/Tests/MPQEditor/MPQEditor.test.ts

This commit implements 'findMPQName' and adds tests for it.

[MPQEditor] Implement 'findMPQName'

---

src/MPQEditor/MPQEditor.ts
src/Tests/MPQEditor/MPQEditor.test.ts

This commit implements 'createDefaultMPQ' and adds tests for it.

[MPQEditor] Implement 'createDefaultMPQ'

---

src/MPQEditor/MPQEditor.ts
src/Tests/MPQEditor/MPQEditor.test.ts

This commit implements 'updateDocumentBy' and adds tests for it.

[MPQEditor] Implement 'updateDocumentBy'

---

src/MPQEditor/MPQEditor.ts

This commit implements 'createMPQJson' for creation/editing default mpq file.
I've checked its validity in the draft #1511. Please see https://github.com/Samsung/ONE-vscode/pull/1511#issue-1642481493 for its correctness.

[MPQEditor] Implement 'createMPQJson'

---

src/MPQEditor/MPQEditor.ts

This commit implements providing model nodes info.

[MPQEditor] Implement providing model nodes info.

---

src/MPQEditor/MPQEditor.ts

This commit implements message processing.
Its correctness is tested in https://github.com/Samsung/ONE-vscode/pull/1511.

[MPQEditor] Implement message processing

---

src/MPQEditor/MPQEditor.ts

This commit implements createFromDefaultExplorer command for manual mixed precision task.
Its correctness is tested in https://github.com/Samsung/ONE-vscode/pull/1511.

[MPQEditor] Implement createFromDefaultExplorer

---

package.json

This commit registers *.mpq.json and showFromDefaultExplorer for  mpq editor.
Its correctness is tested in https://github.com/Samsung/ONE-vscode/pull/1511.

Register mpq editor

---

src/MPQEditor/MPQCircleSelector.ts

This commit introduces MPQSelectionPanel for manual mixed precision quantization task.

[MPQEditor] IntroduceMPQSelectionPanel

---

media/MPQEditor/index.html
media/MPQEditor/index.js
media/MPQEditor/style.css

This commit implements media changes for 'Show graph'.
Its correctness is tested in #1530
Fresh draft: #1530
Full draft: #1505

[MPQEditor] Implement media for 'Show graph'

---

src/MPQEditor/MPQCircleSelector.ts

This commit implements 'constructor' of MPQSelectionPanel.

[MPQEditor] Implement constructor

---

src/MPQEditor/MPQCircleSelector.ts

This commit implements 'createOrShow' along with needful functions for it.

[MPQEditor] Implement 'createOrShow'

---

src/MPQEditor/MPQCircleSelector.ts

This commit implements open and other commands for MPQSelectionPanel.

[MPQEditor] Implement open and other commands

---

src/MPQEditor/MPQEditor.ts

This commit implements usage of  MPQCircleSelector for manual mixed precision quantization task.

[MPQEditor] Use MPQCircleSelector

---

src/MPQEditor/MPQCircleSelector.ts

This commit implements 'dispose' and 'onViewMessage' for manual mixed precision quantization task.

[MPQEditor] Implement 'dispose' and 'onViewMessage'

---

src/CircleGraph/CircleGraphCtrl.ts

This commit introduces 'scrollToSelected' message.

[CircleGraph] Introduce 'scrollToSelected' message

---

src/MPQEditor/MPQData.ts

This commit updates MPQData for handling visq path.

[MPQEditor] Update MPQData for visq path.

---

media/MPQEditor/index.html
media/MPQEditor/index.js
media/MPQEditor/style.css

This commit implements mpqeditor media changes for showing VISQ data for MPQ.

[MPQEditor] Implement media for VISQ

---

media/CircleGraph/index.js
media/CircleGraph/view.js

This commit implements visqselector mode and managing of scrollToSlected.

[CircleGraph] Implement visqselector mode

---

src/MPQEditor/MPQEditor.ts

This commit implements 'removeVisqFile' and 'VisqInputPathChanged' messages.

[MPQEditor] Implement UI messages

---

src/MPQEditor/MPQCircleSelector.ts

This commit updates MPQCircleSelector for visq processing.

[MPQEditor] Update MPQCircleSelector for visq processing

---

src/MPQEditor/MPQCircleSelector.ts

This commit implements 'cancelScrollToSelected' and uses it to prevent the view from scrolling after every user selection.
See related https://github.com/Samsung/ONE-vscode/pull/1505#issuecomment-1453488864.

[MPQEditor] Implement 'cancelScrollToSelected'

---

package.json
src/Backend/One/OneToolchain.ts

In some environments, a GitHub Token is required to access the one-compiler release page. It adds a property for GitHub Token and use it when onecc-docker tool is executed.
Related issue: #1553

[ONEToolchain] Use user github token in ONE Toolchain

---

src/MPQEditor/MPQEditor.ts

This commit implements processing of 'loadVisqFile' message and 'showVisqCircleModelGraph' function needed for that.

[MPQEditor] Implement `handleLoadVisqFile`

---

src/MPQEditor/MPQCircleSelector.ts
src/MPQEditor/MPQEditor.ts

This commit implements handling of invalid VISQ file.
It's correctness is approved below:
https://github.com/Samsung/ONE-vscode/assets/112689352/d5405007-5db1-4fe4-aa91-5ad93be43ce4

[MPQEditor] Handle invalid VISQ data

---

src/Job/Job.ts
src/Job/JobRunner.ts
src/Job/ToolRunner.ts

This commit introduces the stdout result variable to JobRunner. If the tool runner succeeds in executing the command, the stdout result is passed to the JobRunner.

Introduce stdout result variable in JobRunner

---

package.json

This commit uses a free server number, starting to 44. Sometimes the 44 server number is not available to run xvfb-run tool. It solves this issue.

Use a free server number in npm test-no-screen command

---

src/Toolchain/ToolchainProvider.ts

This commit introduces checkAvailableToolchain in ToolchainProvider.
Related draft: #1570
I'm not sure whether this PR is passing CI checkers because there is nowhere to use this function.....

[Toolchain] Introduce checkAvailableToolchain

---

src/Tests/Toolchain/ToolchainEnv.test.ts
src/Toolchain/ToolchainEnv.ts

This commit implements getModelInfo() in ToolchainEnv.

[Toolchain] Implement getModelInfo in ToolchainEnv

---

src/Tests/Toolchain/ToolchainEnv.test.ts
src/Toolchain/ToolchainEnv.ts

This commit changes inference() to infer().

[Toolchain] Change inference function name

---

package.json
src/Tests/Toolchain/ToolchainProvider.test.ts
src/Toolchain/ToolchainProvider.ts

This commit implements inference function in ToolchainProvider. This function calls the inferenct function of ToolchainEnv. It also adds vscode command for inference.

[Toolchain] Implement inference in ToolchainProvider

---

package.json
src/Tests/Toolchain/ToolchainProvider.test.ts
src/Toolchain/ToolchainProvider.ts

This commit implements getModelInfo function in ToolchainProvider. This function calls the getModelInfo function in ToolchainEnv. It also adds vscode command for getModelInfo.

[Toolchain] Implement getModelInfo in ToolchainProvider

---

package.json
src/OneExplorer/OneExplorer.ts

This commit appends the extname to the contextValue. The OneExplorer does not support `resourceExtname` context key. This issue can be resolved using the extname in the contextValue.
Draft PR: #1584

[OneExplorer] Append the extname to the contextValue

---

package.json
src/OneExplorer/OneExplorer.ts

This commit fixes seperates delete and deleteOnShortcut commands. They works differently as the chosen nodes are different. 'delete' command targets the node on which it's right-clicked, whereas 'deleteOnShortcut' command target the nodes on which they're selected.
---
Resolves #1591

[OneExplorer] Seperate delete command

---

package.json
src/OneExplorer/OneExplorer.ts

This commit supports shortcut for renaming.

[OneExplorer] Add rename shortcut 

---

src/OneExplorer/OneExplorer.ts

This commit makes OneExplorer refresh only on watching files' changes.

[OneExplorer] Refresh ONLY on watching files' changes.

---

src/OneExplorer/ConfigObject.ts

This commit uses jsontracer in trace.json file.

[OneExplorer] Use jsontracer in trace.json file

---

package.json
src/Backend/One/OneToolchain.ts
src/Utils/Balloon.ts

To use ONE Toolchain, user need to set github token in vscode settings. Currently, it fails on run without token.
Let's give direction to the user explicitly.
---
For #1601

[Toolchain] Ask user to set github token

---

src/OneExplorer/OneExplorer.ts

This commit enables multiple node deletion on shortcut.

[OneExplorer] Delete multiple nodes with shortcut

---

src/MetadataManager/PathToHash.ts

This commit fixes three major defects in the module. It checks if the property exists in the for loop.
---
For #1580

Fix CQM Major defects in PathToHash

---

src/OneExplorer/OneExplorer.ts

This commit fixes 2 major defects in OneExplorer by making return type consistent.
---
For https://github.com/Samsung/ONE-vscode/issues/1580

Fix CQM Major defects in OneExplorer

---

.vscode/extensions.json

This commit removes xaver.clang-format extension from extension recommendation list.
---
From #1617

[Extension] Revisit recommendation

---

src/Utils/Logger.ts

This commit adds redact step to a Logger.
---
For #1609

[Logger] Add redact step

---

.github/workflows/check-pr-format.yml

This commit removes redundant clang-format-8 installation
---
From #1617

[Action] Remove clang-format-8 installation

---

src/Backend/API.ts
src/Tests/Backend/Backend.test.ts
src/extension.ts

This commit revisits API to split ONE-toolchain backend registration from the api itself. It aim to show the extension's api functions clearly.

[API] Clarify APIs

---

media/CircleEditor/view.js

This commit removes clang-format related dead codes.
---
From #1617

[CircleEditor] Clean dead codes

---

src/MPQEditor/MPQEditor.ts

This commit replaces 'glob.sync' with 'fs.readdirSync'.
This commit fixes #1637.
Related: #1637

[MPQEditor] Remove 'glob.sync'

---

src/Backend/API.ts
src/Tests/Backend/Backend.test.ts

This commit removes executors as they are not used anywhere.

[Backend] Remove executors

---

.ahub/sam/exclude.txt

This will excludes circle_schema_generated.ts SAM report. 
It is generated by Flatbuffers.
ONE-vscode-DCO-1.0-Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

[ahub/sam] Exclude generated code

---

package.json
src/OneExplorer/ConfigObject.ts

This commit deprecates JsonTracer and shows trace files with default text viewer.

[JsonTracer] Deprecate JsonTracer

---

src/Tests/Toolchain/ToolchainEnv.test.ts
src/Tests/Toolchain/ToolchainProvider.test.ts
src/Tests/Utils/PipedSpawnSync.test.ts

This commit removes meaningless assertions in unit tests.
---
For https://github.com/Samsung/ONE-vscode/issues/1624#issuecomment-1720965076

[Test] Remove meaningless assertions

---

src/Execute/DeviceViewProvider.ts

This commit expands node entries at HostPC parent node by default.

[Execute] Expand node entries at HostPC parent node

---

media/CircleEditor/external/circle-schema.js
src/CircleEditor/circle_schema_generated.ts

This PR will update circle-schema to version 0.6.
The `circle-schema.js` file is originally come from [netron](https://github.com/lutzroeder/netron/blob/89104391b1f2dfea9738d064339069ad1db3bd34/source/circle-schema.js).
The `circle_schema_generated.ts` file is originally come from [ONE](https://github.com/Samsung/ONE/blob/e09738db8a7f873005d26a21465dfabca12abf88/res/CircleSchema/0.6/circle_schema.fbs).
ONE-vscode-DCO-1.0-Signed-off-by: Seungho Henry Park <shs.park@samsung.com>
---
Related: #1651

[CircleEditor] Update Circle Schema

---

package.json

This commit makes our keybindings activate only when ONE Explorer is visible and no input focus.
---
For #1652

[OneExplorer] Activate keybindings with condition

---

src/Toolchain/ToolchainProvider.ts

This commit shows detailed error messages when cfg compiles.

[Toolchain] Show detailed error messages in run()

---

src/Backend/EdgeTPU/EdgeTPUToolchain.ts
src/Tests/Backend/EdgeTPU/EdgeTPUToolchain.test.ts

For #1621, #1628 
This commit adds the EdgeTPUDebianToolchain class extending DebianToolchain.
It implements the codes reading the cfg file to construct the command and uses ini, fs packages to read cfg file.
Also, This commit adds the EdgeTPUDebianToolchain.test.ts file.
It includes the codes testing if EdgeTPUDebianToolchain's run() method returns the expected Command with given absolute and relative input paths.
ONE-vscode-DCO-1.0-Signed-off-by: Bumsoo Ko <rhqjatn2398@naver.com>

[EdgeTPU] Add EdgeTPUDebianToolchain

---

src/OneExplorer/OneExplorer.ts

This commit enables OneExplorer to open tflite and onnx with embedded netron. And it also changes opening policy on *.pb. It opens pb files with default editor.

[OneExplorer] Open tflite and onnx with netron

---

src/Tests/MPQEditor/MPQEditor.test.ts
src/Tests/OneExplorer/ConfigObject.test.ts
src/Tests/OneExplorer/OneExplorer.test.ts
src/Tests/OneExplorer/OneStorage.test.ts
src/Tests/Utils/Hash.test.ts

This commit relocate teardown function down to the bottom. Currently TCM test is making mistakes of accusing teardown function of having no assertion. Let's do a workaround by relocating the lines.
---
For #1678
> ### Workaround
> 
> https://analysishub.sec.samsung.net/service/analyses/2400671
> By relocating the teardown function all the way down to the bottom, we can instantly dodge the warning.
> 
> ![image](https://github.com/Samsung/ONE-vscode/assets/17171963/2b699a24-b1f7-4a65-9dd9-8ed0a40a52fb)

[Test] Relocate teardown

---

src/Execute/DeviceViewProvider.ts
src/Tests/Execute/DeviceViewProvider.test.ts

This commit registers SimulatorDevice with Toolchain information.
It does not add device according to the DeviceSpec. All devices are
added to the DeviceManager directly.
wait for #1660

[Execute] Register SimulatorDevice with Toolchain information

---

src/Execute/DeviceViewProvider.ts

This commit uses forEach instead of Map because it does not use the return value.

[Execute] Use forEach instead of Map

---

.github/workflows/publish-extension.yml

This commit uses boolean type to process true/false value in publish extension workflow.

[workflows] Use boolean type in publish extension workflow

---

src/Tests/index.ts

This commit excludes CircleEditor and MetadataViewer from nyc test files. These modules are not an official v0.4 release features.

[Tests] Exclude CircleEditor and MetadataViewer from nyc test files

---

media/CircleGraph/view-sidebar.js

This commit fixes a constructor to return nothing consistently.
---
For https://github.com/Samsung/ONE-vscode/issues/1624#issuecomment-1720750787

[CircleGraph] Fix constructor

---

media/CfgEditor/displaycfg.js
media/CfgEditor/index.js
media/CfgEditor/updateContent.js

This commit checks properties' existence in for loop.
---
For https://github.com/Samsung/ONE-vscode/issues/1624#issuecomment-1720750787

[CfgEditor] Check properties existence in loop

---

media/CfgEditor/index.js
media/CircleEditor/index.js
media/CircleGraph/index.js
media/Jsontracer/index.js
media/MPQEditor/index.js
media/MetadataViewer/index.js
media/Mondrian/mondrianViewer.js
media/PartEditor/index.js

This commit checks origin of messages in event handlers
----
For https://github.com/Samsung/ONE-vscode/issues/1624#issuecomment-1720750787

[media] Check origin of messages

---

package.json

This commit hides commands of MetadataViewer.
Let's show the command when the whole functionality is ready.

[MetadataViewer] Hide commands

---

src/MPQEditor/MPQCircleSelector.ts
src/MPQEditor/MPQEditor.ts

This commit is to ignore provider and panel classes in TC coverage.

[MPQEditor] Ignore from Coverage

---

package.json

This commit hides mpq editor command from menu temporarily. Let's show it when it is supported in OneExplorer.

[MPQEditor] Hide from menu

---

package.json

This commit uses DEVICE view name instead of TARGET DEVICES.

[Execute] Use DEVICE view name

---

src/OneExplorer/OneStorage.ts
src/Tests/OneExplorer/OneStorage.test.ts

Let's deprecate BaseModelToCfgMap because it hinders OneStorage management while its effect is low.
---
From #1703

[OneStorage] Deprecate BaseModelToCfgMap

---

src/CfgEditor/CfgData.ts
src/CfgEditor/EdgeTPUCfgData.ts
src/CfgEditor/ICfgData.ts
src/OneExplorer/OneExplorer.ts

This PR is about extending the createCfg method for other cfg types.
I wanted to make this UI like this.
But I couldn't find this API, and this program also gets the name for the output as a `quick pick`, so I made it a `quick pick` like this.
The option '.edgetpucfg' appears only in the tflite file.
I don't think this PR is enough to modularize. So please comment about best modularizing or refactoring

[EdgeTPU] Expand createCfg method for other cfg types

---

src/Toolchain/JobConfig.ts
src/Toolchain/ToolchainEnv.ts
src/Toolchain/ToolchainProvider.ts

Modify notiTitle in JobConfig.ts from 'Running onecc...' to 'Running tools...'
Use active toolchain name in notification and log of ToolchainProvider _run method
Add notiTitle in ToolchainEnv run method to provide notification differently for each toolchain

[EdgeTPU] Update Toolchain run notification and log

---

src/OneExplorer/OneStorage.ts

This commit improves insert function to manipulate cfgToCfgObjMap too.
This way, we can refresh only related nodes in some cases.
---
~~Wait for #1700~~
Draft #1703

[OneStorage] Improve insert 

---

src/Tests/index.ts

This commit alter mocha timeout from 2000(default) to 10000 ms. It's to prevent timeout failure during test.
---
For #1706
I suspect it as a long latency problem. By rising timeout up to 10000 ms, (default: 2000 ms) the test passes at once. Maybe the CI machine sometime get slower and does not pass within the timeout. They always pass on local machine, so let's simply change the timeout.

[Test] Alter mocha timeout

---

src/OneExplorer/ConfigObject.ts
src/OneExplorer/OneExplorer.ts
src/OneExplorer/OneStorage.ts

This commit refreshs only the required nodes on change and delete file.
---
For #1422 #1501

[OneExplorer] Targeted refresh on Change/Delete

---

.eslintrc.json
infra/license/license-judgment.json
package-lock.json
package.json

This commit updates the dependency package versions.
- eslint : 7.15.0 -> 8.52.0
- vscode : 2.7.0 -> 2.21.1 The latest eslint generates more warning than before. So it temporarily turned off the options related to this.

[release/0.5.0] Update dependency package version

---

src/CfgEditor/CfgData.ts
src/CfgEditor/ICfgData.ts

This commit modularize the CfgData file for EdgeTPU.
It defines the interface named ICfgData extracted from CfgData.
ONE-vscode-DCO-1.0-Signed-off-by: Bumsoo Ko <rhqjatn2398@naver.com>

[EdgeTPU] Extract Interface for Modularization (CfgData)

---

script/prerequisitesForGetEdgeTPUToolchain.sh

This commit adds a shell script for getting prerequisties.
---
Original PR #1667

[EdgeTPU] Add shell script for the prerequisites

---

src/CfgEditor/EdgeTPUCfgData.ts
src/Tests/CfgEditor/EdgeTPUCfgData.test.ts

This commit changes "EdgeTpuCfgData" -> "EdgeTPUCfgData" because TPU is initial of 'Tensor Processing Unit'
ONE-vscode-DCO-1.0-Signed-off-by: Hyeon-Uk <rlagusdnr120@gmail.com>
---
Origianal PR #1691

[EdgeTPU] Fixing typing error

---

media/EdgeTPUCfgEditor/cfgeditor.css
media/EdgeTPUCfgEditor/cfgeditor.html
media/EdgeTPUCfgEditor/displaycfg.js
media/EdgeTPUCfgEditor/index.js
media/EdgeTPUCfgEditor/updateContent.js
media/EdgeTPUCfgEditor/updateUI.js
media/EdgeTPUCfgEditor/vscodeapi.js

For modularization of EdgeTPU, we decided to add a new file name extension for config file for edgetpu compiler.
Its name is 'edgetpucfg'.
'edgetpucfg' has different steps and options than the original cfg file.
Therefore, this commit adds a new directory and files for .edgetpucfg in /media/EdgetpuCfgEditor.
ONE-vscode-DCO-1.0-Signed-off-by: hohee-hee <khappy517@gmail.com>
Co-authored-by: Bumsoo Ko <rhqjatn2398@naver.com>
Co-authored-by: 김현욱 <rlagusdnr120@gmail.com>
---
Original PR #1671

[EdgeTPU] Add files for EdgeTPUCfgEditor 

---

src/OneExplorer/OneExplorer.ts
src/OneExplorer/OneStorage.ts
src/Tests/OneExplorer/OneExplorer.test.ts
src/Tests/OneExplorer/OneStorage.test.ts

This commit Implements Explorer for EdgeTpu Backend
- Implements Explorer for EdgeTpu Backend
- Add Explorer Test code for EdgeTPU Backend
ONE-vscode-DCO-1.0-Signed-off-by: SeungHyunH <vkflek1232@naver.com>
Co-authored-by: Seongwon Im <imsw0529@gmail.com>
Co-authored-by: Dayoung Lee <dayoung.lee@samsung.com>
---
Original PR #1689

[EdgeTpu] Implements Explorer

---

package.json
src/CfgEditor/EdgeTPUCfgEditorPanel.ts
src/extension.ts

This commit creates EdgeTPUCfgEditorPanel.ts that is a panel for .edgetpucfg.
- Create EdgetpuCfgEditorPanel.ts : Cfg Editor Panel for edgetpu cfg editor
- Add register in extension.ts
- Map a new view type with a new file extension - .edgetpucfg
- Error fix : Duplication of setDefaultValues causes error so changed the command name to "setDefaultEdgetpuValues".
- Add objects about setDefaultEdgetpuValues in Commands and Keybindings in package.json
ONE-vscode-DCO-1.0-Signed-off-by: hohee-hee <khappy517@gmail.com>

[EdgeTPU] Introduce EdgeTPUCfgEditorPanel

---

src/CfgEditor/CfgData.ts
src/CfgEditor/EdgeTPUCfgData.ts
src/CfgEditor/ICfgData.ts
src/OneExplorer/OneExplorer.ts

- Extract and implement function about selecting cfg options with `quick pick`
- Extracting functions to make them easier to scale later
ONE-vscode-DCO-1.0-Signed-off-by: Hyeon-Uk <rlagusdnr120@gmail.com>

[EdgeTPU] Expand createCfg method

---

src/Toolchain/JobConfig.ts
src/Toolchain/ToolchainEnv.ts
src/Toolchain/ToolchainProvider.ts

Modify notiTitle in JobConfig.ts from 'Running onecc...' to 'Running tools...' Use active toolchain name in notification and log of ToolchainProvider _run method
---
Origianl PR #1698

[EdgeTPU] Update Toolchain run notification and log 

---

src/Backend/CompilerImpl/DebianCompiler.ts
src/Backend/EdgeTPU/EdgeTPUToolchain.ts
src/Backend/One/OneToolchain.ts
src/Tests/Backend/EdgeTPU/EdgeTPUToolchain.test.ts

Implemented the EdgeTPUCompiler for EdgeTPUToolchain Implemented the following functions in EdgeTPUCompiler
- getToolchainTypes
- parseVersion
- getToolchains
- getInstalledToolchains
- prerequisitesForGetToolchains
---
Origianl PR #1697

[EdgeTPU] Add EdgeTPUCompiler

---

src/Tests/Backend/One/OneToolchain.test.ts

This commit adds test case of prerequisitesForGetToolchian

[Toolchain] Add test for prerequisitesForGetToolchains

---

docs/HowToBuildFromSource.md

This PR updates HowToBuildFromSource.md.
This is to remove `npm vsce` package warning message.
ONE-vscode-DCO-1.0-Signed-off-by: SeungHui Youn <sseung.youn@samsung.com>
Co-authored-by: Jiyoung Giuliana Yun <wldudyun10@gmail.com>
related : https://github.com/Samsung/ONE-vscode/issues/1748

[docs] Update HowToBuildFromSource to use package.json
